/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class ActivityAlertsOverviewDto {
    'hasUnreadAlerts'?: boolean;
    'notificationsEnabled'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hasUnreadAlerts",
            "baseName": "hasUnreadAlerts",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "notificationsEnabled",
            "baseName": "notificationsEnabled",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ActivityAlertsOverviewDto.attributeTypeMap;
    }

    public constructor() {
    }
}

