/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrganizationSummaryDto } from '../models/OrganizationSummaryDto';
import { TaskDto } from '../models/TaskDto';
import { User } from '../models/User';


export class ActivityAlertDto {
    'activityAlertIdentifier'?: string;
    'activityAlertSubTitle'?: string;
    'activityAlertTitle'?: string;
    'activityAlertType'?: ActivityAlertDtoActivityAlertTypeEnum;
    'createdDateTime'?: Date;
    'organization'?: OrganizationSummaryDto;
    'targetIdentifier'?: string;
    'targetType'?: ActivityAlertDtoTargetTypeEnum;
    'targetUser'?: User;
    'task'?: TaskDto;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "activityAlertIdentifier",
            "baseName": "activityAlertIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "activityAlertSubTitle",
            "baseName": "activityAlertSubTitle",
            "type": "string",
            "format": ""
        },
        {
            "name": "activityAlertTitle",
            "baseName": "activityAlertTitle",
            "type": "string",
            "format": ""
        },
        {
            "name": "activityAlertType",
            "baseName": "activityAlertType",
            "type": "ActivityAlertDtoActivityAlertTypeEnum",
            "format": ""
        },
        {
            "name": "createdDateTime",
            "baseName": "createdDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "organization",
            "baseName": "organization",
            "type": "OrganizationSummaryDto",
            "format": ""
        },
        {
            "name": "targetIdentifier",
            "baseName": "targetIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetType",
            "baseName": "targetType",
            "type": "ActivityAlertDtoTargetTypeEnum",
            "format": ""
        },
        {
            "name": "targetUser",
            "baseName": "targetUser",
            "type": "User",
            "format": ""
        },
        {
            "name": "task",
            "baseName": "task",
            "type": "TaskDto",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ActivityAlertDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ActivityAlertDtoActivityAlertTypeEnum {
    CreateTask = 'CREATE_TASK',
    CreateComment = 'CREATE_COMMENT',
    CreateAttachment = 'CREATE_ATTACHMENT',
    UpdateTask = 'UPDATE_TASK',
    UpdateComment = 'UPDATE_COMMENT',
    DeleteTask = 'DELETE_TASK',
    UndeleteTask = 'UNDELETE_TASK',
    DeleteComment = 'DELETE_COMMENT',
    AssignTask = 'ASSIGN_TASK',
    MarkComplete = 'MARK_COMPLETE',
    RemoveUserFromOrganization = 'REMOVE_USER_FROM_ORGANIZATION',
    AddUserToOrganization = 'ADD_USER_TO_ORGANIZATION',
    MakeAdminForOrganization = 'MAKE_ADMIN_FOR_ORGANIZATION',
    RemoveAdminForOrganization = 'REMOVE_ADMIN_FOR_ORGANIZATION',
    MentionTask = 'MENTION_TASK',
    MentionComment = 'MENTION_COMMENT',
    TaskIsDueToday = 'TASK_IS_DUE_TODAY',
    CreateTaskBundle = 'CREATE_TASK_BUNDLE',
    ShareTask = 'SHARE_TASK'
}
export enum ActivityAlertDtoTargetTypeEnum {
    Task = 'TASK',
    User = 'USER',
    Patient = 'PATIENT',
    PatientNote = 'PATIENT_NOTE',
    Comment = 'COMMENT',
    Attachment = 'ATTACHMENT',
    Organization = 'ORGANIZATION',
    List = 'LIST',
    ListLabel = 'LIST_LABEL',
    TaskLabel = 'TASK_LABEL',
    Protocol = 'PROTOCOL',
    ProtocolItem = 'PROTOCOL_ITEM',
    OrgUser = 'ORG_USER',
    ListUser = 'LIST_USER',
    UserInvite = 'USER_INVITE',
    TaskGroup = 'TASK_GROUP',
    TaskTemplate = 'TASK_TEMPLATE',
    TaskStatus = 'TASK_STATUS',
    PatientList = 'PATIENT_LIST',
    SharedLabel = 'SHARED_LABEL',
    PatientLabel = 'PATIENT_LABEL',
    CustomField = 'CUSTOM_FIELD',
    PatientMetaData = 'PATIENT_META_DATA',
    TaskMetaData = 'TASK_META_DATA',
    ProviderMetaData = 'PROVIDER_META_DATA',
    TaskOutcome = 'TASK_OUTCOME',
    TransactionEvent = 'TRANSACTION_EVENT',
    Provider = 'PROVIDER',
    Template = 'TEMPLATE',
    Contact = 'CONTACT',
    Profile = 'PROFILE'
}

