/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AuditDto } from '../models/AuditDto';


export class AuditAllTaskListDto {
    'auditList'?: Array<AuditDto>;
    'listName'?: string;
    'taskListId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "auditList",
            "baseName": "auditList",
            "type": "Array<AuditDto>",
            "format": ""
        },
        {
            "name": "listName",
            "baseName": "listName",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskListId",
            "baseName": "taskListId",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return AuditAllTaskListDto.attributeTypeMap;
    }

    public constructor() {
    }
}

