/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserSummaryDto } from '../models/UserSummaryDto';


export class AuditDto {
    'activityFeed'?: string;
    'auditEventType'?: AuditDtoAuditEventTypeEnum;
    'auditEventTypeDescription'?: string;
    'auditId'?: number;
    'createdBy'?: string;
    'createdDateTime'?: Date;
    'currentState'?: string;
    'parentAudit'?: number;
    'previousState'?: string;
    'targetId'?: number;
    'targetIdType'?: AuditDtoTargetIdTypeEnum;
    'taskHistoryDetails'?: string;
    'taskHistoryType'?: string;
    'updatedBy'?: string;
    'updatedDateTime'?: Date;
    'user'?: UserSummaryDto;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "activityFeed",
            "baseName": "activityFeed",
            "type": "string",
            "format": ""
        },
        {
            "name": "auditEventType",
            "baseName": "auditEventType",
            "type": "AuditDtoAuditEventTypeEnum",
            "format": ""
        },
        {
            "name": "auditEventTypeDescription",
            "baseName": "auditEventTypeDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "auditId",
            "baseName": "auditId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdDateTime",
            "baseName": "createdDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "currentState",
            "baseName": "currentState",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentAudit",
            "baseName": "parentAudit",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "previousState",
            "baseName": "previousState",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetId",
            "baseName": "targetId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "targetIdType",
            "baseName": "targetIdType",
            "type": "AuditDtoTargetIdTypeEnum",
            "format": ""
        },
        {
            "name": "taskHistoryDetails",
            "baseName": "taskHistoryDetails",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskHistoryType",
            "baseName": "taskHistoryType",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedBy",
            "baseName": "updatedBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedDateTime",
            "baseName": "updatedDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "UserSummaryDto",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AuditDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AuditDtoAuditEventTypeEnum {
    CreateTask = 'CREATE_TASK',
    CreateTaskFromEmail = 'CREATE_TASK_FROM_EMAIL',
    CreateRecurringTask = 'CREATE_RECURRING_TASK',
    CreateUser = 'CREATE_USER',
    CreateUserGroup = 'CREATE_USER_GROUP',
    CreatePatient = 'CREATE_PATIENT',
    CreatePatientNote = 'CREATE_PATIENT_NOTE',
    CreateComment = 'CREATE_COMMENT',
    CreateAttachment = 'CREATE_ATTACHMENT',
    CreateOrganization = 'CREATE_ORGANIZATION',
    CreateList = 'CREATE_LIST',
    CreateProtocol = 'CREATE_PROTOCOL',
    CreateProtocolItem = 'CREATE_PROTOCOL_ITEM',
    ChangeEmail = 'CHANGE_EMAIL',
    UpdateTask = 'UPDATE_TASK',
    UpdateTaskDescription = 'UPDATE_TASK_DESCRIPTION',
    UpdateTaskDetails = 'UPDATE_TASK_DETAILS',
    UpdateTaskPatient = 'UPDATE_TASK_PATIENT',
    UpdateTaskPriority = 'UPDATE_TASK_PRIORITY',
    UpdateTaskStartDate = 'UPDATE_TASK_START_DATE',
    UpdateTaskDueDate = 'UPDATE_TASK_DUE_DATE',
    UpdateTaskStatus = 'UPDATE_TASK_STATUS',
    UpdateTaskWorkflowStatus = 'UPDATE_TASK_WORKFLOW_STATUS',
    UpdateTaskRecurringSchedule = 'UPDATE_TASK_RECURRING_SCHEDULE',
    UpdateUser = 'UPDATE_USER',
    UpdateUserGroup = 'UPDATE_USER_GROUP',
    UpdateUserFirstname = 'UPDATE_USER_FIRSTNAME',
    UpdateUserLastname = 'UPDATE_USER_LASTNAME',
    UpdateUserSpecialty = 'UPDATE_USER_SPECIALTY',
    UpdateUserSubspecialty = 'UPDATE_USER_SUBSPECIALTY',
    UpdateUserTitle = 'UPDATE_USER_TITLE',
    UpdateUserCredentials = 'UPDATE_USER_CREDENTIALS',
    UpdateUserAccountphone = 'UPDATE_USER_ACCOUNTPHONE',
    UpdateUserWorkphone = 'UPDATE_USER_WORKPHONE',
    UpdateUserHomephone = 'UPDATE_USER_HOMEPHONE',
    UpdateUserFaxnumber = 'UPDATE_USER_FAXNUMBER',
    UpdateUserProfilepic = 'UPDATE_USER_PROFILEPIC',
    UpdateUserNotificationprefEmail = 'UPDATE_USER_NOTIFICATIONPREF_EMAIL',
    UpdateUserNotificationprefPush = 'UPDATE_USER_NOTIFICATIONPREF_PUSH',
    UpdateUserPrefDisplayColumns = 'UPDATE_USER_PREF_DISPLAY_COLUMNS',
    UpdateUserPrefDisplayOptions = 'UPDATE_USER_PREF_DISPLAY_OPTIONS',
    UpdateUserPrefDisplayGroups = 'UPDATE_USER_PREF_DISPLAY_GROUPS',
    UpdatePatient = 'UPDATE_PATIENT',
    UpdatePatientNote = 'UPDATE_PATIENT_NOTE',
    UpdateComment = 'UPDATE_COMMENT',
    UpdateAttachment = 'UPDATE_ATTACHMENT',
    UpdateOrganization = 'UPDATE_ORGANIZATION',
    UpdateOrganizationLegalName = 'UPDATE_ORGANIZATION_LEGAL_NAME',
    UpdateOrganizationSignatureStatus = 'UPDATE_ORGANIZATION_SIGNATURE_STATUS',
    BaaSignatureRequestSent = 'BAA_SIGNATURE_REQUEST_SENT',
    UpdateList = 'UPDATE_LIST',
    UpdateListNotificationOn = 'UPDATE_LIST_NOTIFICATION_ON',
    UpdateListNotificationOff = 'UPDATE_LIST_NOTIFICATION_OFF',
    UpdateListUserPref = 'UPDATE_LIST_USER_PREF',
    UpdateListArchived = 'UPDATE_LIST_ARCHIVED',
    UpdateListUnarchived = 'UPDATE_LIST_UNARCHIVED',
    UpdateProtocol = 'UPDATE_PROTOCOL',
    UpdateProtocolItem = 'UPDATE_PROTOCOL_ITEM',
    DeleteTask = 'DELETE_TASK',
    UndeleteTask = 'UNDELETE_TASK',
    DeleteUser = 'DELETE_USER',
    DeleteUserProfilepic = 'DELETE_USER_PROFILEPIC',
    ArchivePatient = 'ARCHIVE_PATIENT',
    UnarchivePatient = 'UNARCHIVE_PATIENT',
    DeletePatient = 'DELETE_PATIENT',
    RestorePatient = 'RESTORE_PATIENT',
    DeletePatientNote = 'DELETE_PATIENT_NOTE',
    DeleteComment = 'DELETE_COMMENT',
    DeleteAttachment = 'DELETE_ATTACHMENT',
    DeleteOrganization = 'DELETE_ORGANIZATION',
    DeleteList = 'DELETE_LIST',
    DeleteProtocol = 'DELETE_PROTOCOL',
    DeleteProtocolItem = 'DELETE_PROTOCOL_ITEM',
    AssignTask = 'ASSIGN_TASK',
    SetPriority = 'SET_PRIORITY',
    MarkTasksRead = 'MARK_TASKS_READ',
    MarkRead = 'MARK_READ',
    MarkComplete = 'MARK_COMPLETE',
    MarkIncomplete = 'MARK_INCOMPLETE',
    MergePatient = 'MERGE_PATIENT',
    FlagAsUnread = 'FLAG_AS_UNREAD',
    UnflagAsRead = 'UNFLAG_AS_READ',
    AddUserToOrganization = 'ADD_USER_TO_ORGANIZATION',
    AddUserToList = 'ADD_USER_TO_LIST',
    AddPatientToTask = 'ADD_PATIENT_TO_TASK',
    RemoveUserFromList = 'REMOVE_USER_FROM_LIST',
    UserLeavesList = 'USER_LEAVES_LIST',
    UserLeavesOrganization = 'USER_LEAVES_ORGANIZATION',
    MarkTaskUnassigned = 'MARK_TASK_UNASSIGNED',
    RemoveUserFromOrganization = 'REMOVE_USER_FROM_ORGANIZATION',
    RemoveUserGroupFromOrganization = 'REMOVE_USER_GROUP_FROM_ORGANIZATION',
    AddExistingTaskToList = 'ADD_EXISTING_TASK_TO_LIST',
    AddNewTaskToList = 'ADD_NEW_TASK_TO_LIST',
    AddExistingSubtaskToAnotherTask = 'ADD_EXISTING_SUBTASK_TO_ANOTHER_TASK',
    InviteUserToOrganization = 'INVITE_USER_TO_ORGANIZATION',
    InviteUserToOrgAndList = 'INVITE_USER_TO_ORG_AND_LIST',
    AcceptInvitationToOrganization = 'ACCEPT_INVITATION_TO_ORGANIZATION',
    AcceptInvitationToList = 'ACCEPT_INVITATION_TO_LIST',
    RejectInvitationToList = 'REJECT_INVITATION_TO_LIST',
    CancelInvitationToList = 'CANCEL_INVITATION_TO_LIST',
    ChangeTaskPriority = 'CHANGE_TASK_PRIORITY',
    AddStartDate = 'ADD_START_DATE',
    AddDueDate = 'ADD_DUE_DATE',
    MarkTasksAsSeen = 'MARK_TASKS_AS_SEEN',
    MarkTaskAsSeen = 'MARK_TASK_AS_SEEN',
    AddSubtask = 'ADD_SUBTASK',
    Notifiable = 'NOTIFIABLE',
    ActivityFeed = 'ACTIVITY_FEED',
    MakeAdminForList = 'MAKE_ADMIN_FOR_LIST',
    RemoveAdminForList = 'REMOVE_ADMIN_FOR_LIST',
    MarkListInviteInactive = 'MARK_LIST_INVITE_INACTIVE',
    MarkTaskInactive = 'MARK_TASK_INACTIVE',
    MakeAdminForOrganization = 'MAKE_ADMIN_FOR_ORGANIZATION',
    RemoveAdminForOrganization = 'REMOVE_ADMIN_FOR_ORGANIZATION',
    CancelInvitationToOrganization = 'CANCEL_INVITATION_TO_ORGANIZATION',
    DuplicateTask = 'DUPLICATE_TASK',
    TaskReminderSet = 'TASK_REMINDER_SET',
    TaskReminderNotificationTriggered = 'TASK_REMINDER_NOTIFICATION_TRIGGERED',
    TaskDueDateReminderTriggered = 'TASK_DUE_DATE_REMINDER_TRIGGERED',
    SelectSubscription = 'SELECT_SUBSCRIPTION',
    BillingDetailsUpdate = 'BILLING_DETAILS_UPDATE',
    CreateListLabel = 'CREATE_LIST_LABEL',
    DeleteListLabel = 'DELETE_LIST_LABEL',
    AddTaskLabel = 'ADD_TASK_LABEL',
    EditTaskLabel = 'EDIT_TASK_LABEL',
    RemoveTaskLabel = 'REMOVE_TASK_LABEL',
    CreateTaskGroup = 'CREATE_TASK_GROUP',
    EditTaskGroup = 'EDIT_TASK_GROUP',
    DeleteTaskGroup = 'DELETE_TASK_GROUP',
    AddTaskToGroup = 'ADD_TASK_TO_GROUP',
    RemoveTaskFromGroup = 'REMOVE_TASK_FROM_GROUP',
    CreateTaskTemplate = 'CREATE_TASK_TEMPLATE',
    EditTaskTemplate = 'EDIT_TASK_TEMPLATE',
    DeleteTaskTemplate = 'DELETE_TASK_TEMPLATE',
    AddTaskToTemplate = 'ADD_TASK_TO_TEMPLATE',
    RemoveTaskFromTemplate = 'REMOVE_TASK_FROM_TEMPLATE',
    DuplicateTaskTemplate = 'DUPLICATE_TASK_TEMPLATE',
    DuplicateTaskTemplateToOrg = 'DUPLICATE_TASK_TEMPLATE_TO_ORG',
    MoveTaskTemplate = 'MOVE_TASK_TEMPLATE',
    CreateTaskBundle = 'CREATE_TASK_BUNDLE',
    UpdateTaskBundle = 'UPDATE_TASK_BUNDLE',
    DuplicateTaskBundle = 'DUPLICATE_TASK_BUNDLE',
    DeleteTaskBundle = 'DELETE_TASK_BUNDLE',
    UndeleteTaskBundle = 'UNDELETE_TASK_BUNDLE',
    MoveTaskBundle = 'MOVE_TASK_BUNDLE',
    MoreTasksTaskBundle = 'MORE_TASKS_TASK_BUNDLE',
    MentionTask = 'MENTION_TASK',
    MentionComment = 'MENTION_COMMENT',
    CreateTaskStatus = 'CREATE_TASK_STATUS',
    EditTaskStatus = 'EDIT_TASK_STATUS',
    DeleteTaskStatus = 'DELETE_TASK_STATUS',
    CreatePatientList = 'CREATE_PATIENT_LIST',
    UpdatePatientList = 'UPDATE_PATIENT_LIST',
    DeletePatientList = 'DELETE_PATIENT_LIST',
    CreateAttachmentPatient = 'CREATE_ATTACHMENT_PATIENT',
    UpdateAttachmentPatient = 'UPDATE_ATTACHMENT_PATIENT',
    DeleteAttachmentPatient = 'DELETE_ATTACHMENT_PATIENT',
    CreateSharedPatientLabel = 'CREATE_SHARED_PATIENT_LABEL',
    DeleteSharedPatientLabel = 'DELETE_SHARED_PATIENT_LABEL',
    EditSharedPatientLabel = 'EDIT_SHARED_PATIENT_LABEL',
    AddPatientLabel = 'ADD_PATIENT_LABEL',
    RemovePatientLabel = 'REMOVE_PATIENT_LABEL',
    PinnedPatientNote = 'PINNED_PATIENT_NOTE',
    UnpinnedPatientNote = 'UNPINNED_PATIENT_NOTE',
    CreateCustomField = 'CREATE_CUSTOM_FIELD',
    EditCustomField = 'EDIT_CUSTOM_FIELD',
    DeleteCustomField = 'DELETE_CUSTOM_FIELD',
    SavePatientMetaData = 'SAVE_PATIENT_META_DATA',
    SaveTaskMetaData = 'SAVE_TASK_META_DATA',
    SaveProviderMetaData = 'SAVE_PROVIDER_META_DATA',
    CreateTaskLink = 'CREATE_TASK_LINK',
    EditTaskLink = 'EDIT_TASK_LINK',
    DeleteTaskLink = 'DELETE_TASK_LINK',
    CreateTaskOutcome = 'CREATE_TASK_OUTCOME',
    EditTaskOutcome = 'EDIT_TASK_OUTCOME',
    DeleteTaskOutcome = 'DELETE_TASK_OUTCOME',
    SelectTaskOutcome = 'SELECT_TASK_OUTCOME',
    BulkTaskAssign = 'BULK_TASK_ASSIGN',
    UpdateExternalIdentifier = 'UPDATE_EXTERNAL_IDENTIFIER',
    LinkedWorkflowLaunched = 'LINKED_WORKFLOW_LAUNCHED',
    CreateTemplate = 'CREATE_TEMPLATE',
    EditTemplate = 'EDIT_TEMPLATE',
    DeleteTemplate = 'DELETE_TEMPLATE',
    CreateContact = 'CREATE_CONTACT',
    EditContact = 'EDIT_CONTACT',
    DeleteContact = 'DELETE_CONTACT',
    RestoreUser = 'RESTORE_USER',
    ActivateTask = 'ACTIVATE_TASK',
    SendSlack = 'SEND_SLACK',
    SendEmail = 'SEND_EMAIL',
    SendSecureMessage = 'SEND_SECURE_MESSAGE',
    TaskOverdue = 'TASK_OVERDUE',
    ShareTask = 'SHARE_TASK'
}
export enum AuditDtoTargetIdTypeEnum {
    Task = 'TASK',
    User = 'USER',
    Patient = 'PATIENT',
    PatientNote = 'PATIENT_NOTE',
    Comment = 'COMMENT',
    Attachment = 'ATTACHMENT',
    Organization = 'ORGANIZATION',
    List = 'LIST',
    ListLabel = 'LIST_LABEL',
    TaskLabel = 'TASK_LABEL',
    Protocol = 'PROTOCOL',
    ProtocolItem = 'PROTOCOL_ITEM',
    OrgUser = 'ORG_USER',
    ListUser = 'LIST_USER',
    UserInvite = 'USER_INVITE',
    TaskGroup = 'TASK_GROUP',
    TaskTemplate = 'TASK_TEMPLATE',
    TaskStatus = 'TASK_STATUS',
    PatientList = 'PATIENT_LIST',
    SharedLabel = 'SHARED_LABEL',
    PatientLabel = 'PATIENT_LABEL',
    CustomField = 'CUSTOM_FIELD',
    PatientMetaData = 'PATIENT_META_DATA',
    TaskMetaData = 'TASK_META_DATA',
    ProviderMetaData = 'PROVIDER_META_DATA',
    TaskOutcome = 'TASK_OUTCOME',
    TransactionEvent = 'TRANSACTION_EVENT',
    Provider = 'PROVIDER',
    Template = 'TEMPLATE',
    Contact = 'CONTACT',
    Profile = 'PROFILE'
}

