/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubscriptionDto } from '../models/SubscriptionDto';


export class BillingDetailsDto {
    'billingAddressCity'?: string;
    'billingAddressLine1'?: string;
    'billingAddressLine2'?: string;
    'billingAddressPostalCode'?: string;
    'billingAddressState'?: string;
    'billingEmail'?: string;
    'billingName'?: string;
    'cardBrand'?: string;
    'cardExpiration'?: string;
    'cardLastFour'?: string;
    'cardTokenIdentifier'?: string;
    'discountCode'?: string;
    'subscriptionDetails'?: SubscriptionDto;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "billingAddressCity",
            "baseName": "billingAddressCity",
            "type": "string",
            "format": ""
        },
        {
            "name": "billingAddressLine1",
            "baseName": "billingAddressLine1",
            "type": "string",
            "format": ""
        },
        {
            "name": "billingAddressLine2",
            "baseName": "billingAddressLine2",
            "type": "string",
            "format": ""
        },
        {
            "name": "billingAddressPostalCode",
            "baseName": "billingAddressPostalCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "billingAddressState",
            "baseName": "billingAddressState",
            "type": "string",
            "format": ""
        },
        {
            "name": "billingEmail",
            "baseName": "billingEmail",
            "type": "string",
            "format": ""
        },
        {
            "name": "billingName",
            "baseName": "billingName",
            "type": "string",
            "format": ""
        },
        {
            "name": "cardBrand",
            "baseName": "cardBrand",
            "type": "string",
            "format": ""
        },
        {
            "name": "cardExpiration",
            "baseName": "cardExpiration",
            "type": "string",
            "format": ""
        },
        {
            "name": "cardLastFour",
            "baseName": "cardLastFour",
            "type": "string",
            "format": ""
        },
        {
            "name": "cardTokenIdentifier",
            "baseName": "cardTokenIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "discountCode",
            "baseName": "discountCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "subscriptionDetails",
            "baseName": "subscriptionDetails",
            "type": "SubscriptionDto",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BillingDetailsDto.attributeTypeMap;
    }

    public constructor() {
    }
}

