/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubscriptionDto } from '../models/SubscriptionDto';


export class BillingEstimateDto {
    'activeDockLiteUserCount'?: number;
    'activeUserCount'?: number;
    'annualEstimate'?: number;
    'monthlyDockLitePerUserCost'?: number;
    'monthlyEstimate'?: number;
    'monthlyPerUserCost'?: number;
    'nextBillingDate'?: Date;
    'professionalServicesEstimate'?: number;
    'subscriptionDetails'?: SubscriptionDto;
    'totalEstimate'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "activeDockLiteUserCount",
            "baseName": "activeDockLiteUserCount",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "activeUserCount",
            "baseName": "activeUserCount",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "annualEstimate",
            "baseName": "annualEstimate",
            "type": "number",
            "format": "double"
        },
        {
            "name": "monthlyDockLitePerUserCost",
            "baseName": "monthlyDockLitePerUserCost",
            "type": "number",
            "format": "double"
        },
        {
            "name": "monthlyEstimate",
            "baseName": "monthlyEstimate",
            "type": "number",
            "format": "double"
        },
        {
            "name": "monthlyPerUserCost",
            "baseName": "monthlyPerUserCost",
            "type": "number",
            "format": "double"
        },
        {
            "name": "nextBillingDate",
            "baseName": "nextBillingDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "professionalServicesEstimate",
            "baseName": "professionalServicesEstimate",
            "type": "number",
            "format": "double"
        },
        {
            "name": "subscriptionDetails",
            "baseName": "subscriptionDetails",
            "type": "SubscriptionDto",
            "format": ""
        },
        {
            "name": "totalEstimate",
            "baseName": "totalEstimate",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return BillingEstimateDto.attributeTypeMap;
    }

    public constructor() {
    }
}

