/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserSummaryDto } from '../models/UserSummaryDto';


export class CommentDto {
    'comment'?: string;
    'commentId'?: number;
    'commentIdentifier'?: string;
    'commentMentions'?: any;
    'creator'?: UserSummaryDto;
    'dateCreated'?: Date;
    'dateUpdated'?: Date;
    'hasMentions'?: boolean;
    'sortIndex'?: number;
    'taskIdentifier'?: string;
    'taskWorkflowIdentifier'?: string;
    'tokenizedComment'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "commentId",
            "baseName": "commentId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "commentIdentifier",
            "baseName": "commentIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "commentMentions",
            "baseName": "commentMentions",
            "type": "any",
            "format": ""
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "UserSummaryDto",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "dateCreated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateUpdated",
            "baseName": "dateUpdated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "hasMentions",
            "baseName": "hasMentions",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sortIndex",
            "baseName": "sortIndex",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "taskIdentifier",
            "baseName": "taskIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskWorkflowIdentifier",
            "baseName": "taskWorkflowIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "tokenizedComment",
            "baseName": "tokenizedComment",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CommentDto.attributeTypeMap;
    }

    public constructor() {
    }
}

