/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class ContactDto {
    'email'?: string;
    'faxPhoneNumber'?: string;
    'identifier'?: string;
    'mobilePhoneNumber'?: string;
    'name'?: string;
    'notes'?: string;
    'type'?: ContactDtoTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "faxPhoneNumber",
            "baseName": "faxPhoneNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "mobilePhoneNumber",
            "baseName": "mobilePhoneNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ContactDtoTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ContactDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ContactDtoTypeEnum {
    Individual = 'INDIVIDUAL',
    Organization = 'ORGANIZATION'
}

