/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomFieldOptionDto } from '../models/CustomFieldOptionDto';
import { ProfileTypeDto } from '../models/ProfileTypeDto';


export class CustomFieldDto {
    'active'?: boolean;
    'contextType'?: CustomFieldDtoContextTypeEnum;
    'displayOptions'?: any;
    'externalIdentifier'?: string;
    'fieldCategoryType'?: CustomFieldDtoFieldCategoryTypeEnum;
    'fieldType'?: CustomFieldDtoFieldTypeEnum;
    'identifier'?: string;
    'name'?: string;
    'options'?: Array<CustomFieldOptionDto>;
    'placeholder'?: string;
    'relatedProfileType'?: ProfileTypeDto;
    'required'?: boolean;
    'sortIndex'?: number;
    'targetType'?: CustomFieldDtoTargetTypeEnum;
    'taskListIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "contextType",
            "baseName": "contextType",
            "type": "CustomFieldDtoContextTypeEnum",
            "format": ""
        },
        {
            "name": "displayOptions",
            "baseName": "displayOptions",
            "type": "any",
            "format": ""
        },
        {
            "name": "externalIdentifier",
            "baseName": "externalIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "fieldCategoryType",
            "baseName": "fieldCategoryType",
            "type": "CustomFieldDtoFieldCategoryTypeEnum",
            "format": ""
        },
        {
            "name": "fieldType",
            "baseName": "fieldType",
            "type": "CustomFieldDtoFieldTypeEnum",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Array<CustomFieldOptionDto>",
            "format": ""
        },
        {
            "name": "placeholder",
            "baseName": "placeholder",
            "type": "string",
            "format": ""
        },
        {
            "name": "relatedProfileType",
            "baseName": "relatedProfileType",
            "type": "ProfileTypeDto",
            "format": ""
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sortIndex",
            "baseName": "sortIndex",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "targetType",
            "baseName": "targetType",
            "type": "CustomFieldDtoTargetTypeEnum",
            "format": ""
        },
        {
            "name": "taskListIdentifier",
            "baseName": "taskListIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CustomFieldDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum CustomFieldDtoContextTypeEnum {
    Predefined = 'PREDEFINED',
    Custom = 'CUSTOM'
}
export enum CustomFieldDtoFieldCategoryTypeEnum {
    PatientPersonal = 'PATIENT_PERSONAL',
    PatientContact = 'PATIENT_CONTACT',
    PatientOther = 'PATIENT_OTHER',
    TaskOther = 'TASK_OTHER',
    TaskCore = 'TASK_CORE',
    ProviderOther = 'PROVIDER_OTHER',
    Profile = 'PROFILE'
}
export enum CustomFieldDtoFieldTypeEnum {
    Text = 'TEXT',
    LongText = 'LONG_TEXT',
    Number = 'NUMBER',
    Date = 'DATE',
    DateTime = 'DATE_TIME',
    PickList = 'PICK_LIST',
    Boolean = 'BOOLEAN',
    MultiSelect = 'MULTI_SELECT',
    Hyperlink = 'HYPERLINK',
    Relationship = 'RELATIONSHIP'
}
export enum CustomFieldDtoTargetTypeEnum {
    Task = 'TASK',
    Patient = 'PATIENT',
    Provider = 'PROVIDER',
    Profile = 'PROFILE'
}

