/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class DisplayColumnPrefDto {
    'displayColumn'?: string;
    'sortIndex'?: number;
    'width'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "displayColumn",
            "baseName": "displayColumn",
            "type": "string",
            "format": ""
        },
        {
            "name": "sortIndex",
            "baseName": "sortIndex",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DisplayColumnPrefDto.attributeTypeMap;
    }

    public constructor() {
    }
}

