/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class GenderIdentityTypeDto {
    'description'?: string;
    'genderIdentityType'?: GenderIdentityTypeDtoGenderIdentityTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "genderIdentityType",
            "baseName": "genderIdentityType",
            "type": "GenderIdentityTypeDtoGenderIdentityTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GenderIdentityTypeDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum GenderIdentityTypeDtoGenderIdentityTypeEnum {
    Male = 'MALE',
    Female = 'FEMALE',
    TransMan = 'TRANS_MAN',
    TransWoman = 'TRANS_WOMAN',
    NonConforming = 'NON_CONFORMING',
    Decline = 'DECLINE'
}

