/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class GroupedMetricDto {
    'metricColor'?: string;
    'metricName'?: string;
    'metricValue'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "metricColor",
            "baseName": "metricColor",
            "type": "string",
            "format": ""
        },
        {
            "name": "metricName",
            "baseName": "metricName",
            "type": "string",
            "format": ""
        },
        {
            "name": "metricValue",
            "baseName": "metricValue",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return GroupedMetricDto.attributeTypeMap;
    }

    public constructor() {
    }
}

