/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PatientSummaryDto } from '../models/PatientSummaryDto';
import { TaskItemDto } from '../models/TaskItemDto';


export class GroupedTasksDto {
    'groupIdentifier'?: string;
    'groupName'?: string;
    'groupType'?: GroupedTasksDtoGroupTypeEnum;
    'hasMore'?: boolean;
    'moreTasksIndex'?: number;
    'patients'?: Array<PatientSummaryDto>;
    'sortIndexOfTaskInGroup'?: number;
    'tasks'?: Array<TaskItemDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "groupIdentifier",
            "baseName": "groupIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupName",
            "baseName": "groupName",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupType",
            "baseName": "groupType",
            "type": "GroupedTasksDtoGroupTypeEnum",
            "format": ""
        },
        {
            "name": "hasMore",
            "baseName": "hasMore",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "moreTasksIndex",
            "baseName": "moreTasksIndex",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "patients",
            "baseName": "patients",
            "type": "Array<PatientSummaryDto>",
            "format": ""
        },
        {
            "name": "sortIndexOfTaskInGroup",
            "baseName": "sortIndexOfTaskInGroup",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "tasks",
            "baseName": "tasks",
            "type": "Array<TaskItemDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GroupedTasksDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum GroupedTasksDtoGroupTypeEnum {
    Overdue = 'OVERDUE',
    Today = 'TODAY',
    Tomorrow = 'TOMORROW',
    Next7Days = 'NEXT_7_DAYS',
    NoDueDate = 'NO_DUE_DATE',
    AllOther = 'ALL_OTHER',
    AssignedByMe = 'ASSIGNED_BY_ME',
    CompletedToday = 'COMPLETED_TODAY',
    Completed7Days = 'COMPLETED_7_DAYS',
    OrgOverdue = 'ORG_OVERDUE',
    OrgToday = 'ORG_TODAY',
    OrgTomorrow = 'ORG_TOMORROW',
    OrgNext7Days = 'ORG_NEXT_7_DAYS',
    OrgNoDueDate = 'ORG_NO_DUE_DATE',
    OrgAllOther = 'ORG_ALL_OTHER',
    OrgCompletedToday = 'ORG_COMPLETED_TODAY',
    OrgCompleted7Days = 'ORG_COMPLETED_7_DAYS',
    Escalated = 'ESCALATED',
    Shared = 'SHARED',
    SharedCompletedToday = 'SHARED_COMPLETED_TODAY',
    SharedCompleted7Days = 'SHARED_COMPLETED_7_DAYS'
}

