/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Timestamp } from '../models/Timestamp';


export class InboxRequest {
    'createdBy'?: string;
    'createdDateTime'?: Timestamp;
    'message'?: string;
    'messageIdentifier'?: string;
    'messageReceivedDateTime'?: Date;
    'processed'?: boolean;
    'requestId'?: number;
    'sender'?: string;
    'subject'?: string;
    'updatedBy'?: string;
    'updatedDateTime'?: Timestamp;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdDateTime",
            "baseName": "createdDateTime",
            "type": "Timestamp",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "messageIdentifier",
            "baseName": "messageIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "messageReceivedDateTime",
            "baseName": "messageReceivedDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "processed",
            "baseName": "processed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "requestId",
            "baseName": "requestId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "sender",
            "baseName": "sender",
            "type": "string",
            "format": ""
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedBy",
            "baseName": "updatedBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedDateTime",
            "baseName": "updatedDateTime",
            "type": "Timestamp",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InboxRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

