/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class InvoiceDetailsDto {
    'chargeAmount'?: number;
    'chargeDate'?: Date;
    'currency'?: string;
    'invoiceCreatedDate'?: Date;
    'invoiceIdentifier'?: string;
    'invoiceNumber'?: string;
    'invoicePDFUrl'?: string;
    'receiptNumber'?: string;
    'receiptUrl'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "chargeAmount",
            "baseName": "chargeAmount",
            "type": "number",
            "format": "double"
        },
        {
            "name": "chargeDate",
            "baseName": "chargeDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "invoiceCreatedDate",
            "baseName": "invoiceCreatedDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "invoiceIdentifier",
            "baseName": "invoiceIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "invoiceNumber",
            "baseName": "invoiceNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "invoicePDFUrl",
            "baseName": "invoicePDFUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "receiptNumber",
            "baseName": "receiptNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "receiptUrl",
            "baseName": "receiptUrl",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InvoiceDetailsDto.attributeTypeMap;
    }

    public constructor() {
    }
}

