/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class ListUserPreferenceDto {
    'displayOptions'?: any;
    'listDisplayColumnPrefs'?: any;
    'listDisplayColumns'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "displayOptions",
            "baseName": "displayOptions",
            "type": "any",
            "format": ""
        },
        {
            "name": "listDisplayColumnPrefs",
            "baseName": "listDisplayColumnPrefs",
            "type": "any",
            "format": ""
        },
        {
            "name": "listDisplayColumns",
            "baseName": "listDisplayColumns",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListUserPreferenceDto.attributeTypeMap;
    }

    public constructor() {
    }
}

