/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class ModelFile {
    'absolute'?: boolean;
    'absoluteFile'?: HttpFile;
    'absolutePath'?: string;
    'canonicalFile'?: HttpFile;
    'canonicalPath'?: string;
    'directory'?: boolean;
    'file'?: boolean;
    'freeSpace'?: number;
    'hidden'?: boolean;
    'name'?: string;
    'parent'?: string;
    'parentFile'?: HttpFile;
    'path'?: string;
    'totalSpace'?: number;
    'usableSpace'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "absolute",
            "baseName": "absolute",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "absoluteFile",
            "baseName": "absoluteFile",
            "type": "HttpFile",
            "format": "binary"
        },
        {
            "name": "absolutePath",
            "baseName": "absolutePath",
            "type": "string",
            "format": ""
        },
        {
            "name": "canonicalFile",
            "baseName": "canonicalFile",
            "type": "HttpFile",
            "format": "binary"
        },
        {
            "name": "canonicalPath",
            "baseName": "canonicalPath",
            "type": "string",
            "format": ""
        },
        {
            "name": "directory",
            "baseName": "directory",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "file",
            "baseName": "file",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "freeSpace",
            "baseName": "freeSpace",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "hidden",
            "baseName": "hidden",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "parent",
            "baseName": "parent",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentFile",
            "baseName": "parentFile",
            "type": "HttpFile",
            "format": "binary"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalSpace",
            "baseName": "totalSpace",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "usableSpace",
            "baseName": "usableSpace",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ModelFile.attributeTypeMap;
    }

    public constructor() {
    }
}

