/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class MultiUserInviteDto {
    'invitedUsers'?: Array<number>;
    'invitedUsersIdentifier'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "invitedUsers",
            "baseName": "invitedUsers",
            "type": "Array<number>",
            "format": "int64"
        },
        {
            "name": "invitedUsersIdentifier",
            "baseName": "invitedUsersIdentifier",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MultiUserInviteDto.attributeTypeMap;
    }

    public constructor() {
    }
}

