/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProviderMetaDataDto } from '../models/ProviderMetaDataDto';
import { SpecialtyDto } from '../models/SpecialtyDto';
import { TitleDto } from '../models/TitleDto';


export class NewUserInviteDto {
    'accountPhoneNumber'?: string;
    'bubbleColor'?: string;
    'comments'?: string;
    'credentials'?: string;
    'department'?: string;
    'email': string;
    'externalIdentifier'?: string;
    'faxNumber'?: string;
    'firstName': string;
    'homePhoneNumber'?: string;
    'initials'?: string;
    'invitedUserId'?: number;
    'invitedUserIdentifier'?: string;
    'invitingUserId'?: number;
    'invitingUserIdentifier'?: string;
    'lastName': string;
    'notes'?: string;
    'organizationId'?: number;
    'organizationIdentifier'?: string;
    'phoneNumber'?: string;
    'providerMetaData'?: Array<ProviderMetaDataDto>;
    'referralCode'?: string;
    'specialities'?: Array<SpecialtyDto>;
    'specialties'?: Array<SpecialtyDto>;
    'titles'?: Array<TitleDto>;
    'userName'?: string;
    'userRole'?: NewUserInviteDtoUserRoleEnum;
    'workPhoneNumber'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accountPhoneNumber",
            "baseName": "accountPhoneNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "bubbleColor",
            "baseName": "bubbleColor",
            "type": "string",
            "format": ""
        },
        {
            "name": "comments",
            "baseName": "comments",
            "type": "string",
            "format": ""
        },
        {
            "name": "credentials",
            "baseName": "credentials",
            "type": "string",
            "format": ""
        },
        {
            "name": "department",
            "baseName": "department",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalIdentifier",
            "baseName": "externalIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "faxNumber",
            "baseName": "faxNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "homePhoneNumber",
            "baseName": "homePhoneNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "initials",
            "baseName": "initials",
            "type": "string",
            "format": ""
        },
        {
            "name": "invitedUserId",
            "baseName": "invitedUserId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "invitedUserIdentifier",
            "baseName": "invitedUserIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "invitingUserId",
            "baseName": "invitingUserId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "invitingUserIdentifier",
            "baseName": "invitingUserIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationId",
            "baseName": "organizationId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "organizationIdentifier",
            "baseName": "organizationIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "providerMetaData",
            "baseName": "providerMetaData",
            "type": "Array<ProviderMetaDataDto>",
            "format": ""
        },
        {
            "name": "referralCode",
            "baseName": "referralCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "specialities",
            "baseName": "specialities",
            "type": "Array<SpecialtyDto>",
            "format": ""
        },
        {
            "name": "specialties",
            "baseName": "specialties",
            "type": "Array<SpecialtyDto>",
            "format": ""
        },
        {
            "name": "titles",
            "baseName": "titles",
            "type": "Array<TitleDto>",
            "format": ""
        },
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string",
            "format": ""
        },
        {
            "name": "userRole",
            "baseName": "userRole",
            "type": "NewUserInviteDtoUserRoleEnum",
            "format": ""
        },
        {
            "name": "workPhoneNumber",
            "baseName": "workPhoneNumber",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NewUserInviteDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum NewUserInviteDtoUserRoleEnum {
    Owner = 'OWNER',
    Admin = 'ADMIN',
    Member = 'MEMBER',
    Guest = 'GUEST',
    DockPro = 'DOCK_PRO',
    DockLite = 'DOCK_LITE',
    Collaborator = 'COLLABORATOR',
    ViewOnly = 'VIEW_ONLY'
}

