/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class OIDCTokensPayload {
    'accessToken'?: string;
    'expiresIn'?: number;
    'idToken'?: string;
    'organizationIdentifier'?: string;
    'patientIdentifier'?: string;
    'profile'?: string;
    'refreshToken'?: string;
    'taskIdentifier'?: string;
    'taskListIdentifier'?: string;
    'tokenType'?: string;
    'userIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accessToken",
            "baseName": "access_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiresIn",
            "baseName": "expires_in",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "idToken",
            "baseName": "id_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationIdentifier",
            "baseName": "organizationIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "patientIdentifier",
            "baseName": "patientIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "profile",
            "baseName": "profile",
            "type": "string",
            "format": ""
        },
        {
            "name": "refreshToken",
            "baseName": "refresh_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskIdentifier",
            "baseName": "taskIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskListIdentifier",
            "baseName": "taskListIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "tokenType",
            "baseName": "token_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "userIdentifier",
            "baseName": "userIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OIDCTokensPayload.attributeTypeMap;
    }

    public constructor() {
    }
}

