/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class OptInRegistrationDto {
    'initialConsentReceived'?: boolean;
    'optInMethod'?: OptInRegistrationDtoOptInMethodEnum;
    'otherIn'?: string;
    'patientIdentifier'?: string;
    'smsPhone'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "initialConsentReceived",
            "baseName": "initialConsentReceived",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "optInMethod",
            "baseName": "optInMethod",
            "type": "OptInRegistrationDtoOptInMethodEnum",
            "format": ""
        },
        {
            "name": "otherIn",
            "baseName": "otherIn",
            "type": "string",
            "format": ""
        },
        {
            "name": "patientIdentifier",
            "baseName": "patientIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "smsPhone",
            "baseName": "smsPhone",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OptInRegistrationDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum OptInRegistrationDtoOptInMethodEnum {
    Web = 'WEB',
    UserSms = 'USER_SMS',
    Paper = 'PAPER',
    Ehr = 'EHR',
    OtherIn = 'OTHER_IN'
}

