/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class OptInDto {
    'identifier'?: string;
    'initialConsentReceived'?: boolean;
    'optInDate'?: Date;
    'optInMethod'?: OptInDtoOptInMethodEnum;
    'optOutDate'?: Date;
    'optOutMethod'?: OptInDtoOptOutMethodEnum;
    'otherIn'?: string;
    'otherOut'?: string;
    'patientIdentifier'?: string;
    'smsPermitted'?: boolean;
    'smsPhone'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "initialConsentReceived",
            "baseName": "initialConsentReceived",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "optInDate",
            "baseName": "optInDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "optInMethod",
            "baseName": "optInMethod",
            "type": "OptInDtoOptInMethodEnum",
            "format": ""
        },
        {
            "name": "optOutDate",
            "baseName": "optOutDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "optOutMethod",
            "baseName": "optOutMethod",
            "type": "OptInDtoOptOutMethodEnum",
            "format": ""
        },
        {
            "name": "otherIn",
            "baseName": "otherIn",
            "type": "string",
            "format": ""
        },
        {
            "name": "otherOut",
            "baseName": "otherOut",
            "type": "string",
            "format": ""
        },
        {
            "name": "patientIdentifier",
            "baseName": "patientIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "smsPermitted",
            "baseName": "smsPermitted",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "smsPhone",
            "baseName": "smsPhone",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OptInDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum OptInDtoOptInMethodEnum {
    Web = 'WEB',
    UserSms = 'USER_SMS',
    Paper = 'PAPER',
    Ehr = 'EHR',
    OtherIn = 'OTHER_IN'
}
export enum OptInDtoOptOutMethodEnum {
    Twilio = 'TWILIO',
    Provider = 'PROVIDER',
    OtherOut = 'OTHER_OUT'
}

