/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class OptOutDto {
    'optOutMethod'?: OptOutDtoOptOutMethodEnum;
    'otherOut'?: string;
    'smsPhone'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "optOutMethod",
            "baseName": "optOutMethod",
            "type": "OptOutDtoOptOutMethodEnum",
            "format": ""
        },
        {
            "name": "otherOut",
            "baseName": "otherOut",
            "type": "string",
            "format": ""
        },
        {
            "name": "smsPhone",
            "baseName": "smsPhone",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OptOutDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum OptOutDtoOptOutMethodEnum {
    Twilio = 'TWILIO',
    Provider = 'PROVIDER',
    OtherOut = 'OTHER_OUT'
}

