/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class OrganizationSummaryDto {
    'organizationIdentifier'?: string;
    'organizationInitials'?: string;
    'organizationName'?: string;
    'organizationProfileColor'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "organizationIdentifier",
            "baseName": "organizationIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationInitials",
            "baseName": "organizationInitials",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationName",
            "baseName": "organizationName",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationProfileColor",
            "baseName": "organizationProfileColor",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrganizationSummaryDto.attributeTypeMap;
    }

    public constructor() {
    }
}

