/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrgThemeSettingsDto } from '../models/OrgThemeSettingsDto';
import { SubscriptionDto } from '../models/SubscriptionDto';


export class OrganizationDto {
    'availableFeatures'?: any;
    'baaSignatureDateTime'?: Date;
    'baaSignatureRequestSent'?: boolean;
    'baaSigned'?: boolean;
    'customerType'?: OrganizationDtoCustomerTypeEnum;
    'disabledFeatures'?: any;
    'dockChatDisabled'?: boolean;
    'emrIntegrationEnabled'?: boolean;
    'emrIntegrationType'?: string;
    'emrPatientLink'?: string;
    'organizationId'?: number;
    'organizationIdentifier': string;
    'organizationInitials'?: string;
    'organizationLegalEntityName'?: string;
    'organizationName'?: string;
    'organizationProfileColor'?: string;
    'referralCode'?: string;
    'showDefaultTaskStatusCompleted'?: boolean;
    'subscriptionDetails'?: SubscriptionDto;
    'themeSettings'?: Array<OrgThemeSettingsDto>;
    'updatedByUser'?: boolean;
    'whiteLabelEnabled'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "availableFeatures",
            "baseName": "availableFeatures",
            "type": "any",
            "format": ""
        },
        {
            "name": "baaSignatureDateTime",
            "baseName": "baaSignatureDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "baaSignatureRequestSent",
            "baseName": "baaSignatureRequestSent",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "baaSigned",
            "baseName": "baaSigned",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "customerType",
            "baseName": "customerType",
            "type": "OrganizationDtoCustomerTypeEnum",
            "format": ""
        },
        {
            "name": "disabledFeatures",
            "baseName": "disabledFeatures",
            "type": "any",
            "format": ""
        },
        {
            "name": "dockChatDisabled",
            "baseName": "dockChatDisabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "emrIntegrationEnabled",
            "baseName": "emrIntegrationEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "emrIntegrationType",
            "baseName": "emrIntegrationType",
            "type": "string",
            "format": ""
        },
        {
            "name": "emrPatientLink",
            "baseName": "emrPatientLink",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationId",
            "baseName": "organizationId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "organizationIdentifier",
            "baseName": "organizationIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationInitials",
            "baseName": "organizationInitials",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationLegalEntityName",
            "baseName": "organizationLegalEntityName",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationName",
            "baseName": "organizationName",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationProfileColor",
            "baseName": "organizationProfileColor",
            "type": "string",
            "format": ""
        },
        {
            "name": "referralCode",
            "baseName": "referralCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "showDefaultTaskStatusCompleted",
            "baseName": "showDefaultTaskStatusCompleted",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "subscriptionDetails",
            "baseName": "subscriptionDetails",
            "type": "SubscriptionDto",
            "format": ""
        },
        {
            "name": "themeSettings",
            "baseName": "themeSettings",
            "type": "Array<OrgThemeSettingsDto>",
            "format": ""
        },
        {
            "name": "updatedByUser",
            "baseName": "updatedByUser",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "whiteLabelEnabled",
            "baseName": "whiteLabelEnabled",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrganizationDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum OrganizationDtoCustomerTypeEnum {
    Patient = 'PATIENT',
    Client = 'CLIENT',
    Member = 'MEMBER',
    Customer = 'CUSTOMER'
}

