/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class OrganizationManageDto {
    'active'?: boolean;
    'customerType'?: OrganizationManageDtoCustomerTypeEnum;
    'domain'?: string;
    'externalIdentifier'?: string;
    'organizationIdentifier'?: string;
    'organizationInitials'?: string;
    'organizationLegalEntityName'?: string;
    'organizationName'?: string;
    'organizationProfileColor'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "customerType",
            "baseName": "customerType",
            "type": "OrganizationManageDtoCustomerTypeEnum",
            "format": ""
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalIdentifier",
            "baseName": "externalIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationIdentifier",
            "baseName": "organizationIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationInitials",
            "baseName": "organizationInitials",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationLegalEntityName",
            "baseName": "organizationLegalEntityName",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationName",
            "baseName": "organizationName",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationProfileColor",
            "baseName": "organizationProfileColor",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrganizationManageDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum OrganizationManageDtoCustomerTypeEnum {
    Patient = 'PATIENT',
    Client = 'CLIENT',
    Member = 'MEMBER',
    Customer = 'CUSTOMER'
}

