/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class OrgSettingsDto {
    'dockChatDisabled'?: boolean;
    'whiteLabelEnabled'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dockChatDisabled",
            "baseName": "dockChatDisabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "whiteLabelEnabled",
            "baseName": "whiteLabelEnabled",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrgSettingsDto.attributeTypeMap;
    }

    public constructor() {
    }
}

