/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PatientFilterOptionsDto } from '../models/PatientFilterOptionsDto';
import { PatientSummaryDto } from '../models/PatientSummaryDto';


export class PatientLookupDto {
    'patientFilterOptions'?: PatientFilterOptionsDto;
    'patients'?: Array<PatientSummaryDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "patientFilterOptions",
            "baseName": "patientFilterOptions",
            "type": "PatientFilterOptionsDto",
            "format": ""
        },
        {
            "name": "patients",
            "baseName": "patients",
            "type": "Array<PatientSummaryDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PatientLookupDto.attributeTypeMap;
    }

    public constructor() {
    }
}

