/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class PatientMetaDataDto {
    'contextType'?: PatientMetaDataDtoContextTypeEnum;
    'customFieldIdentifier'?: string;
    'customFieldName'?: string;
    'displayName'?: string;
    'displayNames'?: Array<string>;
    'displayOptions'?: any;
    'fieldType'?: PatientMetaDataDtoFieldTypeEnum;
    'sortIndex'?: number;
    'value'?: string;
    'values'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "contextType",
            "baseName": "contextType",
            "type": "PatientMetaDataDtoContextTypeEnum",
            "format": ""
        },
        {
            "name": "customFieldIdentifier",
            "baseName": "customFieldIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "customFieldName",
            "baseName": "customFieldName",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayNames",
            "baseName": "displayNames",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "displayOptions",
            "baseName": "displayOptions",
            "type": "any",
            "format": ""
        },
        {
            "name": "fieldType",
            "baseName": "fieldType",
            "type": "PatientMetaDataDtoFieldTypeEnum",
            "format": ""
        },
        {
            "name": "sortIndex",
            "baseName": "sortIndex",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PatientMetaDataDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PatientMetaDataDtoContextTypeEnum {
    Predefined = 'PREDEFINED',
    Custom = 'CUSTOM'
}
export enum PatientMetaDataDtoFieldTypeEnum {
    Text = 'TEXT',
    LongText = 'LONG_TEXT',
    Number = 'NUMBER',
    Date = 'DATE',
    DateTime = 'DATE_TIME',
    PickList = 'PICK_LIST',
    Boolean = 'BOOLEAN',
    MultiSelect = 'MULTI_SELECT',
    Hyperlink = 'HYPERLINK',
    Relationship = 'RELATIONSHIP'
}

