/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserSummaryDto } from '../models/UserSummaryDto';


export class PatientAttachmentDto {
    'attachmentId'?: number;
    'attachmentIdentifier'?: string;
    'contentType'?: string;
    'creator'?: UserSummaryDto;
    'dateCreated'?: Date;
    'dateUpdated'?: Date;
    'fileIdentifier'?: string;
    'fileName'?: string;
    'fileSize'?: number;
    'fileUrl'?: string;
    'parentAttachment'?: PatientAttachmentDto;
    'parentAttachmentIdentifier'?: string;
    'patientIdentifier'?: string;
    'scanStatus'?: PatientAttachmentDtoScanStatusEnum;
    'type'?: PatientAttachmentDtoTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attachmentId",
            "baseName": "attachmentId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "attachmentIdentifier",
            "baseName": "attachmentIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "contentType",
            "baseName": "contentType",
            "type": "string",
            "format": ""
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "UserSummaryDto",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "dateCreated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateUpdated",
            "baseName": "dateUpdated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "fileIdentifier",
            "baseName": "fileIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileName",
            "baseName": "fileName",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileSize",
            "baseName": "fileSize",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "fileUrl",
            "baseName": "fileUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentAttachment",
            "baseName": "parentAttachment",
            "type": "PatientAttachmentDto",
            "format": ""
        },
        {
            "name": "parentAttachmentIdentifier",
            "baseName": "parentAttachmentIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "patientIdentifier",
            "baseName": "patientIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "scanStatus",
            "baseName": "scanStatus",
            "type": "PatientAttachmentDtoScanStatusEnum",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PatientAttachmentDtoTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PatientAttachmentDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PatientAttachmentDtoScanStatusEnum {
    InProgress = 'IN_PROGRESS',
    Clean = 'CLEAN',
    Infected = 'INFECTED',
    Error = 'ERROR'
}
export enum PatientAttachmentDtoTypeEnum {
    FileLocal = 'FILE_LOCAL',
    FileGdrive = 'FILE_GDRIVE',
    FileOnedrive = 'FILE_ONEDRIVE',
    Folder = 'FOLDER'
}

