/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class PatientImportProcessTrackingUpdateDto {
    'completed'?: boolean;
    'errorDetails'?: string;
    'inError'?: boolean;
    'recordsToProcess'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "completed",
            "baseName": "completed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "errorDetails",
            "baseName": "errorDetails",
            "type": "string",
            "format": ""
        },
        {
            "name": "inError",
            "baseName": "inError",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "recordsToProcess",
            "baseName": "recordsToProcess",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return PatientImportProcessTrackingUpdateDto.attributeTypeMap;
    }

    public constructor() {
    }
}

