/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PatientFilterCustomFieldDto } from '../models/PatientFilterCustomFieldDto';
import { PatientFilterOptionDto } from '../models/PatientFilterOptionDto';


export class PatientFilterOptionsDto {
    'customFields'?: Array<PatientFilterCustomFieldDto>;
    'labels'?: Array<PatientFilterOptionDto>;
    'optionsOrder'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "customFields",
            "baseName": "customFields",
            "type": "Array<PatientFilterCustomFieldDto>",
            "format": ""
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "Array<PatientFilterOptionDto>",
            "format": ""
        },
        {
            "name": "optionsOrder",
            "baseName": "optionsOrder",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PatientFilterOptionsDto.attributeTypeMap;
    }

    public constructor() {
    }
}

