/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PatientImportProcessTrackingDetailsDto } from '../models/PatientImportProcessTrackingDetailsDto';
import { UserSummaryDto } from '../models/UserSummaryDto';


export class PatientImportProcessTrackingDto {
    'completePercentage'?: number;
    'completed'?: boolean;
    'createdDateTime'?: Date;
    'creator'?: UserSummaryDto;
    'endDateTime'?: Date;
    'errorDetails'?: string;
    'fileName'?: string;
    'identifier'?: string;
    'inError'?: boolean;
    'recordsProcessed'?: number;
    'recordsToProcess'?: number;
    'startDateTime'?: Date;
    'trackingDetails'?: Array<PatientImportProcessTrackingDetailsDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "completePercentage",
            "baseName": "completePercentage",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "completed",
            "baseName": "completed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdDateTime",
            "baseName": "createdDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "UserSummaryDto",
            "format": ""
        },
        {
            "name": "endDateTime",
            "baseName": "endDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "errorDetails",
            "baseName": "errorDetails",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileName",
            "baseName": "fileName",
            "type": "string",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "inError",
            "baseName": "inError",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "recordsProcessed",
            "baseName": "recordsProcessed",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "recordsToProcess",
            "baseName": "recordsToProcess",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "startDateTime",
            "baseName": "startDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "trackingDetails",
            "baseName": "trackingDetails",
            "type": "Array<PatientImportProcessTrackingDetailsDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PatientImportProcessTrackingDto.attributeTypeMap;
    }

    public constructor() {
    }
}

