/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PatientFilterSelectedCustomFieldDto } from '../models/PatientFilterSelectedCustomFieldDto';


export class PatientFilterSelectedOptionsDto {
    'customFields'?: Array<PatientFilterSelectedCustomFieldDto>;
    'labels'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "customFields",
            "baseName": "customFields",
            "type": "Array<PatientFilterSelectedCustomFieldDto>",
            "format": ""
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PatientFilterSelectedOptionsDto.attributeTypeMap;
    }

    public constructor() {
    }
}

