/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class PatientInsuranceDto {
    'externalIdentifier'?: string;
    'idNumber'?: string;
    'planName'?: string;
    'preferenceIndex'?: number;
    'type'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "externalIdentifier",
            "baseName": "externalIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "idNumber",
            "baseName": "idNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "planName",
            "baseName": "planName",
            "type": "string",
            "format": ""
        },
        {
            "name": "preferenceIndex",
            "baseName": "preferenceIndex",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PatientInsuranceDto.attributeTypeMap;
    }

    public constructor() {
    }
}

