/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PatientSummaryDto } from '../models/PatientSummaryDto';
import { UserSummaryDto } from '../models/UserSummaryDto';


export class PatientListDto {
    'active'?: boolean;
    'creator'?: UserSummaryDto;
    'externalIdentifier'?: string;
    'listDescription'?: string;
    'listDisplayColumnPrefs'?: any;
    'listDisplayColumns'?: any;
    'listName'?: string;
    'listType'?: PatientListDtoListTypeEnum;
    'patientIdentifiers'?: Array<string>;
    'patientListIdentifier'?: string;
    'patients'?: Array<PatientSummaryDto>;
    'patientsCount'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "UserSummaryDto",
            "format": ""
        },
        {
            "name": "externalIdentifier",
            "baseName": "externalIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "listDescription",
            "baseName": "listDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "listDisplayColumnPrefs",
            "baseName": "listDisplayColumnPrefs",
            "type": "any",
            "format": ""
        },
        {
            "name": "listDisplayColumns",
            "baseName": "listDisplayColumns",
            "type": "any",
            "format": ""
        },
        {
            "name": "listName",
            "baseName": "listName",
            "type": "string",
            "format": ""
        },
        {
            "name": "listType",
            "baseName": "listType",
            "type": "PatientListDtoListTypeEnum",
            "format": ""
        },
        {
            "name": "patientIdentifiers",
            "baseName": "patientIdentifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "patientListIdentifier",
            "baseName": "patientListIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "patients",
            "baseName": "patients",
            "type": "Array<PatientSummaryDto>",
            "format": ""
        },
        {
            "name": "patientsCount",
            "baseName": "patientsCount",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return PatientListDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PatientListDtoListTypeEnum {
    Default = 'DEFAULT',
    Adhoc = 'ADHOC',
    Criteria = 'CRITERIA'
}

