/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserSummaryDto } from '../models/UserSummaryDto';


export class PatientDto {
    'active'?: boolean;
    'age'?: string;
    'allNotes'?: any;
    'createdDateTime'?: Date;
    'creator'?: UserSummaryDto;
    'dob'?: Date;
    'email'?: string;
    'externalIdentifier'?: string;
    'externalIdentifiers'?: any;
    'fhirIdentifier'?: string;
    'firstName'?: string;
    'fromEMR'?: boolean;
    'gender'?: string;
    'genderIdentity'?: PatientDtoGenderIdentityEnum;
    'insurances'?: any;
    'lastName'?: string;
    'middleName'?: string;
    'mrn'?: string;
    'notes'?: string;
    'patientId'?: number;
    'patientIdentifier'?: string;
    'patientLabels'?: any;
    'patientMetaData'?: any;
    'patientName'?: string;
    'patientStatus'?: string;
    'phoneHome'?: string;
    'phoneMobile'?: string;
    'reference'?: string;
    'status'?: string;
    'updatedDateTime'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "age",
            "baseName": "age",
            "type": "string",
            "format": ""
        },
        {
            "name": "allNotes",
            "baseName": "allNotes",
            "type": "any",
            "format": ""
        },
        {
            "name": "createdDateTime",
            "baseName": "createdDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "UserSummaryDto",
            "format": ""
        },
        {
            "name": "dob",
            "baseName": "dob",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalIdentifier",
            "baseName": "externalIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalIdentifiers",
            "baseName": "externalIdentifiers",
            "type": "any",
            "format": ""
        },
        {
            "name": "fhirIdentifier",
            "baseName": "fhirIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "fromEMR",
            "baseName": "fromEMR",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "string",
            "format": ""
        },
        {
            "name": "genderIdentity",
            "baseName": "genderIdentity",
            "type": "PatientDtoGenderIdentityEnum",
            "format": ""
        },
        {
            "name": "insurances",
            "baseName": "insurances",
            "type": "any",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "middleName",
            "baseName": "middleName",
            "type": "string",
            "format": ""
        },
        {
            "name": "mrn",
            "baseName": "mrn",
            "type": "string",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "patientId",
            "baseName": "patientId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "patientIdentifier",
            "baseName": "patientIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "patientLabels",
            "baseName": "patientLabels",
            "type": "any",
            "format": ""
        },
        {
            "name": "patientMetaData",
            "baseName": "patientMetaData",
            "type": "any",
            "format": ""
        },
        {
            "name": "patientName",
            "baseName": "patientName",
            "type": "string",
            "format": ""
        },
        {
            "name": "patientStatus",
            "baseName": "patientStatus",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneHome",
            "baseName": "phoneHome",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneMobile",
            "baseName": "phoneMobile",
            "type": "string",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedDateTime",
            "baseName": "updatedDateTime",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return PatientDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PatientDtoGenderIdentityEnum {
    Male = 'MALE',
    Female = 'FEMALE',
    TransMan = 'TRANS_MAN',
    TransWoman = 'TRANS_WOMAN',
    NonConforming = 'NON_CONFORMING',
    Decline = 'DECLINE'
}

