/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class PatientBulkOperationRequestDto {
    'bulkOperationType'?: PatientBulkOperationRequestDtoBulkOperationTypeEnum;
    'labelIdentifier'?: string;
    'labelName'?: string;
    'patientIdentifiers'?: Array<string>;
    'taskDescription'?: string;
    'taskGroupIdentifier'?: string;
    'taskListIdentifier'?: string;
    'workflowIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bulkOperationType",
            "baseName": "bulkOperationType",
            "type": "PatientBulkOperationRequestDtoBulkOperationTypeEnum",
            "format": ""
        },
        {
            "name": "labelIdentifier",
            "baseName": "labelIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "labelName",
            "baseName": "labelName",
            "type": "string",
            "format": ""
        },
        {
            "name": "patientIdentifiers",
            "baseName": "patientIdentifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "taskDescription",
            "baseName": "taskDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskGroupIdentifier",
            "baseName": "taskGroupIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskListIdentifier",
            "baseName": "taskListIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "workflowIdentifier",
            "baseName": "workflowIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PatientBulkOperationRequestDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PatientBulkOperationRequestDtoBulkOperationTypeEnum {
    CreateTask = 'CREATE_TASK',
    CreateWorkflow = 'CREATE_WORKFLOW',
    AddLabel = 'ADD_LABEL',
    DeleteLabel = 'DELETE_LABEL',
    DeletePatient = 'DELETE_PATIENT',
    RestorePatient = 'RESTORE_PATIENT',
    ArchivePatient = 'ARCHIVE_PATIENT',
    UnarchivePatient = 'UNARCHIVE_PATIENT'
}

