/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PatientImportAttributeDto } from '../models/PatientImportAttributeDto';


export class PatientImportDto {
    'additionalAttributes'?: Array<PatientImportAttributeDto>;
    'dob'?: string;
    'email'?: string;
    'errorDetails'?: string;
    'firstName'?: string;
    'gender'?: string;
    'lastName'?: string;
    'middleName'?: string;
    'mrn'?: string;
    'notes'?: string;
    'phoneHome'?: string;
    'phoneMobile'?: string;
    'reference'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "additionalAttributes",
            "baseName": "additionalAttributes",
            "type": "Array<PatientImportAttributeDto>",
            "format": ""
        },
        {
            "name": "dob",
            "baseName": "dob",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "errorDetails",
            "baseName": "errorDetails",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "middleName",
            "baseName": "middleName",
            "type": "string",
            "format": ""
        },
        {
            "name": "mrn",
            "baseName": "mrn",
            "type": "string",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneHome",
            "baseName": "phoneHome",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneMobile",
            "baseName": "phoneMobile",
            "type": "string",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PatientImportDto.attributeTypeMap;
    }

    public constructor() {
    }
}

