/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class PatientFilterSelectedCustomFieldDto {
    'customFieldIdentifier'?: string;
    'dateEnd'?: Date;
    'dateOption'?: string;
    'dateStart'?: Date;
    'selectedOptionIdentifiers'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "customFieldIdentifier",
            "baseName": "customFieldIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateEnd",
            "baseName": "dateEnd",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateOption",
            "baseName": "dateOption",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateStart",
            "baseName": "dateStart",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "selectedOptionIdentifiers",
            "baseName": "selectedOptionIdentifiers",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PatientFilterSelectedCustomFieldDto.attributeTypeMap;
    }

    public constructor() {
    }
}

