/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class PatientSummaryDto {
    'active'?: boolean;
    'age'?: string;
    'dob'?: string;
    'email'?: string;
    'firstName'?: string;
    'fromEMR'?: boolean;
    'gender'?: string;
    'genderIdentity'?: PatientSummaryDtoGenderIdentityEnum;
    'lastName'?: string;
    'middleName'?: string;
    'mrn'?: string;
    'patientId'?: number;
    'patientIdentifier'?: string;
    'patientLabels'?: any;
    'patientMetaData'?: any;
    'patientName'?: string;
    'patientStatus'?: string;
    'phoneHome'?: string;
    'phoneMobile'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "age",
            "baseName": "age",
            "type": "string",
            "format": ""
        },
        {
            "name": "dob",
            "baseName": "dob",
            "type": "string",
            "format": "date"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "fromEMR",
            "baseName": "fromEMR",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "string",
            "format": ""
        },
        {
            "name": "genderIdentity",
            "baseName": "genderIdentity",
            "type": "PatientSummaryDtoGenderIdentityEnum",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "middleName",
            "baseName": "middleName",
            "type": "string",
            "format": ""
        },
        {
            "name": "mrn",
            "baseName": "mrn",
            "type": "string",
            "format": ""
        },
        {
            "name": "patientId",
            "baseName": "patientId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "patientIdentifier",
            "baseName": "patientIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "patientLabels",
            "baseName": "patientLabels",
            "type": "any",
            "format": ""
        },
        {
            "name": "patientMetaData",
            "baseName": "patientMetaData",
            "type": "any",
            "format": ""
        },
        {
            "name": "patientName",
            "baseName": "patientName",
            "type": "string",
            "format": ""
        },
        {
            "name": "patientStatus",
            "baseName": "patientStatus",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneHome",
            "baseName": "phoneHome",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneMobile",
            "baseName": "phoneMobile",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PatientSummaryDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PatientSummaryDtoGenderIdentityEnum {
    Male = 'MALE',
    Female = 'FEMALE',
    TransMan = 'TRANS_MAN',
    TransWoman = 'TRANS_WOMAN',
    NonConforming = 'NON_CONFORMING',
    Decline = 'DECLINE'
}

