/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class PatientImportProcessTrackingDetailsDto {
    'errorDetails'?: string;
    'patientIdentifier'?: string;
    'patientName'?: string;
    'reference'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "errorDetails",
            "baseName": "errorDetails",
            "type": "string",
            "format": ""
        },
        {
            "name": "patientIdentifier",
            "baseName": "patientIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "patientName",
            "baseName": "patientName",
            "type": "string",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PatientImportProcessTrackingDetailsDto.attributeTypeMap;
    }

    public constructor() {
    }
}

