/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserSummaryDto } from '../models/UserSummaryDto';


export class PatientNoteDto {
    'creator'?: UserSummaryDto;
    'dateCreated'?: Date;
    'dateUpdated'?: Date;
    'description'?: string;
    'lastEditor'?: UserSummaryDto;
    'patientNoteId'?: number;
    'patientNoteIdentifier'?: string;
    'pinned'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "creator",
            "baseName": "creator",
            "type": "UserSummaryDto",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "dateCreated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateUpdated",
            "baseName": "dateUpdated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastEditor",
            "baseName": "lastEditor",
            "type": "UserSummaryDto",
            "format": ""
        },
        {
            "name": "patientNoteId",
            "baseName": "patientNoteId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "patientNoteIdentifier",
            "baseName": "patientNoteIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "pinned",
            "baseName": "pinned",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PatientNoteDto.attributeTypeMap;
    }

    public constructor() {
    }
}

