/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Timestamp } from '../models/Timestamp';
import { UserSummaryDto } from '../models/UserSummaryDto';


export class ProfileNoteDto {
    'createdBy'?: string;
    'createdDateTime'?: Timestamp;
    'creator'?: UserSummaryDto;
    'description'?: string;
    'externalIdentifier'?: string;
    'identifier'?: string;
    'updatedBy'?: string;
    'updatedDateTime'?: Timestamp;
    'updater'?: UserSummaryDto;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdDateTime",
            "baseName": "createdDateTime",
            "type": "Timestamp",
            "format": ""
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "UserSummaryDto",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalIdentifier",
            "baseName": "externalIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedBy",
            "baseName": "updatedBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedDateTime",
            "baseName": "updatedDateTime",
            "type": "Timestamp",
            "format": ""
        },
        {
            "name": "updater",
            "baseName": "updater",
            "type": "UserSummaryDto",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProfileNoteDto.attributeTypeMap;
    }

    public constructor() {
    }
}

