/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomFieldOptionDto } from '../models/CustomFieldOptionDto';
import { ProfileTypeDto } from '../models/ProfileTypeDto';
import { Timestamp } from '../models/Timestamp';


export class ProfileTypeCustomFieldDto {
    'active'?: boolean;
    'contextType'?: ProfileTypeCustomFieldDtoContextTypeEnum;
    'createdBy'?: string;
    'createdDateTime'?: Timestamp;
    'displayOptions'?: any;
    'externalIdentifier'?: string;
    'fieldCategoryType'?: ProfileTypeCustomFieldDtoFieldCategoryTypeEnum;
    'fieldType'?: ProfileTypeCustomFieldDtoFieldTypeEnum;
    'identifier'?: string;
    'name'?: string;
    'options'?: Array<CustomFieldOptionDto>;
    'placeholder'?: string;
    'profileType'?: ProfileTypeDto;
    'relatedProfileType'?: ProfileTypeDto;
    'required'?: boolean;
    'sortIndex'?: number;
    'targetType'?: ProfileTypeCustomFieldDtoTargetTypeEnum;
    'taskListIdentifier'?: string;
    'updatedBy'?: string;
    'updatedDateTime'?: Timestamp;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "contextType",
            "baseName": "contextType",
            "type": "ProfileTypeCustomFieldDtoContextTypeEnum",
            "format": ""
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdDateTime",
            "baseName": "createdDateTime",
            "type": "Timestamp",
            "format": ""
        },
        {
            "name": "displayOptions",
            "baseName": "displayOptions",
            "type": "any",
            "format": ""
        },
        {
            "name": "externalIdentifier",
            "baseName": "externalIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "fieldCategoryType",
            "baseName": "fieldCategoryType",
            "type": "ProfileTypeCustomFieldDtoFieldCategoryTypeEnum",
            "format": ""
        },
        {
            "name": "fieldType",
            "baseName": "fieldType",
            "type": "ProfileTypeCustomFieldDtoFieldTypeEnum",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Array<CustomFieldOptionDto>",
            "format": ""
        },
        {
            "name": "placeholder",
            "baseName": "placeholder",
            "type": "string",
            "format": ""
        },
        {
            "name": "profileType",
            "baseName": "profileType",
            "type": "ProfileTypeDto",
            "format": ""
        },
        {
            "name": "relatedProfileType",
            "baseName": "relatedProfileType",
            "type": "ProfileTypeDto",
            "format": ""
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sortIndex",
            "baseName": "sortIndex",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "targetType",
            "baseName": "targetType",
            "type": "ProfileTypeCustomFieldDtoTargetTypeEnum",
            "format": ""
        },
        {
            "name": "taskListIdentifier",
            "baseName": "taskListIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedBy",
            "baseName": "updatedBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedDateTime",
            "baseName": "updatedDateTime",
            "type": "Timestamp",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProfileTypeCustomFieldDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ProfileTypeCustomFieldDtoContextTypeEnum {
    Predefined = 'PREDEFINED',
    Custom = 'CUSTOM'
}
export enum ProfileTypeCustomFieldDtoFieldCategoryTypeEnum {
    PatientPersonal = 'PATIENT_PERSONAL',
    PatientContact = 'PATIENT_CONTACT',
    PatientOther = 'PATIENT_OTHER',
    TaskOther = 'TASK_OTHER',
    TaskCore = 'TASK_CORE',
    ProviderOther = 'PROVIDER_OTHER',
    Profile = 'PROFILE'
}
export enum ProfileTypeCustomFieldDtoFieldTypeEnum {
    Text = 'TEXT',
    LongText = 'LONG_TEXT',
    Number = 'NUMBER',
    Date = 'DATE',
    DateTime = 'DATE_TIME',
    PickList = 'PICK_LIST',
    Boolean = 'BOOLEAN',
    MultiSelect = 'MULTI_SELECT',
    Hyperlink = 'HYPERLINK',
    Relationship = 'RELATIONSHIP'
}
export enum ProfileTypeCustomFieldDtoTargetTypeEnum {
    Task = 'TASK',
    Patient = 'PATIENT',
    Provider = 'PROVIDER',
    Profile = 'PROFILE'
}

