/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProfileFieldDto } from '../models/ProfileFieldDto';
import { ProfileTypeDto } from '../models/ProfileTypeDto';
import { Timestamp } from '../models/Timestamp';


export class ProfileDto {
    'createdBy'?: string;
    'createdDateTime'?: Timestamp;
    'externalIdentifier'?: string;
    'fields'?: Array<ProfileFieldDto>;
    'identifier'?: string;
    'profileType'?: ProfileTypeDto;
    'updatedBy'?: string;
    'updatedDateTime'?: Timestamp;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdDateTime",
            "baseName": "createdDateTime",
            "type": "Timestamp",
            "format": ""
        },
        {
            "name": "externalIdentifier",
            "baseName": "externalIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<ProfileFieldDto>",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "profileType",
            "baseName": "profileType",
            "type": "ProfileTypeDto",
            "format": ""
        },
        {
            "name": "updatedBy",
            "baseName": "updatedBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedDateTime",
            "baseName": "updatedDateTime",
            "type": "Timestamp",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProfileDto.attributeTypeMap;
    }

    public constructor() {
    }
}

