/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProfileFieldValueDto } from '../models/ProfileFieldValueDto';
import { ProfileTypeCustomFieldDto } from '../models/ProfileTypeCustomFieldDto';
import { Timestamp } from '../models/Timestamp';


export class ProfileFieldDto {
    'createdBy'?: string;
    'createdDateTime'?: Timestamp;
    'externalIdentifier'?: string;
    'identifier'?: string;
    'profileTypeField'?: ProfileTypeCustomFieldDto;
    'updatedBy'?: string;
    'updatedDateTime'?: Timestamp;
    'values'?: Array<ProfileFieldValueDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdDateTime",
            "baseName": "createdDateTime",
            "type": "Timestamp",
            "format": ""
        },
        {
            "name": "externalIdentifier",
            "baseName": "externalIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "profileTypeField",
            "baseName": "profileTypeField",
            "type": "ProfileTypeCustomFieldDto",
            "format": ""
        },
        {
            "name": "updatedBy",
            "baseName": "updatedBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedDateTime",
            "baseName": "updatedDateTime",
            "type": "Timestamp",
            "format": ""
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<ProfileFieldValueDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProfileFieldDto.attributeTypeMap;
    }

    public constructor() {
    }
}

