/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class ProfileFieldSimpleDto {
    'externalIdentifier'?: string;
    'identifier'?: string;
    'profileTypeFieldIdentifier'?: string;
    'profileTypeFieldName'?: string;
    'profileTypeFieldType'?: string;
    'value'?: string;
    'values'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "externalIdentifier",
            "baseName": "externalIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "profileTypeFieldIdentifier",
            "baseName": "profileTypeFieldIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "profileTypeFieldName",
            "baseName": "profileTypeFieldName",
            "type": "string",
            "format": ""
        },
        {
            "name": "profileTypeFieldType",
            "baseName": "profileTypeFieldType",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProfileFieldSimpleDto.attributeTypeMap;
    }

    public constructor() {
    }
}

