/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomFieldOptionDto } from '../models/CustomFieldOptionDto';
import { ProfileFieldDto } from '../models/ProfileFieldDto';
import { Timestamp } from '../models/Timestamp';


export class ProfileFieldValueDto {
    'createdBy'?: string;
    'createdDateTime'?: Timestamp;
    'customFieldOption'?: CustomFieldOptionDto;
    'externalIdentifier'?: string;
    'identifier'?: string;
    'profileField'?: ProfileFieldDto;
    'updatedBy'?: string;
    'updatedDateTime'?: Timestamp;
    'value'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdDateTime",
            "baseName": "createdDateTime",
            "type": "Timestamp",
            "format": ""
        },
        {
            "name": "customFieldOption",
            "baseName": "customFieldOption",
            "type": "CustomFieldOptionDto",
            "format": ""
        },
        {
            "name": "externalIdentifier",
            "baseName": "externalIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "profileField",
            "baseName": "profileField",
            "type": "ProfileFieldDto",
            "format": ""
        },
        {
            "name": "updatedBy",
            "baseName": "updatedBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedDateTime",
            "baseName": "updatedDateTime",
            "type": "Timestamp",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProfileFieldValueDto.attributeTypeMap;
    }

    public constructor() {
    }
}

