/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProfileFieldSimpleDto } from '../models/ProfileFieldSimpleDto';


export class ProfileSimpleDto {
    'externalIdentifier'?: string;
    'fields'?: Array<ProfileFieldSimpleDto>;
    'identifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "externalIdentifier",
            "baseName": "externalIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<ProfileFieldSimpleDto>",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProfileSimpleDto.attributeTypeMap;
    }

    public constructor() {
    }
}

