/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Protocol } from '../models/Protocol';
import { Timestamp } from '../models/Timestamp';


export class ProtocolItem {
    'createdBy'?: string;
    'createdDateTime'?: Timestamp;
    'description'?: string;
    'protocol'?: Protocol;
    'protocolItemId'?: number;
    'sortingIndex'?: number;
    'updatedBy'?: string;
    'updatedDateTime'?: Timestamp;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdDateTime",
            "baseName": "createdDateTime",
            "type": "Timestamp",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "protocol",
            "baseName": "protocol",
            "type": "Protocol",
            "format": ""
        },
        {
            "name": "protocolItemId",
            "baseName": "protocolItemId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "sortingIndex",
            "baseName": "sortingIndex",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "updatedBy",
            "baseName": "updatedBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedDateTime",
            "baseName": "updatedDateTime",
            "type": "Timestamp",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProtocolItem.attributeTypeMap;
    }

    public constructor() {
    }
}

