/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TaskFilterSelectedOptionsDto } from '../models/TaskFilterSelectedOptionsDto';


export class QuickFilterDto {
    'contextType'?: QuickFilterDtoContextTypeEnum;
    'name'?: string;
    'organizationIdentifier'?: string;
    'patientIdentifier'?: string;
    'personIdentifier'?: string;
    'quickFilterIdentifier'?: string;
    'selectedOptions'?: TaskFilterSelectedOptionsDto;
    'taskListIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "contextType",
            "baseName": "contextType",
            "type": "QuickFilterDtoContextTypeEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationIdentifier",
            "baseName": "organizationIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "patientIdentifier",
            "baseName": "patientIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "personIdentifier",
            "baseName": "personIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "quickFilterIdentifier",
            "baseName": "quickFilterIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "selectedOptions",
            "baseName": "selectedOptions",
            "type": "TaskFilterSelectedOptionsDto",
            "format": ""
        },
        {
            "name": "taskListIdentifier",
            "baseName": "taskListIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QuickFilterDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum QuickFilterDtoContextTypeEnum {
    MyTasks = 'MY_TASKS',
    AllTasks = 'ALL_TASKS',
    Analytics = 'ANALYTICS'
}

