/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class ReferralConfigurationDto {
    'hasDiscountCode'?: boolean;
    'messageBannerBar'?: string;
    'messageCreateAccount'?: string;
    'messageLogin'?: string;
    'referralCode'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hasDiscountCode",
            "baseName": "hasDiscountCode",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "messageBannerBar",
            "baseName": "messageBannerBar",
            "type": "string",
            "format": ""
        },
        {
            "name": "messageCreateAccount",
            "baseName": "messageCreateAccount",
            "type": "string",
            "format": ""
        },
        {
            "name": "messageLogin",
            "baseName": "messageLogin",
            "type": "string",
            "format": ""
        },
        {
            "name": "referralCode",
            "baseName": "referralCode",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReferralConfigurationDto.attributeTypeMap;
    }

    public constructor() {
    }
}

