/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubSpecialtyDto } from '../models/SubSpecialtyDto';


export class SpecialtyDto {
    'name'?: string;
    'specialtyId'?: number;
    'subSpecialties'?: Array<SubSpecialtyDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "specialtyId",
            "baseName": "specialtyId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "subSpecialties",
            "baseName": "subSpecialties",
            "type": "Array<SubSpecialtyDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SpecialtyDto.attributeTypeMap;
    }

    public constructor() {
    }
}

