/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
* SSO Auth Details
*/
export class SSOAuth {
    'issuer'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "issuer",
            "baseName": "issuer",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SSOAuth.attributeTypeMap;
    }

    public constructor() {
    }
}

