/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class SubscriptionDto {
    'billingFrequency'?: SubscriptionDtoBillingFrequencyEnum;
    'professionalServicesIncluded'?: boolean;
    'subscriptionPlan'?: SubscriptionDtoSubscriptionPlanEnum;
    'subscriptionPlanName'?: string;
    'trialEndDate'?: Date;
    'trialEnded'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "billingFrequency",
            "baseName": "billingFrequency",
            "type": "SubscriptionDtoBillingFrequencyEnum",
            "format": ""
        },
        {
            "name": "professionalServicesIncluded",
            "baseName": "professionalServicesIncluded",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "subscriptionPlan",
            "baseName": "subscriptionPlan",
            "type": "SubscriptionDtoSubscriptionPlanEnum",
            "format": ""
        },
        {
            "name": "subscriptionPlanName",
            "baseName": "subscriptionPlanName",
            "type": "string",
            "format": ""
        },
        {
            "name": "trialEndDate",
            "baseName": "trialEndDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "trialEnded",
            "baseName": "trialEnded",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum SubscriptionDtoBillingFrequencyEnum {
    Monthly = 'MONTHLY',
    Annual = 'ANNUAL'
}
export enum SubscriptionDtoSubscriptionPlanEnum {
    _15DayTrial = 'PLAN_15_DAY_TRIAL',
    _30DayTrial = 'PLAN_30_DAY_TRIAL',
    _60DayTrial = 'PLAN_60_DAY_TRIAL',
    _90DayTrial = 'PLAN_90_DAY_TRIAL',
    _120DayTrial = 'PLAN_120_DAY_TRIAL',
    _180DayTrial = 'PLAN_180_DAY_TRIAL',
    Standard = 'PLAN_STANDARD',
    Premium = 'PLAN_PREMIUM',
    Pro = 'PLAN_PRO',
    Enterprise = 'PLAN_ENTERPRISE',
    Free = 'PLAN_FREE',
    DockLite = 'PLAN_DOCK_LITE'
}

