/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class SubSpecialtyDto {
    'subSpecialtyId'?: number;
    'subSpecialtyName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "subSpecialtyId",
            "baseName": "subSpecialtyId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "subSpecialtyName",
            "baseName": "subSpecialtyName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SubSpecialtyDto.attributeTypeMap;
    }

    public constructor() {
    }
}

