/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ContactDto } from '../models/ContactDto';


export class TaskSharingDto {
    'assignTask'?: boolean;
    'externalCollaborators'?: Array<ContactDto>;
    'taskIdentifier'?: string;
    'userIdentifiers'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assignTask",
            "baseName": "assignTask",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "externalCollaborators",
            "baseName": "externalCollaborators",
            "type": "Array<ContactDto>",
            "format": ""
        },
        {
            "name": "taskIdentifier",
            "baseName": "taskIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "userIdentifiers",
            "baseName": "userIdentifiers",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskSharingDto.attributeTypeMap;
    }

    public constructor() {
    }
}

