/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class TaskSortDto {
    'parentTaskIdentifier'?: string;
    'taskGroupIdentifier'?: string;
    'taskGroupImplicitType'?: TaskSortDtoTaskGroupImplicitTypeEnum;
    'taskIdentifiers'?: Array<string>;
    'taskTemplateIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "parentTaskIdentifier",
            "baseName": "parentTaskIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskGroupIdentifier",
            "baseName": "taskGroupIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskGroupImplicitType",
            "baseName": "taskGroupImplicitType",
            "type": "TaskSortDtoTaskGroupImplicitTypeEnum",
            "format": ""
        },
        {
            "name": "taskIdentifiers",
            "baseName": "taskIdentifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "taskTemplateIdentifier",
            "baseName": "taskTemplateIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskSortDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TaskSortDtoTaskGroupImplicitTypeEnum {
    Overdue = 'OVERDUE',
    Today = 'TODAY',
    Tomorrow = 'TOMORROW',
    Next7Days = 'NEXT_7_DAYS',
    NoDueDate = 'NO_DUE_DATE',
    AllOther = 'ALL_OTHER',
    AssignedByMe = 'ASSIGNED_BY_ME',
    CompletedToday = 'COMPLETED_TODAY',
    Completed7Days = 'COMPLETED_7_DAYS',
    OrgOverdue = 'ORG_OVERDUE',
    OrgToday = 'ORG_TODAY',
    OrgTomorrow = 'ORG_TOMORROW',
    OrgNext7Days = 'ORG_NEXT_7_DAYS',
    OrgNoDueDate = 'ORG_NO_DUE_DATE',
    OrgAllOther = 'ORG_ALL_OTHER',
    OrgCompletedToday = 'ORG_COMPLETED_TODAY',
    OrgCompleted7Days = 'ORG_COMPLETED_7_DAYS',
    Escalated = 'ESCALATED',
    Shared = 'SHARED',
    SharedCompletedToday = 'SHARED_COMPLETED_TODAY',
    SharedCompleted7Days = 'SHARED_COMPLETED_7_DAYS'
}

