/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class TaskSummaryForEMRDto {
    'details'?: string;
    'noteType'?: TaskSummaryForEMRDtoNoteTypeEnum;
    'taskIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "details",
            "baseName": "details",
            "type": "string",
            "format": ""
        },
        {
            "name": "noteType",
            "baseName": "noteType",
            "type": "TaskSummaryForEMRDtoNoteTypeEnum",
            "format": ""
        },
        {
            "name": "taskIdentifier",
            "baseName": "taskIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskSummaryForEMRDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TaskSummaryForEMRDtoNoteTypeEnum {
    CommunicationNote = 'COMMUNICATION_NOTE',
    ReferralNote = 'REFERRAL_NOTE',
    ConsultNote = 'CONSULT_NOTE',
    ProcedureNote = 'PROCEDURE_NOTE',
    ProgressNote = 'PROGRESS_NOTE',
    LabNote = 'LAB_NOTE'
}

