/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class TaskLinkSummaryDto {
    'decisionOutcome'?: string;
    'delayIsBusinessDays'?: boolean;
    'delayPeriod'?: number;
    'delayPeriodUnit'?: TaskLinkSummaryDtoDelayPeriodUnitEnum;
    'isDependent'?: boolean;
    'sourceTaskIdentifier'?: string;
    'targetTaskIdentifier'?: string;
    'timeReference'?: TaskLinkSummaryDtoTimeReferenceEnum;
    'timeRelative'?: TaskLinkSummaryDtoTimeRelativeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "decisionOutcome",
            "baseName": "decisionOutcome",
            "type": "string",
            "format": ""
        },
        {
            "name": "delayIsBusinessDays",
            "baseName": "delayIsBusinessDays",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "delayPeriod",
            "baseName": "delayPeriod",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "delayPeriodUnit",
            "baseName": "delayPeriodUnit",
            "type": "TaskLinkSummaryDtoDelayPeriodUnitEnum",
            "format": ""
        },
        {
            "name": "isDependent",
            "baseName": "isDependent",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sourceTaskIdentifier",
            "baseName": "sourceTaskIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetTaskIdentifier",
            "baseName": "targetTaskIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeReference",
            "baseName": "timeReference",
            "type": "TaskLinkSummaryDtoTimeReferenceEnum",
            "format": ""
        },
        {
            "name": "timeRelative",
            "baseName": "timeRelative",
            "type": "TaskLinkSummaryDtoTimeRelativeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskLinkSummaryDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TaskLinkSummaryDtoDelayPeriodUnitEnum {
    Hour = 'HOUR',
    Day = 'DAY',
    Week = 'WEEK',
    Month = 'MONTH',
    Year = 'YEAR'
}
export enum TaskLinkSummaryDtoTimeReferenceEnum {
    PrevTaskDueDateTime = 'PREV_TASK_DUE_DATE_TIME',
    PrevTaskCompletionDateTime = 'PREV_TASK_COMPLETION_DATE_TIME',
    NextTaskDueDateTime = 'NEXT_TASK_DUE_DATE_TIME',
    WorkflowAnchorDate = 'WORKFLOW_ANCHOR_DATE',
    WorkflowDeployDate = 'WORKFLOW_DEPLOY_DATE',
    WorkflowDueDate = 'WORKFLOW_DUE_DATE'
}
export enum TaskLinkSummaryDtoTimeRelativeEnum {
    Before = 'BEFORE',
    After = 'AFTER'
}

