/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TaskDto } from '../models/TaskDto';


export class TaskUpdateServiceResponse {
    'errorCode'?: string;
    'errorMessage'?: string;
    'statusCode'?: TaskUpdateServiceResponseStatusCodeEnum;
    'statusMessage'?: string;
    'task'?: TaskDto;
    'uuid'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "errorCode",
            "baseName": "errorCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "errorMessage",
            "baseName": "errorMessage",
            "type": "string",
            "format": ""
        },
        {
            "name": "statusCode",
            "baseName": "statusCode",
            "type": "TaskUpdateServiceResponseStatusCodeEnum",
            "format": ""
        },
        {
            "name": "statusMessage",
            "baseName": "statusMessage",
            "type": "string",
            "format": ""
        },
        {
            "name": "task",
            "baseName": "task",
            "type": "TaskDto",
            "format": ""
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskUpdateServiceResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TaskUpdateServiceResponseStatusCodeEnum {
    Success = 'SUCCESS',
    Warning = 'WARNING',
    Failure = 'FAILURE'
}

