/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DateGroupedMetricDto } from '../models/DateGroupedMetricDto';
import { TaskListStatsDto } from '../models/TaskListStatsDto';


export class TaskListStatsSummaryDto {
    'newTasksByDate'?: Array<DateGroupedMetricDto>;
    'newTasksByMeByDate'?: Array<DateGroupedMetricDto>;
    'stats'?: Array<TaskListStatsDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "newTasksByDate",
            "baseName": "newTasksByDate",
            "type": "Array<DateGroupedMetricDto>",
            "format": ""
        },
        {
            "name": "newTasksByMeByDate",
            "baseName": "newTasksByMeByDate",
            "type": "Array<DateGroupedMetricDto>",
            "format": ""
        },
        {
            "name": "stats",
            "baseName": "stats",
            "type": "Array<TaskListStatsDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskListStatsSummaryDto.attributeTypeMap;
    }

    public constructor() {
    }
}

