/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class TaskLabelDto {
    'labelIdentifier'?: string;
    'labelName'?: string;
    'taskIdentifier'?: string;
    'taskWorkflowIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "labelIdentifier",
            "baseName": "labelIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "labelName",
            "baseName": "labelName",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskIdentifier",
            "baseName": "taskIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskWorkflowIdentifier",
            "baseName": "taskWorkflowIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskLabelDto.attributeTypeMap;
    }

    public constructor() {
    }
}

