/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserItemDto } from '../models/UserItemDto';


export class Task Template Member {
    'memberPermission'?: Task Template MemberMemberPermissionEnum;
    'user'?: UserItemDto;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "memberPermission",
            "baseName": "memberPermission",
            "type": "Task Template MemberMemberPermissionEnum",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "UserItemDto",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Task Template Member.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum Task Template MemberMemberPermissionEnum {
    View = 'VIEW',
    Editor = 'EDITOR'
}

