/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrganizationSummaryDto } from '../models/OrganizationSummaryDto';
import { PatientSummaryDto } from '../models/PatientSummaryDto';
import { TaskGroupDto } from '../models/TaskGroupDto';
import { TaskListSummaryDto } from '../models/TaskListSummaryDto';
import { TaskTemplateDto } from '../models/TaskTemplateDto';
import { TaskWorkflowStatusDto } from '../models/TaskWorkflowStatusDto';
import { UserItemDto } from '../models/UserItemDto';
import { UserSummaryDto } from '../models/UserSummaryDto';


export class TaskDto {
    'active'?: boolean;
    'addedToListByUser'?: UserSummaryDto;
    'archivedByUser'?: boolean;
    'assignedToUsers'?: Array<UserItemDto>;
    'assignmentUpdatedDateTime'?: Date;
    'attachments'?: any;
    'comments'?: any;
    'completedBy'?: UserSummaryDto;
    'completedDt'?: Date;
    'createdDateTime'?: Date;
    'creator'?: UserSummaryDto;
    'dependencyTasksCompletedCount'?: number;
    'dependencyTasksCount'?: number;
    'description'?: string;
    'details'?: string;
    'dueDate'?: Date;
    'duplicated'?: boolean;
    'edited'?: boolean;
    'externalIdentifier'?: string;
    'hasEscalations'?: boolean;
    'hasMentions'?: boolean;
    'hasRecurringSchedule'?: boolean;
    'identifier'?: string;
    'intentType'?: TaskDtoIntentTypeEnum;
    'itemType'?: TaskDtoItemTypeEnum;
    'labels'?: any;
    'linkedTaskTemplate'?: TaskTemplateDto;
    'linkedWorkflowTaskGroup'?: TaskGroupDto;
    'linkedWorkflowTaskList'?: TaskListSummaryDto;
    'organization'?: OrganizationSummaryDto;
    'parentTask'?: TaskDto;
    'parentTaskId'?: number;
    'parentTaskIdentifier'?: string;
    'patient'?: PatientSummaryDto;
    'priority'?: TaskDtoPriorityEnum;
    'read'?: boolean;
    'reminderDt'?: Date;
    'reminderTime'?: string;
    'reminderType'?: TaskDtoReminderTypeEnum;
    'sharedWithUsers'?: Array<UserItemDto>;
    'sourceMessage'?: string;
    'startDate'?: Date;
    'status'?: TaskDtoStatusEnum;
    'subTaskSortIndex'?: number;
    'subTasksCompletedCount'?: number;
    'subTasksCount'?: number;
    'subtasks'?: any;
    'taskBundleGroup'?: TaskGroupDto;
    'taskDependencies'?: any;
    'taskGroups'?: any;
    'taskId'?: number;
    'taskIdentifier'?: string;
    'taskLinks'?: any;
    'taskList'?: TaskListSummaryDto;
    'taskMentions'?: any;
    'taskMetaData'?: any;
    'taskOutcomes'?: any;
    'taskTemplate'?: TaskTemplateDto;
    'taskTemplateIdentifier'?: string;
    'tokenizedDescription'?: string;
    'tokenizedDetails'?: string;
    'type'?: TaskDtoTypeEnum;
    'updated'?: boolean;
    'updatedAttachment'?: boolean;
    'updatedComment'?: boolean;
    'updatedDateTime'?: Date;
    'updatedDueDate'?: boolean;
    'updatedLabel'?: boolean;
    'workflowStatus'?: TaskWorkflowStatusDto;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "addedToListByUser",
            "baseName": "addedToListByUser",
            "type": "UserSummaryDto",
            "format": ""
        },
        {
            "name": "archivedByUser",
            "baseName": "archivedByUser",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "assignedToUsers",
            "baseName": "assignedToUsers",
            "type": "Array<UserItemDto>",
            "format": ""
        },
        {
            "name": "assignmentUpdatedDateTime",
            "baseName": "assignmentUpdatedDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "attachments",
            "baseName": "attachments",
            "type": "any",
            "format": ""
        },
        {
            "name": "comments",
            "baseName": "comments",
            "type": "any",
            "format": ""
        },
        {
            "name": "completedBy",
            "baseName": "completedBy",
            "type": "UserSummaryDto",
            "format": ""
        },
        {
            "name": "completedDt",
            "baseName": "completedDt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdDateTime",
            "baseName": "createdDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "UserSummaryDto",
            "format": ""
        },
        {
            "name": "dependencyTasksCompletedCount",
            "baseName": "dependencyTasksCompletedCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "dependencyTasksCount",
            "baseName": "dependencyTasksCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "string",
            "format": ""
        },
        {
            "name": "dueDate",
            "baseName": "dueDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "duplicated",
            "baseName": "duplicated",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "edited",
            "baseName": "edited",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "externalIdentifier",
            "baseName": "externalIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasEscalations",
            "baseName": "hasEscalations",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasMentions",
            "baseName": "hasMentions",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasRecurringSchedule",
            "baseName": "hasRecurringSchedule",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "intentType",
            "baseName": "intentType",
            "type": "TaskDtoIntentTypeEnum",
            "format": ""
        },
        {
            "name": "itemType",
            "baseName": "itemType",
            "type": "TaskDtoItemTypeEnum",
            "format": ""
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "any",
            "format": ""
        },
        {
            "name": "linkedTaskTemplate",
            "baseName": "linkedTaskTemplate",
            "type": "TaskTemplateDto",
            "format": ""
        },
        {
            "name": "linkedWorkflowTaskGroup",
            "baseName": "linkedWorkflowTaskGroup",
            "type": "TaskGroupDto",
            "format": ""
        },
        {
            "name": "linkedWorkflowTaskList",
            "baseName": "linkedWorkflowTaskList",
            "type": "TaskListSummaryDto",
            "format": ""
        },
        {
            "name": "organization",
            "baseName": "organization",
            "type": "OrganizationSummaryDto",
            "format": ""
        },
        {
            "name": "parentTask",
            "baseName": "parentTask",
            "type": "TaskDto",
            "format": ""
        },
        {
            "name": "parentTaskId",
            "baseName": "parentTaskId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "parentTaskIdentifier",
            "baseName": "parentTaskIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "patient",
            "baseName": "patient",
            "type": "PatientSummaryDto",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "TaskDtoPriorityEnum",
            "format": ""
        },
        {
            "name": "read",
            "baseName": "read",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "reminderDt",
            "baseName": "reminderDt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "reminderTime",
            "baseName": "reminderTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "reminderType",
            "baseName": "reminderType",
            "type": "TaskDtoReminderTypeEnum",
            "format": ""
        },
        {
            "name": "sharedWithUsers",
            "baseName": "sharedWithUsers",
            "type": "Array<UserItemDto>",
            "format": ""
        },
        {
            "name": "sourceMessage",
            "baseName": "sourceMessage",
            "type": "string",
            "format": ""
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TaskDtoStatusEnum",
            "format": ""
        },
        {
            "name": "subTaskSortIndex",
            "baseName": "subTaskSortIndex",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "subTasksCompletedCount",
            "baseName": "subTasksCompletedCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "subTasksCount",
            "baseName": "subTasksCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "subtasks",
            "baseName": "subtasks",
            "type": "any",
            "format": ""
        },
        {
            "name": "taskBundleGroup",
            "baseName": "taskBundleGroup",
            "type": "TaskGroupDto",
            "format": ""
        },
        {
            "name": "taskDependencies",
            "baseName": "taskDependencies",
            "type": "any",
            "format": ""
        },
        {
            "name": "taskGroups",
            "baseName": "taskGroups",
            "type": "any",
            "format": ""
        },
        {
            "name": "taskId",
            "baseName": "taskId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "taskIdentifier",
            "baseName": "taskIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskLinks",
            "baseName": "taskLinks",
            "type": "any",
            "format": ""
        },
        {
            "name": "taskList",
            "baseName": "taskList",
            "type": "TaskListSummaryDto",
            "format": ""
        },
        {
            "name": "taskMentions",
            "baseName": "taskMentions",
            "type": "any",
            "format": ""
        },
        {
            "name": "taskMetaData",
            "baseName": "taskMetaData",
            "type": "any",
            "format": ""
        },
        {
            "name": "taskOutcomes",
            "baseName": "taskOutcomes",
            "type": "any",
            "format": ""
        },
        {
            "name": "taskTemplate",
            "baseName": "taskTemplate",
            "type": "TaskTemplateDto",
            "format": ""
        },
        {
            "name": "taskTemplateIdentifier",
            "baseName": "taskTemplateIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "tokenizedDescription",
            "baseName": "tokenizedDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "tokenizedDetails",
            "baseName": "tokenizedDetails",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TaskDtoTypeEnum",
            "format": ""
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "updatedAttachment",
            "baseName": "updatedAttachment",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "updatedComment",
            "baseName": "updatedComment",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "updatedDateTime",
            "baseName": "updatedDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedDueDate",
            "baseName": "updatedDueDate",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "updatedLabel",
            "baseName": "updatedLabel",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "workflowStatus",
            "baseName": "workflowStatus",
            "type": "TaskWorkflowStatusDto",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TaskDtoIntentTypeEnum {
    Standard = 'STANDARD',
    Decision = 'DECISION',
    WorkflowLink = 'WORKFLOW_LINK',
    WorkflowRepeat = 'WORKFLOW_REPEAT',
    WorkflowStart = 'WORKFLOW_START',
    WorkflowEnd = 'WORKFLOW_END'
}
export enum TaskDtoItemTypeEnum {
    Task = 'TASK',
    Bundle = 'BUNDLE',
    Template = 'TEMPLATE'
}
export enum TaskDtoPriorityEnum {
    High = 'HIGH',
    Medium = 'MEDIUM',
    Low = 'LOW',
    None = 'NONE'
}
export enum TaskDtoReminderTypeEnum {
    None = 'NONE',
    DayOf = 'DAY_OF',
    DayBefore1 = 'DAY_BEFORE_1',
    DayBefore2 = 'DAY_BEFORE_2',
    WeekBefore1 = 'WEEK_BEFORE_1'
}
export enum TaskDtoStatusEnum {
    Complete = 'COMPLETE',
    Incomplete = 'INCOMPLETE'
}
export enum TaskDtoTypeEnum {
    InApp = 'IN_APP',
    Email = 'EMAIL',
    Template = 'TEMPLATE',
    Bundle = 'BUNDLE'
}

