/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TaskItemDto } from '../models/TaskItemDto';


export class TasksUpdateServiceResponse {
    'errorCode'?: string;
    'errorMessage'?: string;
    'statusCode'?: TasksUpdateServiceResponseStatusCodeEnum;
    'statusMessage'?: string;
    'tasks'?: Array<TaskItemDto>;
    'transactionIdentifier'?: string;
    'uuid'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "errorCode",
            "baseName": "errorCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "errorMessage",
            "baseName": "errorMessage",
            "type": "string",
            "format": ""
        },
        {
            "name": "statusCode",
            "baseName": "statusCode",
            "type": "TasksUpdateServiceResponseStatusCodeEnum",
            "format": ""
        },
        {
            "name": "statusMessage",
            "baseName": "statusMessage",
            "type": "string",
            "format": ""
        },
        {
            "name": "tasks",
            "baseName": "tasks",
            "type": "Array<TaskItemDto>",
            "format": ""
        },
        {
            "name": "transactionIdentifier",
            "baseName": "transactionIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TasksUpdateServiceResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TasksUpdateServiceResponseStatusCodeEnum {
    Success = 'SUCCESS',
    Warning = 'WARNING',
    Failure = 'FAILURE'
}

