/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TaskTemplateMember } from '../models/TaskTemplateMember';
import { TaskWorkflowStatusDto } from '../models/TaskWorkflowStatusDto';
import { UserSummaryDto } from '../models/UserSummaryDto';


export class TaskTemplateDto {
    'createdDateTime'?: Date;
    'creator'?: UserSummaryDto;
    'description'?: string;
    'descriptionCleared'?: boolean;
    'identifier'?: string;
    'itemType'?: TaskTemplateDtoItemTypeEnum;
    'members'?: Array<Task Template Member>;
    'name'?: string;
    'parentTaskWorkflowIdentifier'?: string;
    'priority'?: TaskTemplateDtoPriorityEnum;
    'publicAccess'?: boolean;
    'templateType'?: TaskTemplateDtoTemplateTypeEnum;
    'tokenizedDescription'?: string;
    'workflowStatus'?: TaskWorkflowStatusDto;
    'workflowStatusIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdDateTime",
            "baseName": "createdDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "UserSummaryDto",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "descriptionCleared",
            "baseName": "descriptionCleared",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemType",
            "baseName": "itemType",
            "type": "TaskTemplateDtoItemTypeEnum",
            "format": ""
        },
        {
            "name": "members",
            "baseName": "members",
            "type": "Array<Task Template Member>",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentTaskWorkflowIdentifier",
            "baseName": "parentTaskWorkflowIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "TaskTemplateDtoPriorityEnum",
            "format": ""
        },
        {
            "name": "publicAccess",
            "baseName": "publicAccess",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "templateType",
            "baseName": "templateType",
            "type": "TaskTemplateDtoTemplateTypeEnum",
            "format": ""
        },
        {
            "name": "tokenizedDescription",
            "baseName": "tokenizedDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "workflowStatus",
            "baseName": "workflowStatus",
            "type": "TaskWorkflowStatusDto",
            "format": ""
        },
        {
            "name": "workflowStatusIdentifier",
            "baseName": "workflowStatusIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskTemplateDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TaskTemplateDtoItemTypeEnum {
    Task = 'TASK',
    Bundle = 'BUNDLE',
    Template = 'TEMPLATE'
}
export enum TaskTemplateDtoPriorityEnum {
    High = 'HIGH',
    Medium = 'MEDIUM',
    Low = 'LOW',
    None = 'NONE'
}
export enum TaskTemplateDtoTemplateTypeEnum {
    Workflow = 'WORKFLOW',
    Smartflow = 'SMARTFLOW',
    SmartflowSample = 'SMARTFLOW_SAMPLE',
    Folder = 'FOLDER'
}

