/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class TaskCommunicationDto {
    'communicationType'?: TaskCommunicationDtoCommunicationTypeEnum;
    'details'?: string;
    'message'?: string;
    'recipientContact'?: string;
    'recipientContacts'?: Array<string>;
    'recipientName'?: string;
    'taskAttachmentIdentifiers'?: Array<string>;
    'taskIdentifier'?: string;
    'templateIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "communicationType",
            "baseName": "communicationType",
            "type": "TaskCommunicationDtoCommunicationTypeEnum",
            "format": ""
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "recipientContact",
            "baseName": "recipientContact",
            "type": "string",
            "format": ""
        },
        {
            "name": "recipientContacts",
            "baseName": "recipientContacts",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "recipientName",
            "baseName": "recipientName",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskAttachmentIdentifiers",
            "baseName": "taskAttachmentIdentifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "taskIdentifier",
            "baseName": "taskIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "templateIdentifier",
            "baseName": "templateIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskCommunicationDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TaskCommunicationDtoCommunicationTypeEnum {
    Email = 'EMAIL',
    Fax = 'FAX',
    Sms = 'SMS',
    Smstwilio = 'SMSTWILIO',
    SecureMessage = 'SECURE_MESSAGE',
    Esign = 'ESIGN'
}

