/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserSummaryDto } from '../models/UserSummaryDto';


export class TaskOutcomeDto {
    'isSelected'?: boolean;
    'name'?: string;
    'selectedBy'?: UserSummaryDto;
    'selectedDateTime'?: Date;
    'taskOutcomeIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "isSelected",
            "baseName": "isSelected",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "selectedBy",
            "baseName": "selectedBy",
            "type": "UserSummaryDto",
            "format": ""
        },
        {
            "name": "selectedDateTime",
            "baseName": "selectedDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "taskOutcomeIdentifier",
            "baseName": "taskOutcomeIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskOutcomeDto.attributeTypeMap;
    }

    public constructor() {
    }
}

