/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class TaskBulkEditRequestDto {
    'assignedToIdentifiers'?: Array<string>;
    'bulkEditType'?: TaskBulkEditRequestDtoBulkEditTypeEnum;
    'dueDate'?: Date;
    'dueDateOption'?: TaskBulkEditRequestDtoDueDateOptionEnum;
    'includeAttachmentsForDuplication'?: boolean;
    'parentTaskIdentifier'?: string;
    'priority'?: TaskBulkEditRequestDtoPriorityEnum;
    'reminderDt'?: Date;
    'taskGroupIdentifier'?: string;
    'taskIdentifiers'?: Array<string>;
    'taskListIdentifier'?: string;
    'taskWorkflowIdentifiers'?: Array<string>;
    'workflowStatusIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assignedToIdentifiers",
            "baseName": "assignedToIdentifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "bulkEditType",
            "baseName": "bulkEditType",
            "type": "TaskBulkEditRequestDtoBulkEditTypeEnum",
            "format": ""
        },
        {
            "name": "dueDate",
            "baseName": "dueDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dueDateOption",
            "baseName": "dueDateOption",
            "type": "TaskBulkEditRequestDtoDueDateOptionEnum",
            "format": ""
        },
        {
            "name": "includeAttachmentsForDuplication",
            "baseName": "includeAttachmentsForDuplication",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "parentTaskIdentifier",
            "baseName": "parentTaskIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "TaskBulkEditRequestDtoPriorityEnum",
            "format": ""
        },
        {
            "name": "reminderDt",
            "baseName": "reminderDt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "taskGroupIdentifier",
            "baseName": "taskGroupIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskIdentifiers",
            "baseName": "taskIdentifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "taskListIdentifier",
            "baseName": "taskListIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskWorkflowIdentifiers",
            "baseName": "taskWorkflowIdentifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "workflowStatusIdentifier",
            "baseName": "workflowStatusIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskBulkEditRequestDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TaskBulkEditRequestDtoBulkEditTypeEnum {
    Duplicate = 'DUPLICATE',
    Move = 'MOVE',
    Complete = 'COMPLETE',
    Status = 'STATUS',
    DueDate = 'DUE_DATE',
    Assign = 'ASSIGN',
    Delete = 'DELETE'
}
export enum TaskBulkEditRequestDtoDueDateOptionEnum {
    Today = 'TODAY',
    Tomorrow = 'TOMORROW'
}
export enum TaskBulkEditRequestDtoPriorityEnum {
    High = 'HIGH',
    Medium = 'MEDIUM',
    Low = 'LOW',
    None = 'NONE'
}

