/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TaskDto } from '../models/TaskDto';

export class TaskLinkDto {
  'decisionOutcome'?: string;
  'delayIsBusinessDays'?: boolean;
  'delayPeriod'?: number;
  'delayPeriodUnit'?: TaskLinkDtoDelayPeriodUnitEnum;
  'isDependent'?: boolean;
  'sourceTask'?: TaskDto;
  'targetTask'?: TaskDto;
  'timeReference'?: TaskLinkDtoTimeReferenceEnum;
  'timeRelative'?: TaskLinkDtoTimeRelativeEnum;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'decisionOutcome',
      baseName: 'decisionOutcome',
      type: 'string',
      format: '',
    },
    {
      name: 'delayIsBusinessDays',
      baseName: 'delayIsBusinessDays',
      type: 'boolean',
      format: '',
    },
    {
      name: 'delayPeriod',
      baseName: 'delayPeriod',
      type: 'number',
      format: 'int32',
    },
    {
      name: 'delayPeriodUnit',
      baseName: 'delayPeriodUnit',
      type: 'TaskLinkDtoDelayPeriodUnitEnum',
      format: '',
    },
    {
      name: 'isDependent',
      baseName: 'isDependent',
      type: 'boolean',
      format: '',
    },
    {
      name: 'sourceTask',
      baseName: 'sourceTask',
      type: 'TaskDto',
      format: '',
    },
    {
      name: 'targetTask',
      baseName: 'targetTask',
      type: 'TaskDto',
      format: '',
    },
    {
      name: 'timeReference',
      baseName: 'timeReference',
      type: 'TaskLinkDtoTimeReferenceEnum',
      format: '',
    },
    {
      name: 'timeRelative',
      baseName: 'timeRelative',
      type: 'TaskLinkDtoTimeRelativeEnum',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return TaskLinkDto.attributeTypeMap;
  }

  public constructor() {}
}

export enum TaskLinkDtoDelayPeriodUnitEnum {
  Minute = 'MINUTE',
  Hour = 'HOUR',
  Day = 'DAY',
  Week = 'WEEK',
  Month = 'MONTH',
  Year = 'YEAR',
}
export enum TaskLinkDtoTimeReferenceEnum {
  PrevTaskDueDateTime = 'PREV_TASK_DUE_DATE_TIME',
  PrevTaskCompletionDateTime = 'PREV_TASK_COMPLETION_DATE_TIME',
  NextTaskDueDateTime = 'NEXT_TASK_DUE_DATE_TIME',
  WorkflowAnchorDate = 'WORKFLOW_ANCHOR_DATE',
  WorkflowDeployDate = 'WORKFLOW_DEPLOY_DATE',
  WorkflowDueDate = 'WORKFLOW_DUE_DATE',
}
export enum TaskLinkDtoTimeRelativeEnum {
  Before = 'BEFORE',
  After = 'AFTER',
}
