/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PatientSummaryDto } from '../models/PatientSummaryDto';
import { TaskFilterOptionsDto } from '../models/TaskFilterOptionsDto';
import { TaskItemDto } from '../models/TaskItemDto';


export class TaskLookupWithTasksDto {
    'patients'?: Array<PatientSummaryDto>;
    'taskFilterOptions'?: TaskFilterOptionsDto;
    'tasks'?: Array<TaskItemDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "patients",
            "baseName": "patients",
            "type": "Array<PatientSummaryDto>",
            "format": ""
        },
        {
            "name": "taskFilterOptions",
            "baseName": "taskFilterOptions",
            "type": "TaskFilterOptionsDto",
            "format": ""
        },
        {
            "name": "tasks",
            "baseName": "tasks",
            "type": "Array<TaskItemDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskLookupWithTasksDto.attributeTypeMap;
    }

    public constructor() {
    }
}

