/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TaskDto } from '../models/TaskDto';
import { UserItemDto } from '../models/UserItemDto';
import { UserSummaryDto } from '../models/UserSummaryDto';


export class TaskListDto {
    'active'?: boolean;
    'adminIdentifiers'?: Array<string>;
    'adminUsers'?: Array<UserSummaryDto>;
    'admins'?: Array<number>;
    'archived'?: boolean;
    'color'?: string;
    'creator'?: UserSummaryDto;
    'discoveryEnabled'?: boolean;
    'displayOptions'?: any;
    'hasUpdatesForMember'?: boolean;
    'listDescription'?: string;
    'listDisplayColumnPrefs'?: any;
    'listDisplayColumns'?: any;
    'listName': string;
    'listType'?: TaskListDtoListTypeEnum;
    'listUsers'?: Array<UserItemDto>;
    'memberIdentifiers'?: Array<string>;
    'memberUsers'?: Array<UserItemDto>;
    'members'?: Array<number>;
    'notifications'?: boolean;
    'numberOfCompletedTasks'?: number;
    'numberOfHighPriorityTasks'?: number;
    'numberOfTasks'?: number;
    'numberOfUnreadTasks'?: number;
    'restrictCustomization'?: boolean;
    'role'?: TaskListDtoRoleEnum;
    'sharingEnabled'?: boolean;
    'status'?: TaskListDtoStatusEnum;
    'taskListId'?: number;
    'taskListIdentifier'?: string;
    'tasks'?: Array<TaskDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "adminIdentifiers",
            "baseName": "adminIdentifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "adminUsers",
            "baseName": "adminUsers",
            "type": "Array<UserSummaryDto>",
            "format": ""
        },
        {
            "name": "admins",
            "baseName": "admins",
            "type": "Array<number>",
            "format": "int64"
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string",
            "format": ""
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "UserSummaryDto",
            "format": ""
        },
        {
            "name": "discoveryEnabled",
            "baseName": "discoveryEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "displayOptions",
            "baseName": "displayOptions",
            "type": "any",
            "format": ""
        },
        {
            "name": "hasUpdatesForMember",
            "baseName": "hasUpdatesForMember",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "listDescription",
            "baseName": "listDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "listDisplayColumnPrefs",
            "baseName": "listDisplayColumnPrefs",
            "type": "any",
            "format": ""
        },
        {
            "name": "listDisplayColumns",
            "baseName": "listDisplayColumns",
            "type": "any",
            "format": ""
        },
        {
            "name": "listName",
            "baseName": "listName",
            "type": "string",
            "format": ""
        },
        {
            "name": "listType",
            "baseName": "listType",
            "type": "TaskListDtoListTypeEnum",
            "format": ""
        },
        {
            "name": "listUsers",
            "baseName": "listUsers",
            "type": "Array<UserItemDto>",
            "format": ""
        },
        {
            "name": "memberIdentifiers",
            "baseName": "memberIdentifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "memberUsers",
            "baseName": "memberUsers",
            "type": "Array<UserItemDto>",
            "format": ""
        },
        {
            "name": "members",
            "baseName": "members",
            "type": "Array<number>",
            "format": "int64"
        },
        {
            "name": "notifications",
            "baseName": "notifications",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "numberOfCompletedTasks",
            "baseName": "numberOfCompletedTasks",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "numberOfHighPriorityTasks",
            "baseName": "numberOfHighPriorityTasks",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "numberOfTasks",
            "baseName": "numberOfTasks",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "numberOfUnreadTasks",
            "baseName": "numberOfUnreadTasks",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "restrictCustomization",
            "baseName": "restrictCustomization",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "TaskListDtoRoleEnum",
            "format": ""
        },
        {
            "name": "sharingEnabled",
            "baseName": "sharingEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TaskListDtoStatusEnum",
            "format": ""
        },
        {
            "name": "taskListId",
            "baseName": "taskListId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "taskListIdentifier",
            "baseName": "taskListIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "tasks",
            "baseName": "tasks",
            "type": "Array<TaskDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskListDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TaskListDtoListTypeEnum {
    Public = 'PUBLIC',
    Inbox = 'INBOX',
    Private = 'PRIVATE',
    Shared = 'SHARED',
    SharedSample = 'SHARED_SAMPLE',
    Patient = 'PATIENT',
    Template = 'TEMPLATE'
}
export enum TaskListDtoRoleEnum {
    Owner = 'OWNER',
    Admin = 'ADMIN',
    Member = 'MEMBER',
    Guest = 'GUEST',
    DockPro = 'DOCK_PRO',
    DockLite = 'DOCK_LITE',
    Collaborator = 'COLLABORATOR',
    ViewOnly = 'VIEW_ONLY'
}
export enum TaskListDtoStatusEnum {
    Pending = 'PENDING',
    Accepted = 'ACCEPTED',
    Rejected = 'REJECTED',
    Expired = 'EXPIRED',
    Cancelled = 'CANCELLED',
    Inactive = 'INACTIVE'
}

