/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TaskItemDto } from '../models/TaskItemDto';
import { UserItemDto } from '../models/UserItemDto';
import { UserSummaryDto } from '../models/UserSummaryDto';


export class TaskListWithUsersDto {
    'color'?: string;
    'creator'?: UserSummaryDto;
    'discoveryEnabled'?: boolean;
    'displayOptions'?: any;
    'hasMore'?: boolean;
    'listDescription'?: string;
    'listDisplayColumnPrefs'?: any;
    'listDisplayColumns'?: any;
    'listName': string;
    'listType'?: TaskListWithUsersDtoListTypeEnum;
    'listUsers'?: Array<UserItemDto>;
    'notifications'?: boolean;
    'restrictCustomization'?: boolean;
    'role'?: TaskListWithUsersDtoRoleEnum;
    'sharingEnabled'?: boolean;
    'taskListId'?: number;
    'taskListIdentifier'?: string;
    'tasks'?: Array<TaskItemDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "color",
            "baseName": "color",
            "type": "string",
            "format": ""
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "UserSummaryDto",
            "format": ""
        },
        {
            "name": "discoveryEnabled",
            "baseName": "discoveryEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "displayOptions",
            "baseName": "displayOptions",
            "type": "any",
            "format": ""
        },
        {
            "name": "hasMore",
            "baseName": "hasMore",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "listDescription",
            "baseName": "listDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "listDisplayColumnPrefs",
            "baseName": "listDisplayColumnPrefs",
            "type": "any",
            "format": ""
        },
        {
            "name": "listDisplayColumns",
            "baseName": "listDisplayColumns",
            "type": "any",
            "format": ""
        },
        {
            "name": "listName",
            "baseName": "listName",
            "type": "string",
            "format": ""
        },
        {
            "name": "listType",
            "baseName": "listType",
            "type": "TaskListWithUsersDtoListTypeEnum",
            "format": ""
        },
        {
            "name": "listUsers",
            "baseName": "listUsers",
            "type": "Array<UserItemDto>",
            "format": ""
        },
        {
            "name": "notifications",
            "baseName": "notifications",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "restrictCustomization",
            "baseName": "restrictCustomization",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "TaskListWithUsersDtoRoleEnum",
            "format": ""
        },
        {
            "name": "sharingEnabled",
            "baseName": "sharingEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "taskListId",
            "baseName": "taskListId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "taskListIdentifier",
            "baseName": "taskListIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "tasks",
            "baseName": "tasks",
            "type": "Array<TaskItemDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskListWithUsersDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TaskListWithUsersDtoListTypeEnum {
    Public = 'PUBLIC',
    Inbox = 'INBOX',
    Private = 'PRIVATE',
    Shared = 'SHARED',
    SharedSample = 'SHARED_SAMPLE',
    Patient = 'PATIENT',
    Template = 'TEMPLATE'
}
export enum TaskListWithUsersDtoRoleEnum {
    Owner = 'OWNER',
    Admin = 'ADMIN',
    Member = 'MEMBER',
    Guest = 'GUEST',
    DockPro = 'DOCK_PRO',
    DockLite = 'DOCK_LITE',
    Collaborator = 'COLLABORATOR',
    ViewOnly = 'VIEW_ONLY'
}

