/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TaskFilterCustomFieldDto } from '../models/TaskFilterCustomFieldDto';
import { TaskFilterOptionDto } from '../models/TaskFilterOptionDto';


export class TaskFilterOptionsDto {
    'assignedBy'?: Array<TaskFilterOptionDto>;
    'assignedTo'?: Array<TaskFilterOptionDto>;
    'completedBy'?: Array<TaskFilterOptionDto>;
    'createdBy'?: Array<TaskFilterOptionDto>;
    'customFields'?: Array<TaskFilterCustomFieldDto>;
    'labels'?: Array<TaskFilterOptionDto>;
    'optionsOrder'?: Array<string>;
    'organizations'?: Array<TaskFilterOptionDto>;
    'patients'?: Array<TaskFilterOptionDto>;
    'priorityOptions'?: Array<TaskFilterOptionDto>;
    'taskCompletedDateOptions'?: Array<TaskFilterOptionDto>;
    'taskCreatedDateOptions'?: Array<TaskFilterOptionDto>;
    'taskDueDateOptions'?: Array<TaskFilterOptionDto>;
    'taskLists'?: Array<TaskFilterOptionDto>;
    'taskStatusOptions'?: Array<TaskFilterOptionDto>;
    'workflowStatusOptions'?: Array<TaskFilterOptionDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assignedBy",
            "baseName": "assignedBy",
            "type": "Array<TaskFilterOptionDto>",
            "format": ""
        },
        {
            "name": "assignedTo",
            "baseName": "assignedTo",
            "type": "Array<TaskFilterOptionDto>",
            "format": ""
        },
        {
            "name": "completedBy",
            "baseName": "completedBy",
            "type": "Array<TaskFilterOptionDto>",
            "format": ""
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "Array<TaskFilterOptionDto>",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "customFields",
            "type": "Array<TaskFilterCustomFieldDto>",
            "format": ""
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "Array<TaskFilterOptionDto>",
            "format": ""
        },
        {
            "name": "optionsOrder",
            "baseName": "optionsOrder",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "organizations",
            "baseName": "organizations",
            "type": "Array<TaskFilterOptionDto>",
            "format": ""
        },
        {
            "name": "patients",
            "baseName": "patients",
            "type": "Array<TaskFilterOptionDto>",
            "format": ""
        },
        {
            "name": "priorityOptions",
            "baseName": "priorityOptions",
            "type": "Array<TaskFilterOptionDto>",
            "format": ""
        },
        {
            "name": "taskCompletedDateOptions",
            "baseName": "taskCompletedDateOptions",
            "type": "Array<TaskFilterOptionDto>",
            "format": ""
        },
        {
            "name": "taskCreatedDateOptions",
            "baseName": "taskCreatedDateOptions",
            "type": "Array<TaskFilterOptionDto>",
            "format": ""
        },
        {
            "name": "taskDueDateOptions",
            "baseName": "taskDueDateOptions",
            "type": "Array<TaskFilterOptionDto>",
            "format": ""
        },
        {
            "name": "taskLists",
            "baseName": "taskLists",
            "type": "Array<TaskFilterOptionDto>",
            "format": ""
        },
        {
            "name": "taskStatusOptions",
            "baseName": "taskStatusOptions",
            "type": "Array<TaskFilterOptionDto>",
            "format": ""
        },
        {
            "name": "workflowStatusOptions",
            "baseName": "workflowStatusOptions",
            "type": "Array<TaskFilterOptionDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskFilterOptionsDto.attributeTypeMap;
    }

    public constructor() {
    }
}

