/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class TaskMetaDataDto {
    'customFieldIdentifier'?: string;
    'customFieldName'?: string;
    'value'?: string;
    'values'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "customFieldIdentifier",
            "baseName": "customFieldIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "customFieldName",
            "baseName": "customFieldName",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskMetaDataDto.attributeTypeMap;
    }

    public constructor() {
    }
}

