/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class TaskGroupStatsDto {
    'defaultOpen'?: boolean;
    'groupName'?: string;
    'groupType'?: TaskGroupStatsDtoGroupTypeEnum;
    'metricName'?: string;
    'metricValue'?: number;
    'taskGroupIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "defaultOpen",
            "baseName": "defaultOpen",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "groupName",
            "baseName": "groupName",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupType",
            "baseName": "groupType",
            "type": "TaskGroupStatsDtoGroupTypeEnum",
            "format": ""
        },
        {
            "name": "metricName",
            "baseName": "metricName",
            "type": "string",
            "format": ""
        },
        {
            "name": "metricValue",
            "baseName": "metricValue",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "taskGroupIdentifier",
            "baseName": "taskGroupIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskGroupStatsDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TaskGroupStatsDtoGroupTypeEnum {
    Overdue = 'OVERDUE',
    Today = 'TODAY',
    Tomorrow = 'TOMORROW',
    Next7Days = 'NEXT_7_DAYS',
    NoDueDate = 'NO_DUE_DATE',
    AllOther = 'ALL_OTHER',
    AssignedByMe = 'ASSIGNED_BY_ME',
    CompletedToday = 'COMPLETED_TODAY',
    Completed7Days = 'COMPLETED_7_DAYS',
    OrgOverdue = 'ORG_OVERDUE',
    OrgToday = 'ORG_TODAY',
    OrgTomorrow = 'ORG_TOMORROW',
    OrgNext7Days = 'ORG_NEXT_7_DAYS',
    OrgNoDueDate = 'ORG_NO_DUE_DATE',
    OrgAllOther = 'ORG_ALL_OTHER',
    OrgCompletedToday = 'ORG_COMPLETED_TODAY',
    OrgCompleted7Days = 'ORG_COMPLETED_7_DAYS',
    Escalated = 'ESCALATED',
    Shared = 'SHARED',
    SharedCompletedToday = 'SHARED_COMPLETED_TODAY',
    SharedCompleted7Days = 'SHARED_COMPLETED_7_DAYS'
}

