/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class TaskRecurringScheduleDto {
    'endDate'?: Date;
    'endsOption'?: TaskRecurringScheduleDtoEndsOptionEnum;
    'numberOfOccurrences'?: number;
    'recurringDescription'?: string;
    'recurringOnDays'?: Array<TaskRecurringScheduleDtoRecurringOnDaysEnum>;
    'recurringOption'?: TaskRecurringScheduleDtoRecurringOptionEnum;
    'repeatTimeUnit'?: TaskRecurringScheduleDtoRepeatTimeUnitEnum;
    'repeatTimes'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "endsOption",
            "baseName": "endsOption",
            "type": "TaskRecurringScheduleDtoEndsOptionEnum",
            "format": ""
        },
        {
            "name": "numberOfOccurrences",
            "baseName": "numberOfOccurrences",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "recurringDescription",
            "baseName": "recurringDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "recurringOnDays",
            "baseName": "recurringOnDays",
            "type": "Array<TaskRecurringScheduleDtoRecurringOnDaysEnum>",
            "format": ""
        },
        {
            "name": "recurringOption",
            "baseName": "recurringOption",
            "type": "TaskRecurringScheduleDtoRecurringOptionEnum",
            "format": ""
        },
        {
            "name": "repeatTimeUnit",
            "baseName": "repeatTimeUnit",
            "type": "TaskRecurringScheduleDtoRepeatTimeUnitEnum",
            "format": ""
        },
        {
            "name": "repeatTimes",
            "baseName": "repeatTimes",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return TaskRecurringScheduleDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TaskRecurringScheduleDtoEndsOptionEnum {
    Never = 'NEVER',
    OnDate = 'ON_DATE',
    AfterOccurrences = 'AFTER_OCCURRENCES'
}
export enum TaskRecurringScheduleDtoRecurringOnDaysEnum {
    Sunday = 'SUNDAY',
    Monday = 'MONDAY',
    Tuesday = 'TUESDAY',
    Wednesday = 'WEDNESDAY',
    Thursday = 'THURSDAY',
    Friday = 'FRIDAY',
    Saturday = 'SATURDAY'
}
export enum TaskRecurringScheduleDtoRecurringOptionEnum {
    DoNotRepeat = 'DO_NOT_REPEAT',
    WeekdaysMonFri = 'WEEKDAYS_MON_FRI',
    EverydaySunSat = 'EVERYDAY_SUN_SAT',
    Weekly = 'WEEKLY',
    Biweekly = 'BIWEEKLY',
    Monthly = 'MONTHLY',
    Yearly = 'YEARLY',
    Custom = 'CUSTOM'
}
export enum TaskRecurringScheduleDtoRepeatTimeUnitEnum {
    Hour = 'HOUR',
    Day = 'DAY',
    Week = 'WEEK',
    Month = 'MONTH',
    Year = 'YEAR'
}

