/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomFieldDto } from '../models/CustomFieldDto';
import { TaskFilterOptionDto } from '../models/TaskFilterOptionDto';


export class TaskFilterCustomFieldDto {
    'customField'?: CustomFieldDto;
    'options'?: Array<TaskFilterOptionDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "customField",
            "baseName": "customField",
            "type": "CustomFieldDto",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Array<TaskFilterOptionDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskFilterCustomFieldDto.attributeTypeMap;
    }

    public constructor() {
    }
}

