/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class TaskFilterSelectedDateOptionsDto {
    'dateEnd'?: Date;
    'dateOptions'?: Array<string>;
    'dateStart'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dateEnd",
            "baseName": "dateEnd",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateOptions",
            "baseName": "dateOptions",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "dateStart",
            "baseName": "dateStart",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return TaskFilterSelectedDateOptionsDto.attributeTypeMap;
    }

    public constructor() {
    }
}

