/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserSummaryDto } from '../models/UserSummaryDto';


export class TaskAttachmentDto {
    'attachmentId'?: number;
    'attachmentIdentifier'?: string;
    'contentType'?: string;
    'creator'?: UserSummaryDto;
    'dateCreated'?: Date;
    'dateUpdated'?: Date;
    'fileIdentifier'?: string;
    'fileName'?: string;
    'fileSize'?: number;
    'scanStatus'?: TaskAttachmentDtoScanStatusEnum;
    'taskIdentifier'?: string;
    'taskWorkflowIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attachmentId",
            "baseName": "attachmentId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "attachmentIdentifier",
            "baseName": "attachmentIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "contentType",
            "baseName": "contentType",
            "type": "string",
            "format": ""
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "UserSummaryDto",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "dateCreated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateUpdated",
            "baseName": "dateUpdated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "fileIdentifier",
            "baseName": "fileIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileName",
            "baseName": "fileName",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileSize",
            "baseName": "fileSize",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "scanStatus",
            "baseName": "scanStatus",
            "type": "TaskAttachmentDtoScanStatusEnum",
            "format": ""
        },
        {
            "name": "taskIdentifier",
            "baseName": "taskIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskWorkflowIdentifier",
            "baseName": "taskWorkflowIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskAttachmentDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TaskAttachmentDtoScanStatusEnum {
    InProgress = 'IN_PROGRESS',
    Clean = 'CLEAN',
    Infected = 'INFECTED',
    Error = 'ERROR'
}

