/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TaskItemDto } from '../models/TaskItemDto';


export class TaskListSummaryWithTasksDto {
    'color'?: string;
    'discoveryEnabled'?: boolean;
    'hasMore'?: boolean;
    'listDescription'?: string;
    'listName'?: string;
    'listType'?: TaskListSummaryWithTasksDtoListTypeEnum;
    'restrictCustomization'?: boolean;
    'sharingEnabled'?: boolean;
    'taskListId'?: number;
    'taskListIdentifier'?: string;
    'tasks'?: Array<TaskItemDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "color",
            "baseName": "color",
            "type": "string",
            "format": ""
        },
        {
            "name": "discoveryEnabled",
            "baseName": "discoveryEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasMore",
            "baseName": "hasMore",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "listDescription",
            "baseName": "listDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "listName",
            "baseName": "listName",
            "type": "string",
            "format": ""
        },
        {
            "name": "listType",
            "baseName": "listType",
            "type": "TaskListSummaryWithTasksDtoListTypeEnum",
            "format": ""
        },
        {
            "name": "restrictCustomization",
            "baseName": "restrictCustomization",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sharingEnabled",
            "baseName": "sharingEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "taskListId",
            "baseName": "taskListId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "taskListIdentifier",
            "baseName": "taskListIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "tasks",
            "baseName": "tasks",
            "type": "Array<TaskItemDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskListSummaryWithTasksDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TaskListSummaryWithTasksDtoListTypeEnum {
    Public = 'PUBLIC',
    Inbox = 'INBOX',
    Private = 'PRIVATE',
    Shared = 'SHARED',
    SharedSample = 'SHARED_SAMPLE',
    Patient = 'PATIENT',
    Template = 'TEMPLATE'
}

