/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TaskFilterOptionsDto } from '../models/TaskFilterOptionsDto';
import { TaskListWithUsersDto } from '../models/TaskListWithUsersDto';


export class TaskLookupWithTaskListTasksDto {
    'taskFilterOptions'?: TaskFilterOptionsDto;
    'taskLists'?: Array<TaskListWithUsersDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "taskFilterOptions",
            "baseName": "taskFilterOptions",
            "type": "TaskFilterOptionsDto",
            "format": ""
        },
        {
            "name": "taskLists",
            "baseName": "taskLists",
            "type": "Array<TaskListWithUsersDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskLookupWithTaskListTasksDto.attributeTypeMap;
    }

    public constructor() {
    }
}

