/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class TaskManageDto {
    'assignedById'?: number;
    'assignedByIdentifier'?: string;
    'assignedToExternalIdentifier'?: string;
    'assignedToExternalIdentifiers'?: Array<string>;
    'assignedToId'?: number;
    'assignedToIdentifier'?: string;
    'assignedToIdentifiers'?: Array<string>;
    'assignedToIds'?: Array<number>;
    'comment'?: string;
    'description'?: string;
    'details'?: string;
    'detailsCleared'?: boolean;
    'dueDate'?: Date;
    'externalIdentifier'?: string;
    'intentType'?: TaskManageDtoIntentTypeEnum;
    'labelIdentifiers'?: Array<string>;
    'linkedTemplateIdentifier'?: string;
    'linkedWorkflowTaskGroupIdentifier'?: string;
    'linkedWorkflowTaskListIdentifier'?: string;
    'parentTaskId'?: number;
    'parentTaskIdentifier'?: string;
    'patientId'?: number;
    'patientIdentifier'?: string;
    'priority'?: TaskManageDtoPriorityEnum;
    'profileIdentifier'?: string;
    'refiled'?: boolean;
    'reminderDt'?: Date;
    'reminderTime'?: string;
    'reminderType'?: TaskManageDtoReminderTypeEnum;
    'sourceMessage'?: string;
    'sourceMessageIdentifier'?: string;
    'startDate'?: Date;
    'status'?: TaskManageDtoStatusEnum;
    'subTaskSortIndex'?: number;
    'subtasks'?: Array<TaskManageDto>;
    'taskGroupIdentifier'?: string;
    'taskId'?: number;
    'taskIdentifier'?: string;
    'taskListId'?: number;
    'taskListIdentifier'?: string;
    'taskMetaData'?: any;
    'taskTemplateIdentifier'?: string;
    'workflowStatusIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assignedById",
            "baseName": "assignedById",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "assignedByIdentifier",
            "baseName": "assignedByIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "assignedToExternalIdentifier",
            "baseName": "assignedToExternalIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "assignedToExternalIdentifiers",
            "baseName": "assignedToExternalIdentifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "assignedToId",
            "baseName": "assignedToId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "assignedToIdentifier",
            "baseName": "assignedToIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "assignedToIdentifiers",
            "baseName": "assignedToIdentifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "assignedToIds",
            "baseName": "assignedToIds",
            "type": "Array<number>",
            "format": "int64"
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "string",
            "format": ""
        },
        {
            "name": "detailsCleared",
            "baseName": "detailsCleared",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "dueDate",
            "baseName": "dueDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "externalIdentifier",
            "baseName": "externalIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "intentType",
            "baseName": "intentType",
            "type": "TaskManageDtoIntentTypeEnum",
            "format": ""
        },
        {
            "name": "labelIdentifiers",
            "baseName": "labelIdentifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "linkedTemplateIdentifier",
            "baseName": "linkedTemplateIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "linkedWorkflowTaskGroupIdentifier",
            "baseName": "linkedWorkflowTaskGroupIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "linkedWorkflowTaskListIdentifier",
            "baseName": "linkedWorkflowTaskListIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentTaskId",
            "baseName": "parentTaskId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "parentTaskIdentifier",
            "baseName": "parentTaskIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "patientId",
            "baseName": "patientId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "patientIdentifier",
            "baseName": "patientIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "TaskManageDtoPriorityEnum",
            "format": ""
        },
        {
            "name": "profileIdentifier",
            "baseName": "profileIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "refiled",
            "baseName": "refiled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "reminderDt",
            "baseName": "reminderDt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "reminderTime",
            "baseName": "reminderTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "reminderType",
            "baseName": "reminderType",
            "type": "TaskManageDtoReminderTypeEnum",
            "format": ""
        },
        {
            "name": "sourceMessage",
            "baseName": "sourceMessage",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourceMessageIdentifier",
            "baseName": "sourceMessageIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TaskManageDtoStatusEnum",
            "format": ""
        },
        {
            "name": "subTaskSortIndex",
            "baseName": "subTaskSortIndex",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "subtasks",
            "baseName": "subtasks",
            "type": "Array<TaskManageDto>",
            "format": ""
        },
        {
            "name": "taskGroupIdentifier",
            "baseName": "taskGroupIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskId",
            "baseName": "taskId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "taskIdentifier",
            "baseName": "taskIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskListId",
            "baseName": "taskListId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "taskListIdentifier",
            "baseName": "taskListIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskMetaData",
            "baseName": "taskMetaData",
            "type": "any",
            "format": ""
        },
        {
            "name": "taskTemplateIdentifier",
            "baseName": "taskTemplateIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "workflowStatusIdentifier",
            "baseName": "workflowStatusIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskManageDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TaskManageDtoIntentTypeEnum {
    Standard = 'STANDARD',
    Decision = 'DECISION',
    WorkflowLink = 'WORKFLOW_LINK',
    WorkflowRepeat = 'WORKFLOW_REPEAT',
    WorkflowStart = 'WORKFLOW_START',
    WorkflowEnd = 'WORKFLOW_END'
}
export enum TaskManageDtoPriorityEnum {
    High = 'HIGH',
    Medium = 'MEDIUM',
    Low = 'LOW',
    None = 'NONE'
}
export enum TaskManageDtoReminderTypeEnum {
    None = 'NONE',
    DayOf = 'DAY_OF',
    DayBefore1 = 'DAY_BEFORE_1',
    DayBefore2 = 'DAY_BEFORE_2',
    WeekBefore1 = 'WEEK_BEFORE_1'
}
export enum TaskManageDtoStatusEnum {
    Complete = 'COMPLETE',
    Incomplete = 'INCOMPLETE'
}

