/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class TaskTemplateCopyDto {
    'identifier'?: string;
    'itemType'?: TaskTemplateCopyDtoItemTypeEnum;
    'targetOrganizationIdentifiers'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemType",
            "baseName": "itemType",
            "type": "TaskTemplateCopyDtoItemTypeEnum",
            "format": ""
        },
        {
            "name": "targetOrganizationIdentifiers",
            "baseName": "targetOrganizationIdentifiers",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskTemplateCopyDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TaskTemplateCopyDtoItemTypeEnum {
    Task = 'TASK',
    Bundle = 'BUNDLE',
    Template = 'TEMPLATE'
}

