/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class TaskGroupDto {
    'groupDescription'?: string;
    'groupName'?: string;
    'groupType'?: TaskGroupDtoGroupTypeEnum;
    'parentTaskGroupIdentifier'?: string;
    'sortIndexOfTaskInGroup'?: number;
    'taskGroupIdentifier'?: string;
    'taskListIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "groupDescription",
            "baseName": "groupDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupName",
            "baseName": "groupName",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupType",
            "baseName": "groupType",
            "type": "TaskGroupDtoGroupTypeEnum",
            "format": ""
        },
        {
            "name": "parentTaskGroupIdentifier",
            "baseName": "parentTaskGroupIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "sortIndexOfTaskInGroup",
            "baseName": "sortIndexOfTaskInGroup",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "taskGroupIdentifier",
            "baseName": "taskGroupIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskListIdentifier",
            "baseName": "taskListIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskGroupDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TaskGroupDtoGroupTypeEnum {
    Tasklist = 'TASKLIST',
    User = 'USER',
    Patient = 'PATIENT',
    TasklistDefault = 'TASKLIST_DEFAULT',
    UserDefault = 'USER_DEFAULT',
    PatientDefault = 'PATIENT_DEFAULT',
    TaskBundle = 'TASK_BUNDLE'
}

