/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TaskFilterSelectedCustomFieldDto } from '../models/TaskFilterSelectedCustomFieldDto';
import { TaskFilterSelectedDateOptionsDto } from '../models/TaskFilterSelectedDateOptionsDto';


export class TaskFilterSelectedOptionsDto {
    'assignedBy'?: Array<string>;
    'assignedTo'?: Array<string>;
    'completedBy'?: Array<string>;
    'createdBy'?: Array<string>;
    'customFields'?: Array<TaskFilterSelectedCustomFieldDto>;
    'labels'?: Array<string>;
    'organizations'?: Array<string>;
    'patients'?: Array<string>;
    'priorityOptions'?: Array<string>;
    'taskCompletedDateOptions'?: TaskFilterSelectedDateOptionsDto;
    'taskCreatedDateOptions'?: TaskFilterSelectedDateOptionsDto;
    'taskDueDateOptions'?: TaskFilterSelectedDateOptionsDto;
    'taskLists'?: Array<string>;
    'taskStatusOptions'?: Array<string>;
    'workflowStatusOptions'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assignedBy",
            "baseName": "assignedBy",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "assignedTo",
            "baseName": "assignedTo",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "completedBy",
            "baseName": "completedBy",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "customFields",
            "type": "Array<TaskFilterSelectedCustomFieldDto>",
            "format": ""
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "organizations",
            "baseName": "organizations",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "patients",
            "baseName": "patients",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "priorityOptions",
            "baseName": "priorityOptions",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "taskCompletedDateOptions",
            "baseName": "taskCompletedDateOptions",
            "type": "TaskFilterSelectedDateOptionsDto",
            "format": ""
        },
        {
            "name": "taskCreatedDateOptions",
            "baseName": "taskCreatedDateOptions",
            "type": "TaskFilterSelectedDateOptionsDto",
            "format": ""
        },
        {
            "name": "taskDueDateOptions",
            "baseName": "taskDueDateOptions",
            "type": "TaskFilterSelectedDateOptionsDto",
            "format": ""
        },
        {
            "name": "taskLists",
            "baseName": "taskLists",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "taskStatusOptions",
            "baseName": "taskStatusOptions",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "workflowStatusOptions",
            "baseName": "workflowStatusOptions",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskFilterSelectedOptionsDto.attributeTypeMap;
    }

    public constructor() {
    }
}

