/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GroupedTasksDto } from '../models/GroupedTasksDto';
import { TaskFilterOptionsDto } from '../models/TaskFilterOptionsDto';


export class TaskLookupWithGroupedTasksDto {
    'taskFilterOptions'?: TaskFilterOptionsDto;
    'taskGroups'?: Array<GroupedTasksDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "taskFilterOptions",
            "baseName": "taskFilterOptions",
            "type": "TaskFilterOptionsDto",
            "format": ""
        },
        {
            "name": "taskGroups",
            "baseName": "taskGroups",
            "type": "Array<GroupedTasksDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskLookupWithGroupedTasksDto.attributeTypeMap;
    }

    public constructor() {
    }
}

