/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserSummaryDto } from '../models/UserSummaryDto';


export class TaskListStatsDto {
    'currentUser'?: UserSummaryDto;
    'listName'?: string;
    'metricName'?: string;
    'metricValue'?: number;
    'taskListId'?: number;
    'taskListIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "currentUser",
            "baseName": "currentUser",
            "type": "UserSummaryDto",
            "format": ""
        },
        {
            "name": "listName",
            "baseName": "listName",
            "type": "string",
            "format": ""
        },
        {
            "name": "metricName",
            "baseName": "metricName",
            "type": "string",
            "format": ""
        },
        {
            "name": "metricValue",
            "baseName": "metricValue",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "taskListId",
            "baseName": "taskListId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "taskListIdentifier",
            "baseName": "taskListIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskListStatsDto.attributeTypeMap;
    }

    public constructor() {
    }
}

