/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class TemplateDto {
    'details'?: string;
    'identifier'?: string;
    'name'?: string;
    'shortMessage'?: string;
    'type'?: TemplateDtoTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "details",
            "baseName": "details",
            "type": "string",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "shortMessage",
            "baseName": "shortMessage",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TemplateDtoTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TemplateDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TemplateDtoTypeEnum {
    Email = 'EMAIL',
    Sms = 'SMS',
    Fax = 'FAX',
    EmrNote = 'EMR_NOTE',
    SecureMessage = 'SECURE_MESSAGE'
}

