/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class Timestamp {
    'date'?: number;
    'day'?: number;
    'hours'?: number;
    'minutes'?: number;
    'month'?: number;
    'nanos'?: number;
    'seconds'?: number;
    'time'?: number;
    'timezoneOffset'?: number;
    'year'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "day",
            "baseName": "day",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "hours",
            "baseName": "hours",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "minutes",
            "baseName": "minutes",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "month",
            "baseName": "month",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "nanos",
            "baseName": "nanos",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "seconds",
            "baseName": "seconds",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "time",
            "baseName": "time",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "timezoneOffset",
            "baseName": "timezoneOffset",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "year",
            "baseName": "year",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return Timestamp.attributeTypeMap;
    }

    public constructor() {
    }
}

