/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class TitleDto {
    'name'?: string;
    'titleId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "titleId",
            "baseName": "titleId",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return TitleDto.attributeTypeMap;
    }

    public constructor() {
    }
}

