/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
* User\'s Usage Info
*/
export class UsageState {
    'hasExistingLists'?: boolean;
    'hasOnlyInvitedLists'?: boolean;
    'lastLoginDate'?: Date;
    'loginCount'?: number;
    'orgCreator'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hasExistingLists",
            "baseName": "hasExistingLists",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasOnlyInvitedLists",
            "baseName": "hasOnlyInvitedLists",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "lastLoginDate",
            "baseName": "lastLoginDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "loginCount",
            "baseName": "loginCount",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "orgCreator",
            "baseName": "orgCreator",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UsageState.attributeTypeMap;
    }

    public constructor() {
    }
}

