/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UsageEvenMetaDataDto } from '../models/UsageEvenMetaDataDto';


export class UsageEventDto {
    'eventAction'?: string;
    'eventCategory'?: string;
    'eventLabel'?: string;
    'metaData'?: Array<UsageEvenMetaDataDto>;
    'usageEventType'?: UsageEventDtoUsageEventTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "eventAction",
            "baseName": "eventAction",
            "type": "string",
            "format": ""
        },
        {
            "name": "eventCategory",
            "baseName": "eventCategory",
            "type": "string",
            "format": ""
        },
        {
            "name": "eventLabel",
            "baseName": "eventLabel",
            "type": "string",
            "format": ""
        },
        {
            "name": "metaData",
            "baseName": "metaData",
            "type": "Array<UsageEvenMetaDataDto>",
            "format": ""
        },
        {
            "name": "usageEventType",
            "baseName": "usageEventType",
            "type": "UsageEventDtoUsageEventTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UsageEventDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UsageEventDtoUsageEventTypeEnum {
    PageView = 'PAGE_VIEW',
    UsageAction = 'USAGE_ACTION',
    ApiAccess = 'API_ACCESS'
}

