/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserItemDto } from '../models/UserItemDto';


export class UserListDto {
    'bubbleColor'?: string;
    'description'?: string;
    'identifier'?: string;
    'initials'?: string;
    'listType'?: UserListDtoListTypeEnum;
    'name'?: string;
    'orgUserRole'?: UserListDtoOrgUserRoleEnum;
    'profileThumbnailPictureHash'?: string;
    'users'?: Array<UserItemDto>;
    'usersCount'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bubbleColor",
            "baseName": "bubbleColor",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "initials",
            "baseName": "initials",
            "type": "string",
            "format": ""
        },
        {
            "name": "listType",
            "baseName": "listType",
            "type": "UserListDtoListTypeEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "orgUserRole",
            "baseName": "orgUserRole",
            "type": "UserListDtoOrgUserRoleEnum",
            "format": ""
        },
        {
            "name": "profileThumbnailPictureHash",
            "baseName": "profileThumbnailPictureHash",
            "type": "string",
            "format": ""
        },
        {
            "name": "users",
            "baseName": "users",
            "type": "Array<UserItemDto>",
            "format": ""
        },
        {
            "name": "usersCount",
            "baseName": "usersCount",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return UserListDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UserListDtoListTypeEnum {
    Default = 'DEFAULT',
    Group = 'GROUP'
}
export enum UserListDtoOrgUserRoleEnum {
    Owner = 'OWNER',
    Admin = 'ADMIN',
    Member = 'MEMBER',
    Guest = 'GUEST',
    DockPro = 'DOCK_PRO',
    DockLite = 'DOCK_LITE',
    Collaborator = 'COLLABORATOR',
    ViewOnly = 'VIEW_ONLY'
}

