/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class UserPreferenceManageDto {
    'appFeaturesReviewed'?: any;
    'businessDomain'?: string;
    'demoNeeded'?: string;
    'displayGroups'?: any;
    'displayOptions'?: any;
    'ehrUsed'?: string;
    'jobFunction'?: string;
    'listDisplayColumnPrefs'?: any;
    'listDisplayColumns'?: any;
    'softwareUsed'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "appFeaturesReviewed",
            "baseName": "appFeaturesReviewed",
            "type": "any",
            "format": ""
        },
        {
            "name": "businessDomain",
            "baseName": "businessDomain",
            "type": "string",
            "format": ""
        },
        {
            "name": "demoNeeded",
            "baseName": "demoNeeded",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayGroups",
            "baseName": "displayGroups",
            "type": "any",
            "format": ""
        },
        {
            "name": "displayOptions",
            "baseName": "displayOptions",
            "type": "any",
            "format": ""
        },
        {
            "name": "ehrUsed",
            "baseName": "ehrUsed",
            "type": "string",
            "format": ""
        },
        {
            "name": "jobFunction",
            "baseName": "jobFunction",
            "type": "string",
            "format": ""
        },
        {
            "name": "listDisplayColumnPrefs",
            "baseName": "listDisplayColumnPrefs",
            "type": "any",
            "format": ""
        },
        {
            "name": "listDisplayColumns",
            "baseName": "listDisplayColumns",
            "type": "any",
            "format": ""
        },
        {
            "name": "softwareUsed",
            "baseName": "softwareUsed",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserPreferenceManageDto.attributeTypeMap;
    }

    public constructor() {
    }
}

