/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class UserItemDto {
    'bubbleColor'?: string;
    'externalUserId'?: string;
    'id'?: number;
    'identifier'?: string;
    'initials'?: string;
    'itemType'?: UserItemDtoItemTypeEnum;
    'name'?: string;
    'profileThumbnailPictureHash'?: string;
    'userStatus'?: UserItemDtoUserStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bubbleColor",
            "baseName": "bubbleColor",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalUserId",
            "baseName": "externalUserId",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "initials",
            "baseName": "initials",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemType",
            "baseName": "itemType",
            "type": "UserItemDtoItemTypeEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "profileThumbnailPictureHash",
            "baseName": "profileThumbnailPictureHash",
            "type": "string",
            "format": ""
        },
        {
            "name": "userStatus",
            "baseName": "userStatus",
            "type": "UserItemDtoUserStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserItemDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UserItemDtoItemTypeEnum {
    User = 'USER',
    Group = 'GROUP'
}
export enum UserItemDtoUserStatusEnum {
    Active = 'ACTIVE',
    Inactive = 'INACTIVE',
    Invited = 'INVITED',
    Cancelled = 'CANCELLED',
    Invalid = 'INVALID',
    Pending = 'PENDING',
    Approved = 'APPROVED',
    Denied = 'DENIED'
}

