/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SpecialtyDto } from '../models/SpecialtyDto';
import { TitleDto } from '../models/TitleDto';


/**
* User Details to Update
*/
export class UserManage {
    'accountPhoneNumber'?: string;
    'active'?: boolean;
    'bubbleColor'?: string;
    'credentials'?: string;
    'department'?: string;
    'email': string;
    'externalIdentifier'?: string;
    'faxNumber'?: string;
    'firstName': string;
    'homePhoneNumber'?: string;
    'initials'?: string;
    'lastName': string;
    'name'?: string;
    'notes'?: string;
    'providerMetaData'?: any;
    'referralCode'?: string;
    'specialties'?: Array<SpecialtyDto>;
    'specialtyList'?: string;
    'titleList'?: string;
    'titles'?: Array<TitleDto>;
    'userId'?: number;
    'userIdentifier'?: string;
    'userName'?: string;
    'username': string;
    'workPhoneNumber'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accountPhoneNumber",
            "baseName": "accountPhoneNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "bubbleColor",
            "baseName": "bubbleColor",
            "type": "string",
            "format": ""
        },
        {
            "name": "credentials",
            "baseName": "credentials",
            "type": "string",
            "format": ""
        },
        {
            "name": "department",
            "baseName": "department",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalIdentifier",
            "baseName": "externalIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "faxNumber",
            "baseName": "faxNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "homePhoneNumber",
            "baseName": "homePhoneNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "initials",
            "baseName": "initials",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "providerMetaData",
            "baseName": "providerMetaData",
            "type": "any",
            "format": ""
        },
        {
            "name": "referralCode",
            "baseName": "referralCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "specialties",
            "baseName": "specialties",
            "type": "Array<SpecialtyDto>",
            "format": ""
        },
        {
            "name": "specialtyList",
            "baseName": "specialtyList",
            "type": "string",
            "format": ""
        },
        {
            "name": "titleList",
            "baseName": "titleList",
            "type": "string",
            "format": ""
        },
        {
            "name": "titles",
            "baseName": "titles",
            "type": "Array<TitleDto>",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "userIdentifier",
            "baseName": "userIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string",
            "format": ""
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "workPhoneNumber",
            "baseName": "workPhoneNumber",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserManage.attributeTypeMap;
    }

    public constructor() {
    }
}

