/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class UserNotificationEventTypeDto {
    'description'?: string;
    'eventType'?: UserNotificationEventTypeDtoEventTypeEnum;
    'label'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "eventType",
            "baseName": "eventType",
            "type": "UserNotificationEventTypeDtoEventTypeEnum",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserNotificationEventTypeDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UserNotificationEventTypeDtoEventTypeEnum {
    TaskAssigned = 'TASK_ASSIGNED',
    TaskCompleted = 'TASK_COMPLETED',
    NewComment = 'NEW_COMMENT',
    NewAttachment = 'NEW_ATTACHMENT',
    TaskIsDue = 'TASK_IS_DUE'
}

