/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserItemDto } from '../models/UserItemDto';


/**
* User Group Details
*/
export class UserGroup {
    'bubbleColor'?: string;
    'description'?: string;
    'email'?: string;
    'externalUserId'?: string;
    'firstName'?: string;
    'id'?: number;
    'identifier'?: string;
    'initials'?: string;
    'itemType'?: UserGroupItemTypeEnum;
    'lastName'?: string;
    'name'?: string;
    'orgUserRole'?: UserGroupOrgUserRoleEnum;
    'profileThumbnailPictureHash'?: string;
    'status'?: UserGroupStatusEnum;
    'taskListUserRole'?: UserGroupTaskListUserRoleEnum;
    'userId'?: number;
    'userIdentifiers'?: Array<string>;
    'userName'?: string;
    'userStatus'?: UserGroupUserStatusEnum;
    'users'?: Array<UserItemDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bubbleColor",
            "baseName": "bubbleColor",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalUserId",
            "baseName": "externalUserId",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "initials",
            "baseName": "initials",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemType",
            "baseName": "itemType",
            "type": "UserGroupItemTypeEnum",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "orgUserRole",
            "baseName": "orgUserRole",
            "type": "UserGroupOrgUserRoleEnum",
            "format": ""
        },
        {
            "name": "profileThumbnailPictureHash",
            "baseName": "profileThumbnailPictureHash",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "UserGroupStatusEnum",
            "format": ""
        },
        {
            "name": "taskListUserRole",
            "baseName": "taskListUserRole",
            "type": "UserGroupTaskListUserRoleEnum",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "userIdentifiers",
            "baseName": "userIdentifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string",
            "format": ""
        },
        {
            "name": "userStatus",
            "baseName": "userStatus",
            "type": "UserGroupUserStatusEnum",
            "format": ""
        },
        {
            "name": "users",
            "baseName": "users",
            "type": "Array<UserItemDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserGroup.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UserGroupItemTypeEnum {
    User = 'USER',
    Group = 'GROUP'
}
export enum UserGroupOrgUserRoleEnum {
    Owner = 'OWNER',
    Admin = 'ADMIN',
    Member = 'MEMBER',
    Guest = 'GUEST',
    DockPro = 'DOCK_PRO',
    DockLite = 'DOCK_LITE',
    Collaborator = 'COLLABORATOR',
    ViewOnly = 'VIEW_ONLY'
}
export enum UserGroupStatusEnum {
    Active = 'ACTIVE',
    Pending = 'PENDING',
    Inactive = 'INACTIVE'
}
export enum UserGroupTaskListUserRoleEnum {
    Owner = 'OWNER',
    Admin = 'ADMIN',
    Member = 'MEMBER',
    Guest = 'GUEST',
    DockPro = 'DOCK_PRO',
    DockLite = 'DOCK_LITE',
    Collaborator = 'COLLABORATOR',
    ViewOnly = 'VIEW_ONLY'
}
export enum UserGroupUserStatusEnum {
    Active = 'ACTIVE',
    Inactive = 'INACTIVE',
    Invited = 'INVITED',
    Cancelled = 'CANCELLED',
    Invalid = 'INVALID',
    Pending = 'PENDING',
    Approved = 'APPROVED',
    Denied = 'DENIED'
}

