/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class UserUpdateMFADto {
    'email'?: string;
    'existingPhone'?: string;
    'newPhone'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "existingPhone",
            "baseName": "existingPhone",
            "type": "string",
            "format": ""
        },
        {
            "name": "newPhone",
            "baseName": "newPhone",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserUpdateMFADto.attributeTypeMap;
    }

    public constructor() {
    }
}

