/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class UserSummaryDto {
    'bubbleColor'?: string;
    'credentials'?: string;
    'externalUserId'?: string;
    'firstName'?: string;
    'id'?: number;
    'identifier'?: string;
    'initials'?: string;
    'itemType'?: UserSummaryDtoItemTypeEnum;
    'lastName'?: string;
    'name'?: string;
    'orgUserRole'?: UserSummaryDtoOrgUserRoleEnum;
    'profileThumbnailPictureHash'?: string;
    'providerMetaData'?: any;
    'status'?: UserSummaryDtoStatusEnum;
    'taskListUserRole'?: UserSummaryDtoTaskListUserRoleEnum;
    'userId'?: number;
    'userIdentifier'?: string;
    'userName'?: string;
    'userStatus'?: UserSummaryDtoUserStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bubbleColor",
            "baseName": "bubbleColor",
            "type": "string",
            "format": ""
        },
        {
            "name": "credentials",
            "baseName": "credentials",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalUserId",
            "baseName": "externalUserId",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "initials",
            "baseName": "initials",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemType",
            "baseName": "itemType",
            "type": "UserSummaryDtoItemTypeEnum",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "orgUserRole",
            "baseName": "orgUserRole",
            "type": "UserSummaryDtoOrgUserRoleEnum",
            "format": ""
        },
        {
            "name": "profileThumbnailPictureHash",
            "baseName": "profileThumbnailPictureHash",
            "type": "string",
            "format": ""
        },
        {
            "name": "providerMetaData",
            "baseName": "providerMetaData",
            "type": "any",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "UserSummaryDtoStatusEnum",
            "format": ""
        },
        {
            "name": "taskListUserRole",
            "baseName": "taskListUserRole",
            "type": "UserSummaryDtoTaskListUserRoleEnum",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "userIdentifier",
            "baseName": "userIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string",
            "format": ""
        },
        {
            "name": "userStatus",
            "baseName": "userStatus",
            "type": "UserSummaryDtoUserStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserSummaryDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UserSummaryDtoItemTypeEnum {
    User = 'USER',
    Group = 'GROUP'
}
export enum UserSummaryDtoOrgUserRoleEnum {
    Owner = 'OWNER',
    Admin = 'ADMIN',
    Member = 'MEMBER',
    Guest = 'GUEST',
    DockPro = 'DOCK_PRO',
    DockLite = 'DOCK_LITE',
    Collaborator = 'COLLABORATOR',
    ViewOnly = 'VIEW_ONLY'
}
export enum UserSummaryDtoStatusEnum {
    Active = 'ACTIVE',
    Pending = 'PENDING',
    Inactive = 'INACTIVE'
}
export enum UserSummaryDtoTaskListUserRoleEnum {
    Owner = 'OWNER',
    Admin = 'ADMIN',
    Member = 'MEMBER',
    Guest = 'GUEST',
    DockPro = 'DOCK_PRO',
    DockLite = 'DOCK_LITE',
    Collaborator = 'COLLABORATOR',
    ViewOnly = 'VIEW_ONLY'
}
export enum UserSummaryDtoUserStatusEnum {
    Active = 'ACTIVE',
    Inactive = 'INACTIVE',
    Invited = 'INVITED',
    Cancelled = 'CANCELLED',
    Invalid = 'INVALID',
    Pending = 'PENDING',
    Approved = 'APPROVED',
    Denied = 'DENIED'
}

