/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class UserDeviceTokenDto {
    'deviceToken'?: string;
    'deviceType'?: UserDeviceTokenDtoDeviceTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "deviceToken",
            "baseName": "deviceToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "deviceType",
            "baseName": "deviceType",
            "type": "UserDeviceTokenDtoDeviceTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserDeviceTokenDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UserDeviceTokenDtoDeviceTypeEnum {
    Ios = 'IOS',
    Android = 'ANDROID'
}

