/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class UserNotificationSettingDto {
    'description'?: string;
    'emailEnabled'?: boolean;
    'eventType'?: UserNotificationSettingDtoEventTypeEnum;
    'label'?: string;
    'pushNotificationEnabled'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "emailEnabled",
            "baseName": "emailEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "eventType",
            "baseName": "eventType",
            "type": "UserNotificationSettingDtoEventTypeEnum",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "pushNotificationEnabled",
            "baseName": "pushNotificationEnabled",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserNotificationSettingDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UserNotificationSettingDtoEventTypeEnum {
    TaskAssigned = 'TASK_ASSIGNED',
    TaskCompleted = 'TASK_COMPLETED',
    NewComment = 'NEW_COMMENT',
    NewAttachment = 'NEW_ATTACHMENT',
    TaskIsDue = 'TASK_IS_DUE'
}

