/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class UserInviteDto {
    'comments'?: string;
    'createdDateTime'?: Date;
    'email'?: string;
    'firstName'?: string;
    'invitationId'?: number;
    'invitedByFirstName'?: string;
    'invitedByLastName'?: string;
    'lastName'?: string;
    'listInviteStatus'?: UserInviteDtoListInviteStatusEnum;
    'taskListId'?: number;
    'taskListIdentifier'?: string;
    'taskListName'?: string;
    'updatedDateTime'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "comments",
            "baseName": "comments",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdDateTime",
            "baseName": "createdDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "invitationId",
            "baseName": "invitationId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "invitedByFirstName",
            "baseName": "invitedByFirstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "invitedByLastName",
            "baseName": "invitedByLastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "listInviteStatus",
            "baseName": "listInviteStatus",
            "type": "UserInviteDtoListInviteStatusEnum",
            "format": ""
        },
        {
            "name": "taskListId",
            "baseName": "taskListId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "taskListIdentifier",
            "baseName": "taskListIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskListName",
            "baseName": "taskListName",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedDateTime",
            "baseName": "updatedDateTime",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return UserInviteDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UserInviteDtoListInviteStatusEnum {
    Pending = 'PENDING',
    Accepted = 'ACCEPTED',
    Rejected = 'REJECTED',
    Expired = 'EXPIRED',
    Cancelled = 'CANCELLED',
    Inactive = 'INACTIVE'
}

