/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class UserNotificationPrefDto {
    'email'?: boolean;
    'push'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "push",
            "baseName": "push",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserNotificationPrefDto.attributeTypeMap;
    }

    public constructor() {
    }
}

