/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SpecialtyDto } from '../models/SpecialtyDto';
import { SubscriptionDto } from '../models/SubscriptionDto';
import { TaskListSummaryDto } from '../models/TaskListSummaryDto';
import { TitleDto } from '../models/TitleDto';
import { UsageState } from '../models/UsageState';
import { UserPreferenceDto } from '../models/UserPreferenceDto';


/**
* User Details
*/
export class User {
    'accountPhoneNumber'?: string;
    'baaSigned'?: boolean;
    'bubbleColor'?: string;
    'credentials'?: string;
    'defaultSlimView'?: boolean;
    'department'?: string;
    'email': string;
    'emrIntegrationEnabled'?: boolean;
    'emrIntegrationType'?: string;
    'eulaAcknowledged'?: boolean;
    'eulaAcknowledgedDateTime'?: Date;
    'externalIdentifier'?: string;
    'externalUserId'?: string;
    'faxNumber'?: string;
    'firstName': string;
    'homePhoneNumber'?: string;
    'id'?: number;
    'identifier'?: string;
    'inboxTaskListIdentifier'?: string;
    'initials'?: string;
    'itemType'?: UserItemTypeEnum;
    'lastName': string;
    'name'?: string;
    'notes'?: string;
    'orgUserRole'?: UserOrgUserRoleEnum;
    'organizationAvailableFeatures'?: any;
    'organizationCustomerType'?: UserOrganizationCustomerTypeEnum;
    'organizationId'?: number;
    'organizationIdentifier'?: string;
    'organizationInitials'?: string;
    'organizationName'?: string;
    'organizationProfileColor'?: string;
    'personalOrganization'?: boolean;
    'presentHippaAlert'?: boolean;
    'profilePictureHash'?: string;
    'profileThumbnailPictureHash'?: string;
    'providerMetaData'?: any;
    'referralCode'?: string;
    'registrationDate'?: Date;
    'specialties'?: Array<SpecialtyDto>;
    'specialtyList'?: string;
    'status'?: UserStatusEnum;
    'subscription'?: SubscriptionDto;
    'taskListUserRole'?: UserTaskListUserRoleEnum;
    'taskLists'?: Array<TaskListSummaryDto>;
    'timezoneOffset'?: number;
    'titleList'?: string;
    'titles'?: Array<TitleDto>;
    'usageState'?: UsageState;
    'userId'?: number;
    'userIdentifier'?: string;
    'userInviteStatus'?: UserUserInviteStatusEnum;
    'userName'?: string;
    'userPreference'?: UserPreferenceDto;
    'userStatus'?: UserUserStatusEnum;
    'username': string;
    'workPhoneNumber'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accountPhoneNumber",
            "baseName": "accountPhoneNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "baaSigned",
            "baseName": "baaSigned",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "bubbleColor",
            "baseName": "bubbleColor",
            "type": "string",
            "format": ""
        },
        {
            "name": "credentials",
            "baseName": "credentials",
            "type": "string",
            "format": ""
        },
        {
            "name": "defaultSlimView",
            "baseName": "defaultSlimView",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "department",
            "baseName": "department",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "emrIntegrationEnabled",
            "baseName": "emrIntegrationEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "emrIntegrationType",
            "baseName": "emrIntegrationType",
            "type": "string",
            "format": ""
        },
        {
            "name": "eulaAcknowledged",
            "baseName": "eulaAcknowledged",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "eulaAcknowledgedDateTime",
            "baseName": "eulaAcknowledgedDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "externalIdentifier",
            "baseName": "externalIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalUserId",
            "baseName": "externalUserId",
            "type": "string",
            "format": ""
        },
        {
            "name": "faxNumber",
            "baseName": "faxNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "homePhoneNumber",
            "baseName": "homePhoneNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "inboxTaskListIdentifier",
            "baseName": "inboxTaskListIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "initials",
            "baseName": "initials",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemType",
            "baseName": "itemType",
            "type": "UserItemTypeEnum",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "orgUserRole",
            "baseName": "orgUserRole",
            "type": "UserOrgUserRoleEnum",
            "format": ""
        },
        {
            "name": "organizationAvailableFeatures",
            "baseName": "organizationAvailableFeatures",
            "type": "any",
            "format": ""
        },
        {
            "name": "organizationCustomerType",
            "baseName": "organizationCustomerType",
            "type": "UserOrganizationCustomerTypeEnum",
            "format": ""
        },
        {
            "name": "organizationId",
            "baseName": "organizationId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "organizationIdentifier",
            "baseName": "organizationIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationInitials",
            "baseName": "organizationInitials",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationName",
            "baseName": "organizationName",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationProfileColor",
            "baseName": "organizationProfileColor",
            "type": "string",
            "format": ""
        },
        {
            "name": "personalOrganization",
            "baseName": "personalOrganization",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "presentHippaAlert",
            "baseName": "presentHippaAlert",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "profilePictureHash",
            "baseName": "profilePictureHash",
            "type": "string",
            "format": ""
        },
        {
            "name": "profileThumbnailPictureHash",
            "baseName": "profileThumbnailPictureHash",
            "type": "string",
            "format": ""
        },
        {
            "name": "providerMetaData",
            "baseName": "providerMetaData",
            "type": "any",
            "format": ""
        },
        {
            "name": "referralCode",
            "baseName": "referralCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "registrationDate",
            "baseName": "registrationDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "specialties",
            "baseName": "specialties",
            "type": "Array<SpecialtyDto>",
            "format": ""
        },
        {
            "name": "specialtyList",
            "baseName": "specialtyList",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "UserStatusEnum",
            "format": ""
        },
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "SubscriptionDto",
            "format": ""
        },
        {
            "name": "taskListUserRole",
            "baseName": "taskListUserRole",
            "type": "UserTaskListUserRoleEnum",
            "format": ""
        },
        {
            "name": "taskLists",
            "baseName": "taskLists",
            "type": "Array<TaskListSummaryDto>",
            "format": ""
        },
        {
            "name": "timezoneOffset",
            "baseName": "timezoneOffset",
            "type": "number",
            "format": "double"
        },
        {
            "name": "titleList",
            "baseName": "titleList",
            "type": "string",
            "format": ""
        },
        {
            "name": "titles",
            "baseName": "titles",
            "type": "Array<TitleDto>",
            "format": ""
        },
        {
            "name": "usageState",
            "baseName": "usageState",
            "type": "UsageState",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "userIdentifier",
            "baseName": "userIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "userInviteStatus",
            "baseName": "userInviteStatus",
            "type": "UserUserInviteStatusEnum",
            "format": ""
        },
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string",
            "format": ""
        },
        {
            "name": "userPreference",
            "baseName": "userPreference",
            "type": "UserPreferenceDto",
            "format": ""
        },
        {
            "name": "userStatus",
            "baseName": "userStatus",
            "type": "UserUserStatusEnum",
            "format": ""
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "workPhoneNumber",
            "baseName": "workPhoneNumber",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UserItemTypeEnum {
    User = 'USER',
    Group = 'GROUP'
}
export enum UserOrgUserRoleEnum {
    Owner = 'OWNER',
    Admin = 'ADMIN',
    Member = 'MEMBER',
    Guest = 'GUEST',
    DockPro = 'DOCK_PRO',
    DockLite = 'DOCK_LITE',
    Collaborator = 'COLLABORATOR',
    ViewOnly = 'VIEW_ONLY'
}
export enum UserOrganizationCustomerTypeEnum {
    Patient = 'PATIENT',
    Client = 'CLIENT',
    Member = 'MEMBER',
    Customer = 'CUSTOMER'
}
export enum UserStatusEnum {
    Active = 'ACTIVE',
    Pending = 'PENDING',
    Inactive = 'INACTIVE'
}
export enum UserTaskListUserRoleEnum {
    Owner = 'OWNER',
    Admin = 'ADMIN',
    Member = 'MEMBER',
    Guest = 'GUEST',
    DockPro = 'DOCK_PRO',
    DockLite = 'DOCK_LITE',
    Collaborator = 'COLLABORATOR',
    ViewOnly = 'VIEW_ONLY'
}
export enum UserUserInviteStatusEnum {
    Pending = 'PENDING',
    Accepted = 'ACCEPTED',
    Rejected = 'REJECTED',
    Expired = 'EXPIRED',
    Cancelled = 'CANCELLED',
    Inactive = 'INACTIVE'
}
export enum UserUserStatusEnum {
    Active = 'ACTIVE',
    Inactive = 'INACTIVE',
    Invited = 'INVITED',
    Cancelled = 'CANCELLED',
    Invalid = 'INVALID',
    Pending = 'PENDING',
    Approved = 'APPROVED',
    Denied = 'DENIED'
}

