/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WidgetDto } from '../models/WidgetDto';


export class WidgetLaunchDetailsDto {
    'authToken'?: string;
    'idToken'?: string;
    'widgets'?: Array<WidgetDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "authToken",
            "baseName": "authToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "idToken",
            "baseName": "idToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "widgets",
            "baseName": "widgets",
            "type": "Array<WidgetDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WidgetLaunchDetailsDto.attributeTypeMap;
    }

    public constructor() {
    }
}

