/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PatientSummaryDto } from '../models/PatientSummaryDto';
import { TaskDto } from '../models/TaskDto';
import { TaskTemplateDto } from '../models/TaskTemplateDto';
import { TaskTemplateMember } from '../models/TaskTemplateMember';
import { TaskWorkflowStatusDto } from '../models/TaskWorkflowStatusDto';
import { UserItemDto } from '../models/UserItemDto';
import { UserSummaryDto } from '../models/UserSummaryDto';


export class WorkflowDto {
    'anchorDateTime'?: Date;
    'assignedToUsers'?: Array<UserItemDto>;
    'attachments'?: any;
    'comments'?: any;
    'createdDateTime'?: Date;
    'creator'?: UserSummaryDto;
    'description'?: string;
    'descriptionCleared'?: boolean;
    'dueDateTime'?: Date;
    'hasMentions'?: boolean;
    'identifier'?: string;
    'itemType'?: WorkflowDtoItemTypeEnum;
    'labels'?: any;
    'members'?: Array<Task Template Member>;
    'name'?: string;
    'parentTaskWorkflowIdentifier'?: string;
    'patient'?: PatientSummaryDto;
    'patientIdentifier'?: string;
    'priority'?: WorkflowDtoPriorityEnum;
    'publicAccess'?: boolean;
    'reminderDateTime'?: Date;
    'reminderTime'?: string;
    'reminderType'?: WorkflowDtoReminderTypeEnum;
    'sortIndexOfTaskInGroup'?: number;
    'taskBundleTemplate'?: TaskTemplateDto;
    'startDateTime'?: Date;
    'taskListIdentifier'?: string;
    'taskMentions'?: any;
    'taskMetaData'?: any;
    'tasks'?: Array<TaskDto>;
    'tasksCompletedCount'?: number;
    'tasksCount'?: number;
    'templateType'?: WorkflowDtoTemplateTypeEnum;
    'tokenizedDescription'?: string;
    'workflowStatus'?: TaskWorkflowStatusDto;
    'workflowStatusIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "anchorDateTime",
            "baseName": "anchorDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "assignedToUsers",
            "baseName": "assignedToUsers",
            "type": "Array<UserItemDto>",
            "format": ""
        },
        {
            "name": "attachments",
            "baseName": "attachments",
            "type": "any",
            "format": ""
        },
        {
            "name": "comments",
            "baseName": "comments",
            "type": "any",
            "format": ""
        },
        {
            "name": "createdDateTime",
            "baseName": "createdDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "UserSummaryDto",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "descriptionCleared",
            "baseName": "descriptionCleared",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "dueDateTime",
            "baseName": "dueDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "hasMentions",
            "baseName": "hasMentions",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemType",
            "baseName": "itemType",
            "type": "WorkflowDtoItemTypeEnum",
            "format": ""
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "any",
            "format": ""
        },
        {
            "name": "members",
            "baseName": "members",
            "type": "Array<Task Template Member>",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentTaskWorkflowIdentifier",
            "baseName": "parentTaskWorkflowIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "patient",
            "baseName": "patient",
            "type": "PatientSummaryDto",
            "format": ""
        },
        {
            "name": "patientIdentifier",
            "baseName": "patientIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "WorkflowDtoPriorityEnum",
            "format": ""
        },
        {
            "name": "publicAccess",
            "baseName": "publicAccess",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "reminderDateTime",
            "baseName": "reminderDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "reminderTime",
            "baseName": "reminderTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "reminderType",
            "baseName": "reminderType",
            "type": "WorkflowDtoReminderTypeEnum",
            "format": ""
        },
        {
            "name": "sortIndexOfTaskInGroup",
            "baseName": "sortIndexOfTaskInGroup",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "taskBundleTemplate",
            "baseName": "taskBundleTemplate",
            "type": "TaskTemplateDto",
            "format": ""
        },
        {
            "name": "startDateTime",
            "baseName": "startDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "taskListIdentifier",
            "baseName": "taskListIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskMentions",
            "baseName": "taskMentions",
            "type": "any",
            "format": ""
        },
        {
            "name": "taskMetaData",
            "baseName": "taskMetaData",
            "type": "any",
            "format": ""
        },
        {
            "name": "tasks",
            "baseName": "tasks",
            "type": "Array<TaskDto>",
            "format": ""
        },
        {
            "name": "tasksCompletedCount",
            "baseName": "tasksCompletedCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "tasksCount",
            "baseName": "tasksCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "templateType",
            "baseName": "templateType",
            "type": "WorkflowDtoTemplateTypeEnum",
            "format": ""
        },
        {
            "name": "tokenizedDescription",
            "baseName": "tokenizedDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "workflowStatus",
            "baseName": "workflowStatus",
            "type": "TaskWorkflowStatusDto",
            "format": ""
        },
        {
            "name": "workflowStatusIdentifier",
            "baseName": "workflowStatusIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WorkflowDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum WorkflowDtoItemTypeEnum {
    Task = 'TASK',
    Bundle = 'BUNDLE',
    Template = 'TEMPLATE'
}
export enum WorkflowDtoPriorityEnum {
    High = 'HIGH',
    Medium = 'MEDIUM',
    Low = 'LOW',
    None = 'NONE'
}
export enum WorkflowDtoReminderTypeEnum {
    None = 'NONE',
    DayOf = 'DAY_OF',
    DayBefore1 = 'DAY_BEFORE_1',
    DayBefore2 = 'DAY_BEFORE_2',
    WeekBefore1 = 'WEEK_BEFORE_1'
}
export enum WorkflowDtoTemplateTypeEnum {
    Workflow = 'WORKFLOW',
    Smartflow = 'SMARTFLOW',
    SmartflowSample = 'SMARTFLOW_SAMPLE',
    Folder = 'FOLDER'
}

