/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class WorkflowUseDto {
    'anchorDateTime'?: Date;
    'assignedToIdentifier'?: string;
    'assignedToIdentifiers'?: Array<string>;
    'details'?: string;
    'dueDateTime'?: Date;
    'labelIdentifier'?: string;
    'overrideAssignmentMismatch'?: boolean;
    'patientIdentifier'?: string;
    'sourceTaskBundleIdentifier'?: string;
    'startDateTime'?: Date;
    'taskGroupIdentifier'?: string;
    'taskListIdentifier'?: string;
    'taskTemplateIdentifier'?: string;
    'workflowStatusIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "anchorDateTime",
            "baseName": "anchorDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "assignedToIdentifier",
            "baseName": "assignedToIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "assignedToIdentifiers",
            "baseName": "assignedToIdentifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "string",
            "format": ""
        },
        {
            "name": "dueDateTime",
            "baseName": "dueDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "labelIdentifier",
            "baseName": "labelIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "overrideAssignmentMismatch",
            "baseName": "overrideAssignmentMismatch",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "patientIdentifier",
            "baseName": "patientIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourceTaskBundleIdentifier",
            "baseName": "sourceTaskBundleIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "startDateTime",
            "baseName": "startDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "taskGroupIdentifier",
            "baseName": "taskGroupIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskListIdentifier",
            "baseName": "taskListIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskTemplateIdentifier",
            "baseName": "taskTemplateIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "workflowStatusIdentifier",
            "baseName": "workflowStatusIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WorkflowUseDto.attributeTypeMap;
    }

    public constructor() {
    }
}

