/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WorkflowDto } from '../models/WorkflowDto';


export class WorkflowUseServiceResponse {
    'assignmentsMismatchCount'?: number;
    'errorCode'?: string;
    'errorMessage'?: string;
    'statusCode'?: WorkflowUseServiceResponseStatusCodeEnum;
    'statusMessage'?: string;
    'taskWorkflowDto'?: WorkflowDto;
    'uuid'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assignmentsMismatchCount",
            "baseName": "assignmentsMismatchCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "errorCode",
            "baseName": "errorCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "errorMessage",
            "baseName": "errorMessage",
            "type": "string",
            "format": ""
        },
        {
            "name": "statusCode",
            "baseName": "statusCode",
            "type": "WorkflowUseServiceResponseStatusCodeEnum",
            "format": ""
        },
        {
            "name": "statusMessage",
            "baseName": "statusMessage",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskWorkflowDto",
            "baseName": "taskWorkflowDto",
            "type": "WorkflowDto",
            "format": ""
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WorkflowUseServiceResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum WorkflowUseServiceResponseStatusCodeEnum {
    Success = 'SUCCESS',
    Warning = 'WARNING',
    Failure = 'FAILURE'
}

