/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TaskTemplateMember } from '../models/TaskTemplateMember';


export class WorkflowUpdateDto {
    'anchorDateTime'?: Date;
    'anchorDateTimeCleared'?: boolean;
    'assignedByIdentifier'?: string;
    'assignedToIdentifiers'?: Array<string>;
    'attachments'?: any;
    'comments'?: any;
    'description'?: string;
    'descriptionCleared'?: boolean;
    'dueDateTime'?: Date;
    'dueDateTimeCleared'?: boolean;
    'identifier'?: string;
    'itemType'?: WorkflowUpdateDtoItemTypeEnum;
    'labels'?: any;
    'members'?: Array<Task Template Member>;
    'name'?: string;
    'parentTaskWorkflowIdentifier'?: string;
    'patientIdentifier'?: string;
    'priority'?: WorkflowUpdateDtoPriorityEnum;
    'publicAccess'?: boolean;
    'reminderDateTime'?: Date;
    'reminderTime'?: string;
    'reminderType'?: WorkflowUpdateDtoReminderTypeEnum;
    'startDateTime'?: Date;
    'startDateTimeCleared'?: boolean;
    'taskListIdentifier'?: string;
    'taskMetaData'?: any;
    'templateType'?: WorkflowUpdateDtoTemplateTypeEnum;
    'workflowStatusCleared'?: boolean;
    'workflowStatusIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "anchorDateTime",
            "baseName": "anchorDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "anchorDateTimeCleared",
            "baseName": "anchorDateTimeCleared",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "assignedByIdentifier",
            "baseName": "assignedByIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "assignedToIdentifiers",
            "baseName": "assignedToIdentifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "attachments",
            "baseName": "attachments",
            "type": "any",
            "format": ""
        },
        {
            "name": "comments",
            "baseName": "comments",
            "type": "any",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "descriptionCleared",
            "baseName": "descriptionCleared",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "dueDateTime",
            "baseName": "dueDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dueDateTimeCleared",
            "baseName": "dueDateTimeCleared",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemType",
            "baseName": "itemType",
            "type": "WorkflowUpdateDtoItemTypeEnum",
            "format": ""
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "any",
            "format": ""
        },
        {
            "name": "members",
            "baseName": "members",
            "type": "Array<Task Template Member>",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentTaskWorkflowIdentifier",
            "baseName": "parentTaskWorkflowIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "patientIdentifier",
            "baseName": "patientIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "WorkflowUpdateDtoPriorityEnum",
            "format": ""
        },
        {
            "name": "publicAccess",
            "baseName": "publicAccess",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "reminderDateTime",
            "baseName": "reminderDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "reminderTime",
            "baseName": "reminderTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "reminderType",
            "baseName": "reminderType",
            "type": "WorkflowUpdateDtoReminderTypeEnum",
            "format": ""
        },
        {
            "name": "startDateTime",
            "baseName": "startDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "startDateTimeCleared",
            "baseName": "startDateTimeCleared",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "taskListIdentifier",
            "baseName": "taskListIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskMetaData",
            "baseName": "taskMetaData",
            "type": "any",
            "format": ""
        },
        {
            "name": "templateType",
            "baseName": "templateType",
            "type": "WorkflowUpdateDtoTemplateTypeEnum",
            "format": ""
        },
        {
            "name": "workflowStatusCleared",
            "baseName": "workflowStatusCleared",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "workflowStatusIdentifier",
            "baseName": "workflowStatusIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WorkflowUpdateDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum WorkflowUpdateDtoItemTypeEnum {
    Task = 'TASK',
    Bundle = 'BUNDLE',
    Template = 'TEMPLATE'
}
export enum WorkflowUpdateDtoPriorityEnum {
    High = 'HIGH',
    Medium = 'MEDIUM',
    Low = 'LOW',
    None = 'NONE'
}
export enum WorkflowUpdateDtoReminderTypeEnum {
    None = 'NONE',
    DayOf = 'DAY_OF',
    DayBefore1 = 'DAY_BEFORE_1',
    DayBefore2 = 'DAY_BEFORE_2',
    WeekBefore1 = 'WEEK_BEFORE_1'
}
export enum WorkflowUpdateDtoTemplateTypeEnum {
    Workflow = 'WORKFLOW',
    Smartflow = 'SMARTFLOW',
    SmartflowSample = 'SMARTFLOW_SAMPLE',
    Folder = 'FOLDER'
}

