/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class WorkflowCreateDto {
    'assignedByIdentifier'?: string;
    'assignedToIdentifiers'?: Array<string>;
    'attachments'?: any;
    'comments'?: any;
    'description'?: string;
    'dueDateTime'?: Date;
    'identifier'?: string;
    'itemType'?: WorkflowCreateDtoItemTypeEnum;
    'labels'?: any;
    'name'?: string;
    'parentTaskWorkflowIdentifier'?: string;
    'priority'?: WorkflowCreateDtoPriorityEnum;
    'publicAccessFlag'?: boolean;
    'reminderDateTime'?: Date;
    'reminderTime'?: string;
    'reminderType'?: WorkflowCreateDtoReminderTypeEnum;
    'startDateTime'?: Date;
    'taskMetaData'?: any;
    'templateType'?: WorkflowCreateDtoTemplateTypeEnum;
    'workflowStatusIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assignedByIdentifier",
            "baseName": "assignedByIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "assignedToIdentifiers",
            "baseName": "assignedToIdentifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "attachments",
            "baseName": "attachments",
            "type": "any",
            "format": ""
        },
        {
            "name": "comments",
            "baseName": "comments",
            "type": "any",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "dueDateTime",
            "baseName": "dueDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemType",
            "baseName": "itemType",
            "type": "WorkflowCreateDtoItemTypeEnum",
            "format": ""
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "any",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentTaskWorkflowIdentifier",
            "baseName": "parentTaskWorkflowIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "WorkflowCreateDtoPriorityEnum",
            "format": ""
        },
        {
            "name": "publicAccessFlag",
            "baseName": "publicAccessFlag",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "reminderDateTime",
            "baseName": "reminderDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "reminderTime",
            "baseName": "reminderTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "reminderType",
            "baseName": "reminderType",
            "type": "WorkflowCreateDtoReminderTypeEnum",
            "format": ""
        },
        {
            "name": "startDateTime",
            "baseName": "startDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "taskMetaData",
            "baseName": "taskMetaData",
            "type": "any",
            "format": ""
        },
        {
            "name": "templateType",
            "baseName": "templateType",
            "type": "WorkflowCreateDtoTemplateTypeEnum",
            "format": ""
        },
        {
            "name": "workflowStatusIdentifier",
            "baseName": "workflowStatusIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WorkflowCreateDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum WorkflowCreateDtoItemTypeEnum {
    Task = 'TASK',
    Bundle = 'BUNDLE',
    Template = 'TEMPLATE'
}
export enum WorkflowCreateDtoPriorityEnum {
    High = 'HIGH',
    Medium = 'MEDIUM',
    Low = 'LOW',
    None = 'NONE'
}
export enum WorkflowCreateDtoReminderTypeEnum {
    None = 'NONE',
    DayOf = 'DAY_OF',
    DayBefore1 = 'DAY_BEFORE_1',
    DayBefore2 = 'DAY_BEFORE_2',
    WeekBefore1 = 'WEEK_BEFORE_1'
}
export enum WorkflowCreateDtoTemplateTypeEnum {
    Workflow = 'WORKFLOW',
    Smartflow = 'SMARTFLOW',
    SmartflowSample = 'SMARTFLOW_SAMPLE',
    Folder = 'FOLDER'
}

