import { UserOrganizationRole } from 'helpers/user-helper';

export const PERMISSIONS = {
  CAN_ACCESS_HOME_PAGE: 'canAccessHomePage',
  CAN_ACCESS_SEARCH_PAGE: 'canAccessSearchPage',
  CAN_ACCESS_TASK_LIST_PAGE: 'canAccessSearchPage',
  CAN_ACCESS_PEOPLE_LIST_PAGE: 'canAccessPeopleListPage',
  CAN_ACCESS_MEMBER_LIST_PAGE: 'canAccessMemberListPage',
  CAN_ACCESS_WORKFLOW_LIST_PAGE: 'canAccessWorkflowListPage',
  CAN_ACCESS_ANALYTICS_PAGE: 'canAccessAnalyticsPage',
  CAN_ACCESS_SETTINGS_PAGE: 'canAccessSettingsPage',
  CAN_ACCESS_PROFILE_PAGE: 'canAccessProfilePage',
  CAN_ACCESS_EDUCATION_CENTER_PAGE: 'canAccessEducationCenterPage',
  CAN_ACCESS_WORKSPACE_PAGE: 'canAccessWorkspacePage',
  CAN_ACCESS_DATA_MANAGEMENT_PAGE: 'canAccessDataManagementPage',
};

export default {
  [UserOrganizationRole.OWNER]: {
    canAccessHomePage: true,
    canAccessSearchPage: true,
    canAccessTaskListPage: true,
    canAccessPeopleListPage: true,
    canAccessMemberListPage: true,
    canAccessWorkflowListPage: true,
    canAccessAnalyticsPage: true,
    canAccessSettingsPage: true,
    canAccessProfilePage: true,
    canAccessEducationCenterPage: true,
    canAccessWorkspacePage: true,
    canAccessDataManagementPage: true,
  },
  [UserOrganizationRole.ADMIN]: {
    canAccessHomePage: true,
    canAccessSearchPage: true,
    canAccessTaskListPage: true,
    canAccessPeopleListPage: true,
    canAccessMemberListPage: true,
    canAccessWorkflowListPage: true,
    canAccessAnalyticsPage: true,
    canAccessSettingsPage: true,
    canAccessProfilePage: true,
    canAccessEducationCenterPage: true,
    canAccessWorkspacePage: true,
    canAccessDataManagementPage: true,
  },
  [UserOrganizationRole.MEMBER]: {
    canAccessHomePage: true,
    canAccessSearchPage: true,
    canAccessTaskListPage: true,
    canAccessPeopleListPage: true,
    canAccessMemberListPage: true,
    canAccessWorkflowListPage: true,
    canAccessAnalyticsPage: false,
    canAccessSettingsPage: false,
    canAccessProfilePage: true,
    canAccessEducationCenterPage: true,
    canAccessWorkspacePage: true,
    canAccessDataManagementPage: true,
  },
  [UserOrganizationRole.GUEST]: {
    canAccessHomePage: true,
    canAccessSearchPage: true,
    canAccessTaskListPage: true,
    canAccessPeopleListPage: false,
    canAccessMemberListPage: true,
    canAccessWorkflowListPage: false,
    canAccessAnalyticsPage: false,
    canAccessSettingsPage: false,
    canAccessProfilePage: true,
    canAccessEducationCenterPage: true,
    canAccessWorkspacePage: true,
    canAccessDataManagementPage: true,
  },
  [UserOrganizationRole.DOCK_LITE]: {
    canAccessHomePage: true,
    canAccessSearchPage: true,
    canAccessTaskListPage: true,
    canAccessPeopleListPage: false,
    canAccessMemberListPage: true,
    canAccessWorkflowListPage: false,
    canAccessAnalyticsPage: false,
    canAccessSettingsPage: false,
    canAccessProfilePage: true,
    canAccessEducationCenterPage: true,
    canAccessWorkspacePage: true,
    canAccessDataManagementPage: true,
  },
  [UserOrganizationRole.EXTERNAL]: {
    canAccessHomePage: true,
    canAccessSearchPage: true,
    canAccessTaskListPage: false,
    canAccessPeopleListPage: false,
    canAccessMemberListPage: false,
    canAccessWorkflowListPage: false,
    canAccessAnalyticsPage: false,
    canAccessSettingsPage: false,
    canAccessProfilePage: true,
    canAccessEducationCenterPage: true,
    canAccessWorkspacePage: true,
    canAccessDataManagementPage: true,
  },
  [UserOrganizationRole.DOCK_PRO]: {
    canAccessHomePage: true,
    canAccessSearchPage: true,
    canAccessTaskListPage: true,
    canAccessPeopleListPage: true,
    canAccessMemberListPage: true,
    canAccessWorkflowListPage: true,
    canAccessAnalyticsPage: false,
    canAccessSettingsPage: true,
    canAccessProfilePage: true,
    canAccessEducationCenterPage: true,
    canAccessWorkspacePage: true,
    canAccessDataManagementPage: true,
  },
  [UserOrganizationRole.VIEW_ONLY]: {
    canAccessHomePage: true,
    canAccessSearchPage: true,
    canAccessTaskListPage: true,
    canAccessPeopleListPage: false,
    canAccessMemberListPage: true,
    canAccessWorkflowListPage: false,
    canAccessAnalyticsPage: false,
    canAccessSettingsPage: false,
    canAccessProfilePage: true,
    canAccessEducationCenterPage: true,
    canAccessWorkspacePage: true,
    canAccessDataManagementPage: true,
  },
};
