import { UserOrganizationRole } from 'helpers/user-helper';

export const PERMISSIONS = {
  CAN_ACCESS_HOME_PAGE: 'canAccessHomePage',
  CAN_ACCESS_SEARCH_PAGE: 'canAccessSearchPage',
  CAN_ACCESS_TASK_LIST_PAGE: 'canAccessSearchPage',
  CAN_ACCESS_PEOPLE_LIST_PAGE: 'canAccessPeopleListPage',
  CAN_ACCESS_MEMBER_LIST_PAGE: 'canAccessMemberListPage',
  CAN_ACCESS_WORKFLOW_LIST_PAGE: 'canAccessWorkflowListPage',
  CAN_ACCESS_ANALYTICS_PAGE: 'canAccessAnalyticsPage',
  CAN_ACCESS_CHAT_PAGE: 'canAccessChatPage',
  CAN_ACCESS_SETTINGS_PAGE: 'canAccessSettingsPage',
  CAN_ACCESS_EDUCATION_CENTER_PAGE: 'canAccessEducationCenterPage',
};

export default {
  [UserOrganizationRole.OWNER]: {
    canAccessHomePage: true,
    canAccessSearchPage: true,
    canAccessTaskListPage: true,
    canAccessPeopleListPage: true,
    canAccessMemberListPage: true,
    canAccessWorkflowListPage: true,
    canAccessAnalyticsPage: true,
    canAccessChatPage: true,
    canAccessSettingsPage: true,
    canAccessEducationCenterPage: true,
  },
  [UserOrganizationRole.ADMIN]: {
    canAccessHomePage: true,
    canAccessSearchPage: true,
    canAccessTaskListPage: true,
    canAccessPeopleListPage: true,
    canAccessMemberListPage: true,
    canAccessWorkflowListPage: true,
    canAccessAnalyticsPage: true,
    canAccessChatPage: true,
    canAccessSettingsPage: true,
    canAccessEducationCenterPage: true,
  },
  [UserOrganizationRole.MEMBER]: {
    canAccessHomePage: true,
    canAccessSearchPage: true,
    canAccessTaskListPage: true,
    canAccessPeopleListPage: true,
    canAccessMemberListPage: true,
    canAccessWorkflowListPage: true,
    canAccessAnalyticsPage: false,
    canAccessChatPage: true,
    canAccessSettingsPage: false,
    canAccessEducationCenterPage: true,
  },
  [UserOrganizationRole.GUEST]: {
    canAccessHomePage: true,
    canAccessSearchPage: true,
    canAccessTaskListPage: true,
    canAccessPeopleListPage: false,
    canAccessMemberListPage: true,
    canAccessWorkflowListPage: false,
    canAccessAnalyticsPage: false,
    canAccessChatPage: true,
    canAccessSettingsPage: false,
    canAccessEducationCenterPage: true,
  },
  [UserOrganizationRole.EXTERNAL]: {
    canAccessHomePage: true,
    canAccessSearchPage: true,
    canAccessTaskListPage: false,
    canAccessPeopleListPage: false,
    canAccessMemberListPage: false,
    canAccessWorkflowListPage: false,
    canAccessAnalyticsPage: false,
    canAccessChatPage: true,
    canAccessSettingsPage: false,
    canAccessEducationCenterPage: false,
  },
  [UserOrganizationRole.DOCK_PRO]: {
    canAccessHomePage: false,
    canAccessSearchPage: false,
    canAccessTaskListPage: false,
    canAccessPeopleListPage: false,
    canAccessMemberListPage: false,
    canAccessWorkflowListPage: true,
    canAccessAnalyticsPage: false,
    canAccessChatPage: false,
    canAccessSettingsPage: false,
    canAccessEducationCenterPage: false,
  },
};
