import { UserOrganizationRole } from 'helpers/user-helper';

export default {
  [UserOrganizationRole.OWNER]: {
    canAccessHomePage: true,
    canAccessSearchPage: true,
    canAccessTaskListPage: true,
    canAccessPeopleListPage: true,
    canAccessMemberListPage: true,
    canAccessWorkflowListPage: true,
    canAccessAnalyticsPage: true,
    canAccessChatPage: true,
    canAccessSettingsPage: true,
    canAccessEducationCenterPage: true,
  },
  [UserOrganizationRole.ADMIN]: {
    canAccessHomePage: true,
    canAccessSearchPage: true,
    canAccessTaskListPage: true,
    canAccessPeopleListPage: true,
    canAccessMemberListPage: true,
    canAccessWorkflowListPage: true,
    canAccessAnalyticsPage: true,
    canAccessChatPage: true,
    canAccessSettingsPage: true,
    canAccessEducationCenterPage: true,
  },
  [UserOrganizationRole.MEMBER]: {
    canAccessHomePage: true,
    canAccessSearchPage: true,
    canAccessTaskListPage: true,
    canAccessPeopleListPage: true,
    canAccessMemberListPage: true,
    canAccessWorkflowListPage: true,
    canAccessAnalyticsPage: false,
    canAccessChatPage: true,
    canAccessSettingsPage: false,
    canAccessEducationCenterPage: true,
  },
  [UserOrganizationRole.GUEST]: {
    canAccessHomePage: true,
    canAccessSearchPage: true,
    canAccessTaskListPage: true,
    canAccessPeopleListPage: false,
    canAccessMemberListPage: true,
    canAccessWorkflowListPage: false,
    canAccessAnalyticsPage: false,
    canAccessChatPage: true,
    canAccessSettingsPage: false,
    canAccessEducationCenterPage: true,
  },
  [UserOrganizationRole.EXTERNAL]: {
    canAccessHomePage: true,
    canAccessSearchPage: true,
    canAccessTaskListPage: false,
    canAccessPeopleListPage: false,
    canAccessMemberListPage: false,
    canAccessWorkflowListPage: false,
    canAccessAnalyticsPage: false,
    canAccessChatPage: true,
    canAccessSettingsPage: false,
    canAccessEducationCenterPage: false,
  },
  [UserOrganizationRole.DOCK_PRO]: {
    canAccessHomePage: false,
    canAccessSearchPage: false,
    canAccessTaskListPage: false,
    canAccessPeopleListPage: false,
    canAccessMemberListPage: false,
    canAccessWorkflowListPage: true,
    canAccessAnalyticsPage: false,
    canAccessChatPage: false,
    canAccessSettingsPage: false,
    canAccessEducationCenterPage: false,
  },
};
