export const workspaceUsersDummyData = [
  {
    id: 1,
    identifier: 1,
    name: 'Mohit Kumawat',
    email: 'mohit.kumawat@example.com',
    role: 'admin',
    status: 'active',
    isSelected: false,
  },
  {
    id: 2,
    identifier: 2,
    name: 'Aditya Chaurasia',
    email: 'aditya.chaurasia@example.com',
    role: 'member',
    status: 'resend invite',
    isSelected: false,
  },
  {
    id: 3,
    identifier: 3,
    name: 'Nitin Gujral',
    email: 'nitin.gujral@example.com',
    role: 'member',
    status: 'pending',
    isSelected: false,
  },
  {
    id: 4,
    identifier: 4,
    name: 'Tejas Patil',
    email: 'tejas.patil@example.com',
    role: 'admin',
    status: 'active',
    isSelected: false,
  },
  {
    id: 5,
    identifier: 5,
    name: 'AVeryLong UserNameMore',
    email: 'averylong.username@example.com',
    role: 'member',
    status: 'resend invite',
    isSelected: false,
  },
  {
    id: 6,
    identifier: 6,
    name: 'Adarsh Sharma',
    email: 'adarsh.sharma@example.com',
    role: 'admin',
    status: 'active',
    isSelected: false,
  },
];