export default {
  tasks: [],
  task: {description:"Hello"},
  completedTasks: [],
  allPatients: [],
  user: false,
  tasklist: [],
  pendingTasklists: [],
  tasklistone: {},
  tasklistmembers: [],
  orgusersnotintasklist: [],
  nonorgusersintasklist:[],
  tasklistactivemembers: [],
  invitationlist: [],
  peoplelist: [],
  tasklistaudits: [],
  auditsForAllUserList: [],
  activityFeedForAllUserList:[],
  title: "",
  currentList: {},
  currentTask: {},
  genericLists: [],
  users: []
  //addtasklisterror:''
}
