const NONE = 'None of the above';

export const ROLE_OPTIONS = [
  'CEO/Practice owner',
  'MD/DO/DMD/PhD/PsyD',
  'Psychologist / Mental Health Provider',
  'Nurse Practitioner',
  'Nurse',
  'Physician Assistant',
  'TCM Provider',
  'Medical Assistant',
  'Practice Manager',
  'Practice Administrator',
  'Care Coordinator',
  'LCSW',
  'Therapist (OT/PT/SLP)',
  'Case manager',
  'Dietician',
  'Pharmacist',
  'Virtual Assistant',
  'Medical Biller',
  NONE,
];

export const DOMAIN_OPTIONS = [
  'Allergy and Immunology',
  'Anesthesiology',
  'Dermatology',
  'Cardiology',
  'Critical Care',
  'Dentistry',
  'Diagnostic Radiology',
  'Emergency Medicine',
  'Endocrinology',
  'Family Medicine',
  'Gastroenterology',
  'Geriatrics',
  'Hematology',
  'Internal Medicine',
  'Infectious Disease',
  'Medical Genetics',
  'Mental Health',
  'Nephrology',
  'Neurology',
  'Nuclear Medicine',
  'Obstetrics and Gynecology',
  'Oncology',
  'Ophthamology',
  'Orthopaedics',
  'Otolaryngology',
  'Pathology',
  'Pediatrics',
  'Physical Medicine and Rehabilitation',
  'Plastic Surgery',
  'Podiatry',
  'Preventative Medicine',
  'Psychiatry',
  'Psychology',
  'Pulmonology',
  'Radiation Oncology',
  'Rheumatology',
  'Sleep Medicine',
  'Sports Medicine',
  'Surgery',
  'Urology',
  NONE,
];

export const HEALTH_RECORD_OPTIONS = [
  'Epic',
  'Cerner',
  'athenahealth',
  'Meditech',
  'Allscripts',
  'Simple Practice',
  'DrChrono',
  'eClinicalWorks',
  'Kareo',
  'McKesson',
  'Greenway',
  'NextGen',
  'Practice Fusion',
  NONE,
];

export const SOFTWARE_OPTIONS = [
  'Gmail',
  'Outlook',
  'Dropbox',
  'Box',
  'Google Drive',
  'IntakeQ',
  'JotForm',
  'Hubspot',
  'Salesforce',
  'Spruce',
  'RingCentral',
  NONE,
];
