// Global
export const RESET_APP = 'RESET_APP';

// Tasks
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_COMPLETED_TASKS_SUCCESS = 'GET_COMPLETED_TASKS_SUCCESS';
export const GET_COMPLETED_TASKS_SUCCESS_CUMULATIVE =
  'GET_COMPLETED_TASKS_SUCCESS_CUMULATIVE';
export const GET_TASKS_BY_GROUPS_SUCCESS = 'GET_TASKS_BY_GROUPS_SUCCESS';
export const GET_COMPLETED_TASKS_BY_GROUPS_SUCCESS =
  'GET_COMPLETED_TASKS_BY_GROUPS_SUCCESS';
export const GET_TASKS_COUNT_SUCCESS = 'GET_TASKS_COUNT_SUCCESS';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DUPLICATE_TASK_SUCCESS = 'DUPLICATE_TASK_SUCCESS';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const REFRESH_ANOTHER_TASK_SUCCESS = 'REFRESH_ANOTHER_TASK_SUCCESS';
export const TASK_READ_SUCCESS = 'TASK_READ_SUCCESS';
export const MOVE_TASK_SUCCESS = 'MOVE_TASK_SUCCESS';
export const MOVE_TASK_BETWEEN_LISTS = 'MOVE_TASK_BETWEEN_LISTS';
export const TOGGLE_TASK_PRIORITY_SUCCESS = 'TOGGLE_TASK_PRIORITY_SUCCESS';
export const EDIT_TASK = 'EDIT_TASK';
export const SET_AS_CURRENT_TASK = 'SET_AS_CURRENT_TASK';
export const SET_AS_CURRENT_TASK_WITH_SELECTED_TASK_CHECK =
  'SET_AS_CURRENT_TASK_WITH_SELECTED_TASK_CHECK';
export const SET_GENERIC_LIST_COUNTS = 'SET_GENERIC_LIST_COUNTS';
export const REQUEST_TASKS = 'REQUEST_TASKS';
export const REQUEST_COMPLETED_TASKS = 'REQUEST_COMPLETED_TASKS';
export const CLEAR_TASKS_SEARCH = 'CLEAR_TASKS_SEARCH';
export const REQUEST_HISTORY = 'REQUEST_HISTORY';
export const HIDE_COMPLETED_TASKS = 'HIDE_COMPLETED_TASKS';
export const GET_TASK_HISTORY_SUCCESS = 'GET_TASK_HISTORY_SUCCESS';
export const GET_TASK_HISTORY_ERROR = 'GET_TASK_HISTORY_ERROR';
export const ORDER_SUB_TASK_SUCCESS = 'ORDER_SUB_TASK_SUCCESS';
export const STORE_LIST_MEMBERS = 'STORE_LIST_MEMBERS';
export const CHANGE_ADDING_NEW_TASK = 'CHANGE_ADDING_NEW_TASK';
export const CHANGE_ADDING_NEW_SUBTASK = 'CHANGE_ADDING_NEW_SUBTASK';
export const TASK_ARCHIVED = 'TASK_ARCHIVED';
export const TASK_NEW_PAGE_DOWNLOADED = 'TASK_NEW_PAGE_DOWNLOADED';
export const UPDATED_SUBTASK_ORDER = 'UPDATED_SUBTASK_ORDER';
export const GET_MORE_TASKS_REQUEST = 'GET_MORE_TASKS_REQUEST';
export const TASK_COUNTERS_SUCCESS = 'TASK_COUNTERS_SUCCESS';
export const RESET_TASK_COUNTERS = 'RESET_TASK_COUNTERS';
export const INCREASE_INCOMPLETE_TASK_COUNTERS =
  'INCREASE_INCOMPLETE_TASK_COUNTERS';
export const INCREASE_COMPLETE_TASK_COUNTERS =
  'INCREASE_COMPLETE_TASK_COUNTERS';
export const REQUEST_TASKLIST_GROUP_TASKS = 'REQUEST_TASKLIST_GROUP_TASKS';
export const REQUEST_TASKLIST_GROUP_TASKS_SUCCESS =
  'REQUEST_TASKLIST_GROUP_TASKS_SUCCESS';
export const REQUEST_LOAD_SUBTASKS = 'REQUEST_LOAD_SUBTASKS';
export const LOAD_SUBTASKS_SUCCESS = 'LOAD_SUBTASKS_SUCCESS';
export const REQUEST_MULTIPLE_TASKLIST_GROUP_TASKS_SUCCESS =
  'REQUEST_MULTIPLE_TASKLIST_GROUP_TASKS_SUCCESS';

// Comments
export const ADD_TASK_COMMENT_SUCCESS = 'ADD_TASK_COMMENT_SUCCESS';
export const DELETE_TASK_COMMENT_SUCCESS = 'DELETE_TASK_COMMENT_SUCCESS';
export const UPDATE_TASK_COMMENT_SUCCESS = 'UPDATE_TASK_COMMENT_SUCCESS';

// Attachments
export const TASK_ATTACHMENT_ADDED = 'TASK_ATTACHMENT_ADDED';
export const TASK_ATTACHMENT_REMOVED = 'TASK_ATTACHMENT_REMOVED';

// Patient
export const FETCH_PATIENT = 'FETCH_PATIENT';
export const FETCH_PATIENT_SUCCESS = 'FETCH_PATIENT_SUCCESS';
export const FETCH_PATIENT_ERROR = 'FETCH_PATIENT_ERROR';
export const CLEAR_PATIENT = 'CLEAR_PATIENT';

// Patients
export const UPDATE_PATIENT_SUCCESS = 'UPDATE_PATIENT_SUCCESS';
export const DELETE_PATIENT_SUCCESS = 'DELETE_PATIENT_SUCCESS';
export const PATIENT_SELECTION_RESET = 'PATIENT_SELECTION_RESET';
export const ADD_PATIENT_NOTE = 'ADD_PATIENT_NOTE';
export const ADD_PATIENT_NOTE_ERROR = 'ADD_PATIENT_NOTE_ERROR';
export const DELETE_PATIENT_NOTE = 'DELETE_PATIENT_NOTE';
export const DELETE_PATIENT_NOTE_ERROR = 'DELETE_PATIENT_NOTE_ERROR';
export const UPDATE_PATIENT_NOTE = 'UPDATE_PATIENT_NOTE';
export const UPDATE_PATIENT_NOTE_ERROR = 'UPDATE_PATIENT_NOTE_ERROR';

// Tasklist
export const GET_TASKLIST_SUCCESS = 'GET_TASKLIST_SUCCESS';
export const GET_PENDING_TASKLIST_SUCCESS = 'GET_PENDING_TASKLIST_SUCCESS';
export const ADD_TASKLIST_SUCCESS = 'ADD_TASKLIST_SUCCESS';
export const DELETE_TASKLIST_SUCCESS = 'DELETE_TASKLIST_SUCCESS';
export const TOGGLE_LIST_NOTIFICATIONS_SUCCESS =
  'TOGGLE_LIST_NOTIFICATIONS_SUCCESS';
export const SET_AS_CURRENT_LIST = 'SET_AS_CURRENT_LIST';
export const REQUEST_LISTS = 'REQUEST_LISTS';
export const IS_LIST = 'IS_LIST';
export const IS_INBOX = 'IS_INBOX';

export const SET_CURRENT_LIST = 'SET_CURRENT_LIST';
export const UPDATE_TASKLIST_SUCCESS = 'UPDATE_TASKLIST_SUCCESS';
export const GET_TASKLISTMEMBERS_SUCCESS = 'GET_TASKLISTMEMBERS_SUCCESS';
export const INVITE_PERSON_TASKLIST_SUCCESS = 'INVITE_PERSON_TASKLIST_SUCCESS';
export const INVITEMULUSERS_TASKLIST_SUCCESS =
  'INVITEMULUSERS_TASKLIST_SUCCESS';
export const INVITE_USER_TO_TASKLIST_SUCCESS =
  'INVITE_USER_TO_TASKLIST_SUCCESS';
export const GET_NONORGUSERSINTASKLIST_SUCCESS =
  'GET_NONORGUSERSINTASKLIST_SUCCESS';
export const GET_TASKLISTACTIVEMEMBERS_SUCCESS =
  'GET_TASKLISTACTIVEMEMBERS_SUCCESS';
export const CHANGEUSERROLE_TASKLIST_SUCCESS =
  'CHANGEUSERROLE_TASKLIST_SUCCESS';
export const REMOVEUSER_TASKLIST_SUCCESS = 'REMOVEUSER_TASKLIST_SUCCESS';
export const CANCEL_TASKLIST_INVITE_SUCCESS = 'CANCEL_TASKLIST_INVITE_SUCCESS';
export const GET_AUDITS_BY_TASKLIST_SUCCESS = 'GET_AUDITS_BY_TASKLIST_SUCCESS';
export const GET_AUDITS_BY_ALLUSERLIST_SUCCESS =
  'GET_AUDITS_BY_ALLUSERLIST_SUCCESS';
export const GET_ACTIVITYFEED_BY_ALLUSERLIST_SUCCESS =
  'GET_ACTIVITYFEED_BY_ALLUSERLIST_SUCCESS';
export const GET_TASKLIST_STATS_SUCCESS = 'GET_TASKLIST_STATS_SUCCESS';
export const GET_TASKLIST_STATS_FAILURE = 'GET_TASKLIST_STATS_FAILURE';
export const RESET_TASKLIST_STATS = 'RESET_TASKLIST_STATS';
export const FETCH_TASKLIST_FOR_USER = 'FETCH_TASKLIST_FOR_USER';

// Invitation
export const GET_INVITATION_SUCCESS = 'GET_INVITATION_SUCCESS';
export const ACCEPT_INVITE_TOTASKLIST_SUCCESS =
  'ACCEPT_INVITE_TOTASKLIST_SUCCESS';
export const REJECT_INVITE_TOTASKLIST_SUCCESS =
  'REJECT_INVITE_TOTASKLIST_SUCCESS';

// People
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const INVITEPERSON_ORG_SUCCESS = 'INVITEPERSON_ORG_SUCCESS';
export const CHANGEUSERROLE_ORG_SUCCESS = 'CHANGEUSERROLE_ORG_SUCCESS';
export const CANCEL_USER_ORG_INVITE_SUCCESS = 'CANCEL_USER_ORG_INVITE_SUCCESS';
export const REMOVE_USER_ORG_SUCCESS = 'REMOVE_USER_ORG_SUCCESS';
export const ADD_USER_ORG_SUCCESS = 'ADD_USER_ORG_SUCCESS';
export const GET_USER_AVATAR_SUCCESS = 'GET_USER_AVATAR_SUCCESS';
export const REQUEST_PEOPLE = 'REQUEST_PEOPLE';

// Header
export const SET_HEADER = 'SET_HEADER';
export const UNSET_HEADER = 'UNSET_HEADER';
export const HIDE_HEADER = 'HIDE_HEADER';

// Organization
export const REQUEST_GET_ORGANIZATION = 'REQUEST_GET_ORGANIZATION';
export const GET_ORGANIZATION_SUCCESS = 'GET_ORGANIZATION_SUCCESS';
export const GET_ORGANIZATION_FAILURE = 'GET_ORGANIZATION_FAILURE';
export const REQUEST_GET_BILLING_ESTIMATE = 'REQUEST_GET_BILLING_ESTIMATE';
export const GET_BILLING_ESTIMATE_SUCCESS = 'GET_BILLING_ESTIMATE_SUCCESS';
export const GET_BILLING_ESTIMATE_FAILURE = 'GET_BILLING_ESTIMATE_FAILURE';
export const REQUEST_SAVE_BILLING_DETAILS = 'REQUEST_SAVE_BILLING_DETAILS';
export const SAVE_BILLING_DETAILS_SUCCESS = 'SAVE_BILLING_DETAILS_SUCCESS';
export const SAVE_BILLING_DETAILS_FAILURE = 'SAVE_BILLING_DETAILS_FAILURE';
export const REQUEST_GET_BILLING_DETAILS = 'REQUEST_GET_BILLING_DETAILS';
export const GET_BILLING_DETAILS_SUCCESS = 'GET_BILLING_DETAILS_SUCCESS';
export const GET_BILLING_DETAILS_FAILURE = 'GET_BILLING_DETAILS_FAILURE';
export const REQUEST_GET_INVOICE_DETAILS = 'REQUEST_GET_INVOICE_DETAILS';
export const GET_INVOICE_DETAILS_SUCCESS = 'GET_INVOICE_DETAILS_SUCCESS';
export const GET_INVOICE_DETAILS_FAILURE = 'GET_INVOICE_DETAILS_FAILURE';
export const SET_NEW_PAYMENT_PLAN = 'SET_NEW_PAYMENT_PLAN';
export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION';
export const SELECT_USERS_FOR_PLAN = 'SELECT_USERS_FOR_PLAN';

// User
export const USER_ACKNOWLEDGED_EULA = 'USER_ACKNOWLEDGED_EULA';

// Task drawer
export const SET_TASK_DRAWER_STATE = 'SET_TASK_DRAWER_STATE';

// Auth base
export const SET_AUTH_BASE_STATE = 'SET_AUTH_BASE_STATE';

// Referrals
export const GET_REFERRAL_CONFIG_FAILURE = 'GET_REFERRAL_CONFIG_FAILURE';
export const GET_REFERRAL_CONFIG_SUCCESS = 'GET_REFERRAL_CONFIG_SUCCESS';

// Task labels
export const REQUEST_ADDING_LABEL = 'REQUEST_ADDING_LABEL';
export const SUCCESS_ADDING_LABEL = 'SUCCESS_ADDING_LABEL';
export const FAILURE_ADDING_LABEL = 'FAILURE_ADDING_LABEL';
export const REQUEST_EDITING_LABEL = 'REQUEST_EDITING_LABEL';
export const SUCCESS_EDITING_LABEL = 'SUCCESS_EDITING_LABEL';
export const FAILURE_EDITING_LABEL = 'FAILURE_EDITING_LABEL';
export const REQUEST_REMOVING_TASK_LABEL = 'REQUEST_REMOVING_TASK_LABEL';
export const SUCCESS_REMOVING_TASK_LABEL = 'SUCCESS_REMOVING_TASK_LABEL';
export const FAILURE_REMOVING_TASK_LABEL = 'FAILURE_REMOVING_TASK_LABEL';
export const REQUEST_FETCHING_INBOX_LABELS = 'REQUEST_FETCHING_INBOX_LABELS';
export const SUCCESS_FETCHING_INBOX_LABELS = 'SUCCESS_FETCHING_INBOX_LABELS';
export const FAILURE_FETCHING_INBOX_LABELS = 'FAILURE_FETCHING_INBOX_LABELS';
export const REQUEST_FETCHING_LIST_LABELS = 'REQUEST_FETCHING_LIST_LABELS';
export const SUCCESS_FETCHING_LIST_LABELS = 'SUCCESS_FETCHING_LIST_LABELS';
export const FAILURE_FETCHING_LIST_LABELS = 'FAILURE_FETCHING_LIST_LABELS';
export const REQUEST_REMOVING_LABEL_FROM_DATABASE =
  'REQUEST_REMOVING_LABEL_FROM_DATABASE';
export const SUCCESS_REMOVING_LABEL_FROM_DATABASE =
  'SUCCESS_REMOVING_LABEL_FROM_DATABASE';
export const FAILURE_REMOVING_LABEL_FROM_DATABASE =
  'FAILURE_REMOVING_LABEL_FROM_DATABASE';

// Task Groups
export const TASK_GROUP_LIST_REQUEST = 'TASK_GROUP_LIST_REQUEST';
export const TASK_GROUP_LIST_SUCCESS = 'TASK_GROUP_LIST_SUCCESS';
export const TASK_GROUP_LIST_FAILURE = 'TASK_GROUP_LIST_FAILURE';

// Mega Filter
export const FETCH_MEGA_FILTERS_REQUEST = 'FETCH_MEGA_FILTERS_REQUEST';
export const FETCH_MEGA_FILTERS_SUCCESS = 'FETCH_MEGA_FILTERS_SUCCESS';
export const FETCH_MEGA_FILTERS_FAILURE = 'FETCH_MEGA_FILTERS_FAILURE';
export const SELECT_FILTERS_FROM_MEGA_FILTER =
  'SELECT_FILTERS_FROM_MEGA_FILTER';
export const CLEAR_MEGA_FILTERS = 'CLEAR_MEGA_FILTERS';
export const FETCH_MEGA_FILTERS_UPDATE_SUCCESS =
  'FETCH_MEGA_FILTERS_UPDATE_SUCCESS';

// Patient tasks
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const REQUEST_PATIENT_TASKS = 'REQUEST_PATIENT_TASKS';
export const REQUEST_PATIENT_TASKS_SUCCESS = 'REQUEST_PATIENT_TASKS_SUCCESS';
export const REQUEST_PATIENT_TASKS_FAILURE = 'REQUEST_PATIENT_TASKS_FAILURE';
export const REQUEST_PATIENT_STATS_SUCCESS = 'REQUEST_PATIENT_STATS_SUCCESS';
export const REQUEST_PATIENT_STATS_FAILURE = 'REQUEST_PATIENT_STATS_FAILURE';
export const CLEAR_PATIENT_TASKS = 'CLEAR_PATIENT_TASKS';
export const UPDATE_PATIENT_TASK = 'UPDATE_PATIENT_TASK';
export const INITIALIZE_PATIENT = 'INITIALIZE_PATIENT';
export const SET_PATIENT_TASK_SEARCH_VALUE = 'SET_PATIENT_TASK_SEARCH_VALUE';

// Template
export const SHOW_TEMPLATE_HEADER = 'SHOW_TEMPLATE_HEADER';
export const HIDE_TEMPLATE_HEADER = 'HIDE_TEMPLATE_HEADER';
export const SHOW_NAVBAR_SETTINGS = 'SHOW_NAVBAR_SETTINGS';
export const HIDE_NAVBAR_SETTINGS = 'HIDE_NAVBAR_SETTINGS';
export const ENABLE_NAVBAR_FULL_MODE = 'ENABLE_NAVBAR_FULL_MODE';
export const DISABLE_NAVBAR_FULL_MODE = 'DISABLE_NAVBAR_FULL_MODE';
export const SET_CUSTOM_NAVBAR_FULL_WIDTH = 'SET_CUSTOM_NAVBAR_FULL_WIDTH';
export const RESET_CUSTOM_NAVBAR_FULL_WIDTH = 'RESET_CUSTOM_NAVBAR_FULL_WIDTH';
export const SHOW_NAVBAR = 'SHOW_NAVBAR';
export const HIDE_NAVBAR = 'HIDE_NAVBAR';

// Dashboard tasks
export const REQUEST_DASHBOARD_TASKS = 'REQUEST_DASHBOARD_TASKS';
export const REQUEST_DASHBOARD_MORE_GROUP_TASKS =
  'REQUEST_DASHBOARD_MORE_GROUP_TASKS';
export const REQUEST_DASHBOARD_TASKS_SUCCESS =
  'REQUEST_DASHBOARD_TASKS_SUCCESS';
export const REQUEST_DASHBOARD_GROUP_TASKS_SUCCESS =
  'REQUEST_DASHBOARD_GROUP_TASKS_SUCCESS';
export const REQUEST_DASHBOARD_MORE_GROUP_TASKS_SUCCESS =
  'REQUEST_DASHBOARD_MORE_GROUP_TASKS_SUCCESS';
export const REQUEST_DASHBOARD_TASKS_FAILURE =
  'REQUEST_DASHBOARD_TASKS_FAILURE';
export const REQUEST_DASHBOARD_GROUP_TASKS =
  'REQUEST_DASHBOARD_SINGLE_SINGLE_GROUP_TASKS';

// Dashboard statistics
export const REQUEST_DASHBOARD_STATISTICS = 'REQUEST_DASHBOARD_STATISTICS';
export const REQUEST_DASHBOARD_STATISTICS_SUCCESS =
  'REQUEST_DASHBOARD_STATISTICS_SUCCESS';
export const REQUEST_DASHBOARD_STATISTICS_FAILURE =
  'REQUEST_DASHBOARD_STATISTICS_FAILURE';

// Global search
export const SEARCH_COMPLETED_TASKS = 'SEARCH_COMPLETED_TASKS';
export const SEARCH_INCOMPLETED_TASKS = 'SEARCH_INCOMPLETED_TASKS';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const GLOBAL_SEARCH_REQUEST = 'GLOBAL_SEARCH_REQUEST';
export const GLOBAL_SEARCH_REQUEST_SUCCESS = 'GLOBAL_SEARCH_REQUEST_SUCCESS';
export const GLOBAL_SEARCH_REQUEST_FAILURE = 'GLOBAL_SEARCH_REQUEST_FAILURE';
export const RESET_GLOBAL_SEARCH = 'RESET_GLOBAL_SEARCH';
export const UPDATE_GLOBAL_SEARCH_TASK = 'UPDATE_GLOBAL_SEARCH_TASK';
export const GLOBAL_SEARCH_MORE_REQUEST = 'GLOBAL_SEARCH_MORE_REQUEST';
export const GLOBAL_SEARCH_MORE_REQUEST_SUCCESS =
  'GLOBAL_SEARCH_MORE_REQUEST_SUCCESS';
export const GLOBAL_SEARCH_MORE_REQUEST_FAILURE =
  'GLOBAL_SEARCH_MORE_REQUEST_FAILURE';

// Person details
export const GET_PERSON_DETAILS_SUCCESS = 'GET_PERSON_DETAILS_SUCCESS';
export const GET_PERSON_DETAILS_FAILURE = 'GET_PERSON_DETAILS_FAILURE';
export const REQUEST_PERSON_TASKS = 'REQUEST_PERSON_TASKS';
export const REQUEST_PERSON_COMPLETED_TASKS = 'REQUEST_PERSON_COMPLETED_TASKS';
export const GET_PERSON_TASKS_SUCCESS = 'GET_PERSON_TASKS_SUCCESS';
export const GET_PERSON_COMPLETED_TASKS_SUCCESS =
  'GET_PERSON_COMPLETED_TASKS_SUCCESS';
export const GET_PERSON_TASK_COUNTERS_SUCCESS =
  'GET_PERSON_TASK_COUNTERS_SUCCESS';
export const RESET_PERSON_TASK_COUNTERS = 'RESET_PERSON_TASK_COUNTERS';
