// Global
export const RESET_APP = 'RESET_APP';

// Tasks
export const PUSH_TO_TEMPLATES_BREADCRUMBS = 'PUSH_TO_TEMPLATES_BREADCRUMBS';
export const CLEAN_AND_PUSH_TEMPLATES_BREADCRUMBS =
  'CLEAN_AND_PUSH_TEMPLATES_BREADCRUMBS';
export const CLEAN_TEMPLATES_BREADCRUMBS = 'CLEAN_TEMPLATES_BREADCRUMBS';
export const GET_TASK_TEMAPLTES_FOLDER = 'GET_TASK_TEMAPLTES_FOLDER';
export const ADD_TASK = 'ADD_TASK';
export const ADD_SUBTASK = 'ADD_SUBTASK';
export const DELETE_TASK = 'DELETE_TASK';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const SET_COMPLETE_STATUS = 'SET_COMPLETE_STATUS';
export const TASK_READ_SUCCESS = 'TASK_READ_SUCCESS';
export const SET_AS_CURRENT_TASK = 'SET_AS_CURRENT_TASK';
export const REQUEST_HISTORY = 'REQUEST_HISTORY';
export const GET_TASK_HISTORY_SUCCESS = 'GET_TASK_HISTORY_SUCCESS';
export const GET_TASK_HISTORY_ERROR = 'GET_TASK_HISTORY_ERROR';
export const CHANGE_ADDING_NEW_TASK = 'CHANGE_ADDING_NEW_TASK';
export const CHANGE_ADDING_NEW_SUBTASK = 'CHANGE_ADDING_NEW_SUBTASK';
export const REQUEST_LOAD_SUBTASKS = 'REQUEST_LOAD_SUBTASKS';
export const LOAD_SUBTASKS_SUCCESS = 'LOAD_SUBTASKS_SUCCESS';
export const OPEN_QUICK_ADD_SUBTASK_INPUT = 'OPEN_QUICK_ADD_SUBTASK_INPUT';
export const CLOSE_QUICK_ADD_SUBTASK_INPUT = 'CLOSE_QUICK_ADD_SUBTASK_INPUT';
export const UPDATE_TASKS_SUCCESS = 'UPDATE_TASKS_SUCCESS';
export const DELETE_TASKS_SUCCESS = 'DELETE_TASKS_SUCCESS';
export const COMPLETE_TASKS_SUCCESS = 'COMPLETE_TASKS_SUCCESS';
export const ADD_TASK_COMMENT_SUCCESS = 'ADD_TASK_COMMENT_SUCCESS';
export const DELETE_TASK_COMMENT_SUCCESS = 'DELETE_TASK_COMMENT_SUCCESS';
export const UPDATE_TASK_COMMENT_SUCCESS = 'UPDATE_TASK_COMMENT_SUCCESS';
export const TASK_ATTACHMENT_ADDED = 'TASK_ATTACHMENT_ADDED';
export const TASK_ATTACHMENT_REMOVED = 'TASK_ATTACHMENT_REMOVED';
export const UNSELECT_ALL_TASKS = 'UNSELECT_ALL_TASKS';
export const CHANGE_TASKS_SELECTED_STATE = 'CHANGE_TASKS_SELECTED_STATE';
export const OPEN_TASK_DRAWER_WITH_CONTENT = 'OPEN_TASK_DRAWER_WITH_CONTENT';
export const UPDATE_WORKFLOW_STATUS_FOR_TASKS =
  'UPDATE_WORKFLOW_STATUS_FOR_TASKS';
export const ADD_TASK_DEPENDENCY_LINK = 'ADD_TASK_DEPENDENCY_LINK';

// Template bundle
export const UPDATE_TEMPLATE_BUNDLE = 'UPDATE_TEMPLATE_BUNDLE';
export const ADD_TEMPLATE_BUNDLE = 'ADD_TEMPLATE_BUNDLE';
export const DELETE_TEMPLATE_BUNDLE = 'DELETE_TEMPLATE_BUNDLE';
export const COMPLETE_TEMPLATE_BUNDLE = 'COMPLETE_TEMPLATE_BUNDLE';

// List details
export const REQUEST_TASKS = 'REQUEST_TASKS';
export const REQUEST_COMPLETED_TASKS = 'REQUEST_COMPLETED_TASKS';
export const GET_MORE_TASKS_REQUEST = 'GET_MORE_TASKS_REQUEST';
export const GET_TASKS_BY_GROUPS_SUCCESS = 'GET_TASKS_BY_GROUPS_SUCCESS';
export const GET_COMPLETED_TASKS_BY_GROUPS_SUCCESS =
  'GET_COMPLETED_TASKS_BY_GROUPS_SUCCESS';
export const LIST_DETAILS_TASK_COUNTERS_SUCCESS =
  'LIST_DETAILS_TASK_COUNTERS_SUCCESS';
export const RESET_LIST_DETAILS_TASK_COUNTERS =
  'RESET_LIST_DETAILS_TASK_COUNTERS';
export const INCREASE_INCOMPLETE_TASK_COUNTERS =
  'INCREASE_INCOMPLETE_TASK_COUNTERS';
export const INCREASE_COMPLETE_TASK_COUNTERS =
  'INCREASE_COMPLETE_TASK_COUNTERS';
export const REQUEST_ALL_LIST_DETAILS_GROUPS =
  'REQUEST_ALL_LIST_DETAILS_GROUPS';
export const REQUEST_MULTIPLE_TASKLIST_GROUP_TASKS_SUCCESS =
  'REQUEST_MULTIPLE_TASKLIST_GROUP_TASKS_SUCCESS';
export const REQUEST_TASKLIST_GROUP_TASKS = 'REQUEST_TASKLIST_GROUP_TASKS';
export const REQUEST_TASKLIST_GROUP_TASKS_SUCCESS =
  'REQUEST_TASKLIST_GROUP_TASKS_SUCCESS';
export const SET_LIST_DETAILS_TASKS_SORT = 'SET_LIST_DETAILS_TASKS_SORT';
export const TASK_GROUP_LIST_REQUEST = 'TASK_GROUP_LIST_REQUEST';
export const TASK_GROUP_LIST_SUCCESS = 'TASK_GROUP_LIST_SUCCESS';
export const TASK_GROUP_LIST_FAILURE = 'TASK_GROUP_LIST_FAILURE';

// TaskList
export const GET_TASKLIST_SUCCESS = 'GET_TASKLIST_SUCCESS';
export const GET_ARCHIVED_TASKLIST_SUCCESS = 'GET_ARCHIVED_TASKLIST_SUCCESS';
export const GET_PENDING_TASKLIST_SUCCESS = 'GET_PENDING_TASKLIST_SUCCESS';
export const ADD_TASKLIST_SUCCESS = 'ADD_TASKLIST_SUCCESS';
export const DELETE_TASKLIST_SUCCESS = 'DELETE_TASKLIST_SUCCESS';
export const ARCHIVE_TASKLIST_SUCCESS = 'ARCHIVE_TASKLIST_SUCCESS';
export const UNARCHIVE_TASKLIST_SUCCESS = 'UNARCHIVE_TASKLIST_SUCCESS';
export const TOGGLE_LIST_NOTIFICATIONS_SUCCESS =
  'TOGGLE_LIST_NOTIFICATIONS_SUCCESS';
export const SET_AS_CURRENT_LIST = 'SET_AS_CURRENT_LIST';
export const REQUEST_LISTS = 'REQUEST_LISTS';
export const IS_LIST = 'IS_LIST';
export const IS_INBOX = 'IS_INBOX';
export const SET_CURRENT_LIST = 'SET_CURRENT_LIST';
export const UPDATE_TASKLIST_SUCCESS = 'UPDATE_TASKLIST_SUCCESS';
export const GET_TASKLISTMEMBERS_SUCCESS = 'GET_TASKLISTMEMBERS_SUCCESS';
export const INVITE_PERSON_TASKLIST_SUCCESS = 'INVITE_PERSON_TASKLIST_SUCCESS';
export const INVITEMULUSERS_TASKLIST_SUCCESS =
  'INVITEMULUSERS_TASKLIST_SUCCESS';
export const INVITE_USER_TO_TASKLIST_SUCCESS =
  'INVITE_USER_TO_TASKLIST_SUCCESS';
export const GET_NONORGUSERSINTASKLIST_SUCCESS =
  'GET_NONORGUSERSINTASKLIST_SUCCESS';
export const GET_TASKLISTACTIVEMEMBERS_SUCCESS =
  'GET_TASKLISTACTIVEMEMBERS_SUCCESS';
export const CHANGEUSERROLE_TASKLIST_SUCCESS =
  'CHANGEUSERROLE_TASKLIST_SUCCESS';
export const REMOVEUSER_TASKLIST_SUCCESS = 'REMOVEUSER_TASKLIST_SUCCESS';
export const CANCEL_TASKLIST_INVITE_SUCCESS = 'CANCEL_TASKLIST_INVITE_SUCCESS';
export const GET_AUDITS_BY_TASKLIST_SUCCESS = 'GET_AUDITS_BY_TASKLIST_SUCCESS';
export const GET_AUDITS_BY_ALLUSERLIST_SUCCESS =
  'GET_AUDITS_BY_ALLUSERLIST_SUCCESS';
export const GET_ACTIVITYFEED_BY_ALLUSERLIST_SUCCESS =
  'GET_ACTIVITYFEED_BY_ALLUSERLIST_SUCCESS';
export const GET_TASKLIST_STATS_SUCCESS = 'GET_TASKLIST_STATS_SUCCESS';
export const GET_TASKLIST_STATS_FAILURE = 'GET_TASKLIST_STATS_FAILURE';
export const RESET_TASKLIST_STATS = 'RESET_TASKLIST_STATS';
export const FETCH_TASKLIST_FOR_USER = 'FETCH_TASKLIST_FOR_USER';
export const ACCEPT_INVITE_TOTASKLIST_SUCCESS =
  'ACCEPT_INVITE_TOTASKLIST_SUCCESS';
export const REJECT_INVITE_TOTASKLIST_SUCCESS =
  'REJECT_INVITE_TOTASKLIST_SUCCESS';

// People list
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const INVITEPERSON_ORG_SUCCESS = 'INVITEPERSON_ORG_SUCCESS';
export const CHANGEUSERROLE_ORG_SUCCESS = 'CHANGEUSERROLE_ORG_SUCCESS';
export const CANCEL_USER_ORG_INVITE_SUCCESS = 'CANCEL_USER_ORG_INVITE_SUCCESS';
export const REMOVE_USER_ORG_SUCCESS = 'REMOVE_USER_ORG_SUCCESS';
export const ADD_USER_ORG_SUCCESS = 'ADD_USER_ORG_SUCCESS';
export const GET_USER_AVATAR_SUCCESS = 'GET_USER_AVATAR_SUCCESS';
export const REQUEST_PEOPLE = 'REQUEST_PEOPLE';

// Header
export const SET_HEADER = 'SET_HEADER';
export const UNSET_HEADER = 'UNSET_HEADER';
export const HIDE_HEADER = 'HIDE_HEADER';

// Organization
export const REQUEST_GET_ORGANIZATION = 'REQUEST_GET_ORGANIZATION';
export const GET_ORGANIZATION_SUCCESS = 'GET_ORGANIZATION_SUCCESS';
export const GET_ORGANIZATION_FAILURE = 'GET_ORGANIZATION_FAILURE';
export const REQUEST_GET_BILLING_ESTIMATE = 'REQUEST_GET_BILLING_ESTIMATE';
export const GET_BILLING_ESTIMATE_SUCCESS = 'GET_BILLING_ESTIMATE_SUCCESS';
export const GET_BILLING_ESTIMATE_FAILURE = 'GET_BILLING_ESTIMATE_FAILURE';
export const REQUEST_SAVE_BILLING_DETAILS = 'REQUEST_SAVE_BILLING_DETAILS';
export const SAVE_BILLING_DETAILS_SUCCESS = 'SAVE_BILLING_DETAILS_SUCCESS';
export const SAVE_BILLING_DETAILS_FAILURE = 'SAVE_BILLING_DETAILS_FAILURE';
export const REQUEST_GET_BILLING_DETAILS = 'REQUEST_GET_BILLING_DETAILS';
export const GET_BILLING_DETAILS_SUCCESS = 'GET_BILLING_DETAILS_SUCCESS';
export const GET_BILLING_DETAILS_FAILURE = 'GET_BILLING_DETAILS_FAILURE';
export const REQUEST_GET_INVOICE_DETAILS = 'REQUEST_GET_INVOICE_DETAILS';
export const GET_INVOICE_DETAILS_SUCCESS = 'GET_INVOICE_DETAILS_SUCCESS';
export const GET_INVOICE_DETAILS_FAILURE = 'GET_INVOICE_DETAILS_FAILURE';
export const SET_NEW_PAYMENT_PLAN = 'SET_NEW_PAYMENT_PLAN';
export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION';
export const SELECT_USERS_FOR_PLAN = 'SELECT_USERS_FOR_PLAN';
export const SET_FETCHING_ORGANIZATION_STATUSES =
  'SET_FETCHING_ORGANIZATION_STATUSES';
export const SET_ORGANIZATION_STATUSES = 'SET_ORGANIZATION_STATUSES';
export const SET_ORGANIZATION_STATUSES_ERROR =
  'SET_ORGANIZATION_STATUSES_ERROR';
export const DELETE_ORGANIZATION_STATUS = 'DELETE_ORGANIZATION_STATUS';
export const ADD_ORGANIZATION_STATUS = 'ADD_ORGANIZATION_STATUS';
export const UPDATE_ORGANIZATION_STATUS = 'UPDATE_ORGANIZATION_STATUS';

// User
export const USER_ACKNOWLEDGED_EULA = 'USER_ACKNOWLEDGED_EULA';

// Task drawer
export const SET_TASK_DRAWER_STATE = 'SET_TASK_DRAWER_STATE';

// Auth base
export const SET_AUTH_BASE_STATE = 'SET_AUTH_BASE_STATE';

// Referrals
export const GET_REFERRAL_CONFIG_FAILURE = 'GET_REFERRAL_CONFIG_FAILURE';
export const GET_REFERRAL_CONFIG_SUCCESS = 'GET_REFERRAL_CONFIG_SUCCESS';

// Mega Filter
export const FETCH_MEGA_FILTERS_REQUEST = 'FETCH_MEGA_FILTERS_REQUEST';
export const FETCH_MEGA_FILTERS_SUCCESS = 'FETCH_MEGA_FILTERS_SUCCESS';
export const FETCH_MEGA_FILTERS_FAILURE = 'FETCH_MEGA_FILTERS_FAILURE';
export const SELECT_FILTERS_FROM_MEGA_FILTER =
  'SELECT_FILTERS_FROM_MEGA_FILTER';
export const CLEAR_MEGA_FILTERS = 'CLEAR_MEGA_FILTERS';
export const FETCH_MEGA_FILTERS_UPDATE_SUCCESS =
  'FETCH_MEGA_FILTERS_UPDATE_SUCCESS';

// Template
export const SHOW_TEMPLATE_HEADER = 'SHOW_TEMPLATE_HEADER';
export const HIDE_TEMPLATE_HEADER = 'HIDE_TEMPLATE_HEADER';
export const SHOW_NAVBAR = 'SHOW_NAVBAR';
export const HIDE_NAVBAR = 'HIDE_NAVBAR';
export const SHOW_SUB_MENU = 'SHOW_SUB_MENU';
export const HIDE_SUB_MENU = 'HIDE_SUB_MENU';
export const OPEN_NOTIFICATIONS = 'OPEN_NOTIFICATIONS';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';

// Dashboard
export const REQUEST_DASHBOARD_TASKS = 'REQUEST_DASHBOARD_TASKS';
export const REQUEST_DASHBOARD_MORE_GROUP_TASKS =
  'REQUEST_DASHBOARD_MORE_GROUP_TASKS';
export const REQUEST_DASHBOARD_TASKS_SUCCESS =
  'REQUEST_DASHBOARD_TASKS_SUCCESS';
export const REQUEST_DASHBOARD_GROUP_TASKS_SUCCESS =
  'REQUEST_DASHBOARD_GROUP_TASKS_SUCCESS';
export const REQUEST_DASHBOARD_MORE_GROUP_TASKS_SUCCESS =
  'REQUEST_DASHBOARD_MORE_GROUP_TASKS_SUCCESS';
export const REQUEST_DASHBOARD_TASKS_FAILURE =
  'REQUEST_DASHBOARD_TASKS_FAILURE';
export const REQUEST_DASHBOARD_GROUP_TASKS =
  'REQUEST_DASHBOARD_SINGLE_SINGLE_GROUP_TASKS';
export const REQUEST_DASHBOARD_STATISTICS = 'REQUEST_DASHBOARD_STATISTICS';
export const REQUEST_DASHBOARD_STATISTICS_SUCCESS =
  'REQUEST_DASHBOARD_STATISTICS_SUCCESS';
export const REQUEST_DASHBOARD_STATISTICS_FAILURE =
  'REQUEST_DASHBOARD_STATISTICS_FAILURE';

// Global search
export const SEARCH_COMPLETED_TASKS = 'SEARCH_COMPLETED_TASKS';
export const SEARCH_INCOMPLETED_TASKS = 'SEARCH_INCOMPLETED_TASKS';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const GLOBAL_SEARCH_REQUEST = 'GLOBAL_SEARCH_REQUEST';
export const GLOBAL_SEARCH_REQUEST_SUCCESS = 'GLOBAL_SEARCH_REQUEST_SUCCESS';
export const GLOBAL_SEARCH_REQUEST_FAILURE = 'GLOBAL_SEARCH_REQUEST_FAILURE';
export const RESET_GLOBAL_SEARCH = 'RESET_GLOBAL_SEARCH';
export const UPDATE_GLOBAL_SEARCH_TASK = 'UPDATE_GLOBAL_SEARCH_TASK';
export const GLOBAL_SEARCH_MORE_REQUEST = 'GLOBAL_SEARCH_MORE_REQUEST';
export const GLOBAL_SEARCH_MORE_REQUEST_SUCCESS =
  'GLOBAL_SEARCH_MORE_REQUEST_SUCCESS';
export const GLOBAL_SEARCH_MORE_REQUEST_FAILURE =
  'GLOBAL_SEARCH_MORE_REQUEST_FAILURE';

// Person details
export const GET_PERSON_DETAILS_SUCCESS = 'GET_PERSON_DETAILS_SUCCESS';
export const GET_PERSON_DETAILS_FAILURE = 'GET_PERSON_DETAILS_FAILURE';
export const REQUEST_PERSON_TASKS = 'REQUEST_PERSON_TASKS';
export const REQUEST_PERSON_COMPLETED_TASKS = 'REQUEST_PERSON_COMPLETED_TASKS';
export const GET_PERSON_TASKS_SUCCESS = 'GET_PERSON_TASKS_SUCCESS';
export const GET_PERSON_COMPLETED_TASKS_SUCCESS =
  'GET_PERSON_COMPLETED_TASKS_SUCCESS';
export const GET_PERSON_TASK_COUNTERS_SUCCESS =
  'GET_PERSON_TASK_COUNTERS_SUCCESS';
export const RESET_PERSON_TASK_COUNTERS = 'RESET_PERSON_TASK_COUNTERS';
export const SORT_PERSON_TASKS = 'SORT_PERSON_TASKS';

// Patient details
export const SET_PATIENT_LABELS_FETCHING = 'SET_PATIENT_LABELS_FETCHING';
export const SET_PATIENT_LABELS = 'SET_PATIENT_LABELS';
export const SET_PATIENT_ATTACHMENTS_FETCHING =
  'SET_PATIENT_ATTACHMENTS_FETCHING';
export const SET_PATIENT_ATTACHMENTS = 'SET_PATIENT_ATTACHMENTS';
export const SET_PATIENT_FETCHING = 'SET_PATIENT_FETCHING';
export const SET_PATIENT = 'SET_PATIENT';
export const SET_COMPLETE_TASKS_VISIBILITY = 'SET_COMPLETE_TASKS_VISIBILITY';
export const REQUEST_PATIENT_TASKS = 'REQUEST_PATIENT_TASKS';
export const REQUEST_PATIENT_TASKS_SUCCESS = 'REQUEST_PATIENT_TASKS_SUCCESS';
export const REQUEST_PATIENT_TASKS_FAILURE = 'REQUEST_PATIENT_TASKS_FAILURE';
export const REQUEST_PATIENT_STATS_SUCCESS = 'REQUEST_PATIENT_STATS_SUCCESS';
export const REQUEST_PATIENT_STATS_FAILURE = 'REQUEST_PATIENT_STATS_FAILURE';
export const CLEAR_PATIENT_TASKS = 'CLEAR_PATIENT_TASKS';
export const UPDATE_PATIENT_TASK = 'UPDATE_PATIENT_TASK';
export const INITIALIZE_PATIENT = 'INITIALIZE_PATIENT';
export const SET_PATIENT_TASK_SEARCH_VALUE = 'SET_PATIENT_TASK_SEARCH_VALUE';
export const SORT_PATIENT_TASKS = 'SORT_PATIENT_TASKS';
export const UPDATE_PATIENT_NOTE = 'UPDATE_PATIENT_NOTE';
export const ADD_PATIENT_NOTE = 'ADD_PATIENT_NOTE';
export const REMOVE_PATIENT_NOTE = 'REMOVE_PATIENT_NOTE';
export const PIN_PATIENT_NOTE = 'PIN_PATIENT_NOTE';
export const UNPIN_PATIENT_NOTE = 'UNPIN_PATIENT_NOTE';
export const UPDATE_PATIENT_DETAILS = 'UPDATE_PATIENT_DETAILS';

// Task templates
export const TASK_TEMPLATES_FETCHING = 'TASK_TEMPLATES_FETCHING';
export const LOAD_TASK_TEMPLATES = 'LOAD_TASK_TEMPLATES';
export const LOAD_TASK_TEMPLATES_FOLDER = 'LOAD_TASK_TEMPLATES_FOLDER';
export const TASK_TEMPLATES_ERROR = 'TASK_TEMPLATES_ERROR';
export const LOAD_TASKS_FOR_TASK_TEMPLATE = 'LOAD_TASKS_FOR_TASK_TEMPLATE';
export const TASK_TEMPLATE_ERROR = 'TASK_TEMPLATE_ERROR';
export const TOGGLE_TASK_TEMPLATE_OPEN = 'TOGGLE_TASK_TEMPLATE_OPEN';
export const ADD_TASK_TEMPLATE = 'ADD_TASK_TEMPLATE';
export const DELETE_TASK_TEMPLATE = 'DELETE_TASK_TEMPLATE';
export const UPDATE_TASK_TEMPLATE = 'UPDATE_TASK_TEMPLATE';
export const ADD_TASK_TO_TEMPLATE = 'ADD_TASK_TO_TEMPLATE';
export const ADD_TASK_TO_TEMPLATE_SUCCESS = 'ADD_TASK_TO_TEMPLATE_SUCCESS';
export const CLOSE_ALL_TASK_TEMPLATES = 'CLOSE_ALL_TASK_TEMPLATES';
export const INITIALIZE_TASK_TEMPLATE_DETAILS =
  'INITIALIZE_TASK_TEMPLATE_DETAILS';
export const SELECT_TASK_TEMPLATE = 'SELECT_TASK_TEMPLATE';
export const UNSELECT_TASK_TEMPLATE = 'UNSELECT_TASK_TEMPLATE';
export const GET_TASK_TEMPLATE_LAYOUT = 'GET_TASK_TEMPLATE_LAYOUT';
export const GET_TASK_TEMPLATE_LAYOUT_SUCCESS =
  'GET_TASK_TEMPLATE_LAYOUT_SUCCESS';
export const SAVE_TASK_TEMPLATE_LAYOUT = 'SAVE_TASK_TEMPLATE_LAYOUT';
export const SAVE_TASK_TEMPLATE_LAYOUT_SUCCESS =
  'SAVE_TASK_TEMPLATE_LAYOUT_SUCCESS';
export const UPDATE_TASK_POSITION_IN_LAYOUT = 'UPDATE_TASK_POSITION_IN_LAYOUT';
export const GET_TASK_TEMPLATE_TASKS = 'GET_TASK_TEMPLATE_TASKS';
export const ADD_NEW_TASK_ELEMENT = 'ADD_NEW_TASK_ELEMENT';
export const ADD_NEW_DECISION_TASK_ELEMENT = 'ADD_NEW_DECISION_TASK_ELEMENT';
export const DELETE_TEMPORARY_ELEMENT = 'DELETE_TEMPORARY_ELEMENT';
export const LINK_TASKS = 'LINK_TASKS';
export const UPDATE_TASKS_LINK = 'UPDATE_TASKS_LINK';
export const DELETE_TASKS_LINK = 'DELETE_TASKS_LINK';
export const ADD_TASK_OUTCOME = 'ADD_TASK_OUTCOME';
export const UPDATE_TASK_OUTCOME = 'UPDATE_TASK_OUTCOME';
export const ADD_TEMPORARY_LINK = 'ADD_TEMPORARY_LINK';
export const GET_CURRENT_TASK_TEMPLATE = 'GET_CURRENT_TASK_TEMPLATE';
export const GET_CURRENT_TASK_TEMPLATE_SUCCESS =
  'GET_CURRENT_TASK_TEMPLATE_SUCCESS';

// Patients
export const GET_PATIENTS_LISTS_REQUEST = 'GET_PATIENTS_LISTS_REQUEST';
export const GET_PATIENTS_LISTS_SUCCESS = 'GET_PATIENTS_LISTS_SUCCESS';
export const DELETE_PATIENTS_LIST = 'DELETE_PATIENTS_LIST';
export const UPDATE_PATIENTS_LIST = 'UPDATE_PATIENTS_LIST';
