// Tasks
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const MARK_TASK_STATUS_SUCCESS = 'MARK_TASK_STATUS_SUCCESS';
export const UPDATE_TASK_DESCRIPTION_SUCCESS = 'UPDATE_TASK_DESCRIPTION_SUCCESS';
export const TOGGLE_TASK_PRIORITY_SUCCESS = 'TOGGLE_TASK_PRIORITY_SUCCESS';
export const ASSIGN_OR_REASSIGN_TASK_SUCCESS = 'ASSIGN_OR_REASSIGN_TASK_SUCCESS';

// Comments
export const ADD_TASK_COMMENT_SUCCESS = 'ADD_TASK_COMMENT_SUCCESS';

//Patients
export const GET_PATIENTS_SUCCESS = 'GET_PATIENTS_SUCCESS';
export const ADD_PATIENT_SUCCESS = 'ADD_PATIENT_SUCCESS';

//TASKLIST
export const GET_TASKLIST_SUCCESS = 'GET_TASKLIST_SUCCESS';
export const ADD_TASKLIST_SUCCESS = 'ADD_TASKLIST_SUCCESS';
//export const ADD_TASKLIST_FAILURE = 'ADD_TASKLIST_FAILURE';
export const GET_TASKLIST_ONE_SUCCESS = 'GET_TASKLIST_ONE_SUCCESS';
export const UPDATE_TASKLIST_SUCCESS = 'UPDATE_TASKLIST_SUCCESS';
export const GET_TASKLISTMEMBERS_SUCCESS = 'GET_TASKLISTMEMBERS_SUCCESS'
export const GET_ORGUSERSNOTINTASKLIST_SUCCESS='GET_ORGUSERSNOTINTASKLIST_SUCCESS';
export const INVITEPERSON_TASKLIST_SUCCESS='INVITEPERSON_TASKLIST_SUCCESS';
export const INVITEMULUSERS_TASKLIST_SUCCESS='INVITEMULUSERS_TASKLIST_SUCCESS';
export const GET_NONORGUSERSINTASKLIST_SUCCESS='GET_NONORGUSERSINTASKLIST_SUCCESS';
